<a href="https://colab.research.google.com/github/guilhermefrrr/ucl2425/blob/main/python-notebooks/extracting-fixtures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from google.colab import drive

In [2]:
pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_columns', None)  # Show all columns

In [3]:
df = pd.read_html('https://fbref.com/en/comps/8/schedule/Champions-League-Scores-and-Fixtures', attrs={"id": "sched_all"})[0]

In [4]:
df.head()

,Round,Wk,Day,Date,Time,Home,xG,Score,xG.1,Away,Attendance,Venue,Referee,Match Report,Notes
0,League phase,1,Tue,2024-09-17,18:45,Young Boys ch,0.6,0–3,2.0,eng Aston Villa,31500,Stadion Wankdorf,Georgi Kabakov,Match Report,NaN
1,League phase,1,Tue,2024-09-17,18:45,Juventus it,2.9,3–1,1.0,nl PSV Eindhoven,40417,Allianz Stadium,Alejandro Hernández,Match Report,NaN
2,League phase,1,Tue,2024-09-17,20:00,Sporting CP pt,1.6,2–0,0.4,fr Lille,40024,Estádio José Alvalade,Donatas Rumšas,Match Report,NaN
3,League phase,1,Tue,2024-09-17,21:00,Real Madrid es,2.6,3–1,1.9,de Stuttgart,71288,Estadio Santiago Bernabéu,Halil Umut Meler,Match Report,NaN
4,League phase,1,Tue,2024-09-17,21:00,Milan it,0.6,1–3,3.1,eng Liverpool,59826,Stadio Giuseppe Meazza,Espen Eskås,Match Report,NaN

In [5]:
df['Home'] = df['Home'].str.replace(r'\s[a-zA-Z]{2,3}$', '', regex=True, case=False)
df['Away'] = df['Away'].str.replace(r'^[a-zA-Z]{2,3}\s', '', regex=True, case=False)

In [6]:
df = df.drop(columns=['Match Report'])
df = df.drop(columns=['Notes'])

In [7]:
df = df.dropna(subset=['Score'])

In [8]:
df = df.rename(columns={'Wk': 'MD'})
df = df[df['Score'] != 'Score']

In [9]:
df['MD'] = pd.to_numeric(df['MD'], errors='coerce')

In [10]:
df.insert(df.columns.get_loc('MD') + 1, 'Match_ID', range(1, len(df) + 1))

In [11]:
# Split the 'Score' column
df[['Score_Home', 'Score_Away']] = df['Score'].str.split('–', expand=True)

In [12]:
score_index = df.columns.get_loc('Score')
df.insert(score_index, 'Score_Home', df.pop('Score_Home'))  # Move 'Score_Home'
df.insert(score_index + 1, 'Score_Away', df.pop('Score_Away')) # Move 'Score_Away'
df = df.drop(columns=['Score'])  # Remove 'Score'

In [13]:
df = df.rename(columns={'xG': 'xG_Home', 'xG.1': 'xG_Away'})

In [14]:
df.head()

,Round,MD,Match_ID,Day,Date,Time,Home,xG_Home,Score_Home,Score_Away,xG_Away,Away,Attendance,Venue,Referee
0,League phase,1.0,1,Tue,2024-09-17,18:45,Young Boys,0.6,0,3,2.0,Aston Villa,31500,Stadion Wankdorf,Georgi Kabakov
1,League phase,1.0,2,Tue,2024-09-17,18:45,Juventus,2.9,3,1,1.0,PSV Eindhoven,40417,Allianz Stadium,Alejandro Hernández
2,League phase,1.0,3,Tue,2024-09-17,20:00,Sporting CP,1.6,2,0,0.4,Lille,40024,Estádio José Alvalade,Donatas Rumšas
3,League phase,1.0,4,Tue,2024-09-17,21:00,Real Madrid,2.6,3,1,1.9,Stuttgart,71288,Estadio Santiago Bernabéu,Halil Umut Meler
4,League phase,1.0,5,Tue,2024-09-17,21:00,Milan,0.6,1,3,3.1,Liverpool,59826,Stadio Giuseppe Meazza,Espen Eskås

In [15]:
# Getting data from other file of this project
df1 = pd.read_csv('https://raw.githubusercontent.com/guilhermefrrr/ucl2425/refs/heads/main/complete-data/statsucl2425.csv')

In [16]:
df1.head()

,MD,Match_ID,Player,Squad,#,Nation,Age_Years,Age_Days,Pos,Min,Gls,Ast,PK,PKatt,Sh,SoT,CrdY,CrdR,Touches,Tkl,Int,Blocks,xG,npxG,xAG,SCA,GCA,Passes_Cmp,Passes_Att,Passes_Cmp%,Passes_PrgP,Carries,Carries_PrgC,Take-Ons_Att,Take-Ons_Succ,Total_TotDist,Total_PrgDist,Short_Cmp,Short_Att,Short_Cmp%,Medium_Cmp,Medium_Att,Medium_Cmp%,Long_Cmp,Long_Att,Long_Cmp%,xA,KP,1/3,PPA,CrsPA,Pass Types_Live,Pass Types_Dead,Pass Types_FK,Pass Types_TB,Pass Types_Sw,Pass Types_Crs,Pass Types_TI,Pass Types_CK,Corner Kicks_In,Corner Kicks_Out,Corner Kicks_Str,Outcomes_Cmp,Outcomes_Off,Outcomes_Blocks,Tackles_TklW,Tackles_Def 3rd,Tackles_Mid 3rd,Tackles_Att 3rd,Challenges_Tkl,Challenges_Att,Challenges_Tkl%,Challenges_Lost,Blocks_Sh,Blocks_Pass,Int.1,Tkl+Int,Clr,Err,Touches_Def Pen,Touches_Def 3rd,Touches_Mid 3rd,Touches_Att 3rd,Touches_Att Pen,Take-Ons_Succ%,Take-Ons_Tkld,Take-Ons_Tkld%,Carries_TotDist,Carries_PrgDist,Carries_1/3,Carries_CPA,Carries_Mis,Carries_Dis,Rec,PrgR,2CrdY,Fls,Fld,Off,Crs,TklW,PKwon,PKcon,OG,Recov,Aerial Duels_Won,Aerial Duels_Lost,Aerial Duels_Won%
0,1,1,Abdu Conté,Young Boys,22,POR,26,177,LB,28,0,0,0,0,0,0,0,0,9,0,0,1,0.0,0.0,0.0,0,0,5,8,62.5,1,5,1,0,0,91,26,2,5,40.0,3,3,100.0,0,0,NaN,0.0,0,1,0,0,7,1,0,0,0,0,1,0,0,0,0,5,0,0,0,0,0,0,0,0,NaN,0,1,0,0,0,0,0,1,2,5,2,0,NaN,0,NaN,29,18,1,0,0,0,4,0,0,0,0,0,0,0,0,0,0,1,0,0,NaN
1,1,1,Alan Virginius,Young Boys,21,FRA,21,258,"RM,FW",28,0,0,0,0,1,0,0,0,3,0,0,0,0.0,0.0,0.0,0,0,0,0,NaN,0,2,1,0,0,0,0,0,0,NaN,0,0,NaN,0,0,NaN,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,1,0,2,1,NaN,0,NaN,17,7,0,1,0,0,2,1,0,1,0,0,0,0,0,0,0,0,0,0,NaN
2,1,1,Cedric Itten,Young Boys,9,SUI,27,265,FW,8,0,0,0,0,1,0,0,0,5,0,0,0,0.0,0.0,0.0,2,0,3,4,75.0,1,2,0,0,0,33,5,1,1,100.0,1,1,100.0,0,0,NaN,0.0,0,0,0,0,2,1,0,0,0,0,0,0,0,0,0,3,1,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,2,3,1,NaN,0,NaN,10,5,0,0,0,0,3,1,0,0,0,0,0,0,0,0,0,0,1,0,100.0
3,1,1,Cheikh Tidiane Niasse,Young Boys,20,SEN,24,242,DM,45,0,0,0,0,0,0,1,0,28,1,0,0,0.0,0.0,0.0,0,0,20,25,80.0,2,20,3,2,2,342,54,9,11,81.8,6,6,100.0,3,5,60.0,0.0,0,0,0,0,25,0,0,0,0,0,0,0,0,0,0,20,0,0,0,0,1,0,1,1,100.0,0,0,0,0,1,0,0,1,5,19,5,0,100.0,0,0.0,145,103,1,0,1,2,22,2,0,1,2,0,0,0,0,0,0,2,1,0,100.0
4,1,1,Darian Males,Young Boys,39,SUI,23,137,LM,8,0,0,0,0,0,0,0,0,6,2,0,0,0.0,0.0,0.0,0,0,1,3,33.3,0,1,0,1,0,36,0,0,0,NaN,0,0,NaN,1,3,33.3,0.0,0,0,0,0,2,1,0,0,0,2,0,1,0,1,0,1,0,0,2,0,0,2,0,0,NaN,0,0,0,0,2,0,0,0,0,1,5,0,0.0,1,100.0,2,0,0,0,1,0,2,1,0,0,0,0,2,2,0,0,0,0,0,0,NaN

In [17]:
squads_df = pd.unique(df[['Home', 'Away']].values.ravel('K'))
squads_df1 = df1['Squad'].unique()

# Squads in df and out of df1
not_in_df1 = list(set(squads_df) - set(squads_df1))

# Squads in df1 and out of df
not_in_df = list(set(squads_df1) - set(squads_df))

print("Squads in df and out of df1:", not_in_df1)
print("Squads in df1 and out of df:", not_in_df)

Squads in df and out of df1: []
Squads in df1 and out of df: []

In [18]:
squads_mapping = {
    'Shakhtar': 'Shakhtar Donetsk',
    'Leverkusen': 'Bayer Leverkusen',
    'Paris S-G': 'Paris Saint-Germain',
    'Red Star': 'Red Star Belgrade',
    'RB Salzburg': 'Red Bull Salzburg',
    'Inter': 'Internazionale'
}

In [19]:
df['Home'] = df['Home'].replace(squads_mapping)
df['Away'] = df['Away'].replace(squads_mapping)

In [20]:
df.head()

,Round,MD,Match_ID,Day,Date,Time,Home,xG_Home,Score_Home,Score_Away,xG_Away,Away,Attendance,Venue,Referee
0,League phase,1.0,1,Tue,2024-09-17,18:45,Young Boys,0.6,0,3,2.0,Aston Villa,31500,Stadion Wankdorf,Georgi Kabakov
1,League phase,1.0,2,Tue,2024-09-17,18:45,Juventus,2.9,3,1,1.0,PSV Eindhoven,40417,Allianz Stadium,Alejandro Hernández
2,League phase,1.0,3,Tue,2024-09-17,20:00,Sporting CP,1.6,2,0,0.4,Lille,40024,Estádio José Alvalade,Donatas Rumšas
3,League phase,1.0,4,Tue,2024-09-17,21:00,Real Madrid,2.6,3,1,1.9,Stuttgart,71288,Estadio Santiago Bernabéu,Halil Umut Meler
4,League phase,1.0,5,Tue,2024-09-17,21:00,Milan,0.6,1,3,3.1,Liverpool,59826,Stadio Giuseppe Meazza,Espen Eskås

In [21]:
squads_df = pd.unique(df[['Home', 'Away']].values.ravel('K'))
squads_df1 = df1['Squad'].unique()

# Squads in df and out of df1
not_in_df1 = list(set(squads_df) - set(squads_df1))

# Squads in df1 and out of df
not_in_df = list(set(squads_df1) - set(squads_df))

print("Squads in df and out of df1:", not_in_df1)
print("Squads in df1 and out of df:", not_in_df)

Squads in df and out of df1: ['Paris Saint-Germain', 'Internazionale', 'Bayer Leverkusen', 'Red Bull Salzburg', 'Red Star Belgrade', 'Shakhtar Donetsk']
Squads in df1 and out of df: ['Leverkusen', 'Shakhtar', 'RB Salzburg', 'Inter', 'Paris S-G', 'Red Star']

In [22]:
file_path = '/content/drive/MyDrive/Dados/Projetos/UCL_2425/fixturesucl2425.csv'

# Mount Google Drive to save file (if necessary)
drive.mount('/content/drive')

Mounted at /content/drive

In [23]:
#df.to_csv(file_path, index=False)