In [7]:
import pandas as pd

pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)


# URL da página com a tabela de jogos
url = "https://fbref.com/en/comps/8/schedule/Champions-League-Scores-and-Fixtures"

# Lê a tabela HTML da página usando pandas com extract_links=True
dfs = pd.read_html(url, extract_links='body')

# Get the first dataframe from the list
df = dfs[0]

# Convert the 'Match Report' column to string type
df['Match Report'] = df['Match Report'].astype(str)

# Filter the dataframe and create copy
df = df[df['Match Report'].str.contains('Match Report', na=False)].copy()

# Extract links and assign to a new column
df.loc[:, 'URL'] = df['Match Report'].str.extract(r'(en/matches/\S+)')[0].str.rstrip(")'")

df = df.dropna(subset=['URL'])
df['URL'] = [f"https://fbref.com/{link}" for link in df['URL']]

df.reset_index(drop=True, inplace=True)

df

,Round,Wk,Day,Date,Time,Home,xG,Score,xG.1,Away,Attendance,Venue,Referee,Match Report,Notes,URL
0,"(League phase, /en/comps/8/Champions-League-Stats)","(1, None)","(Tue, None)","(2024-09-17, /en/matches/2024-09-17)","(18:45, None)","(Young Boys ch, /en/squads/4b682260/Young-Boys-Stats)","(0.6, None)","(0–3, /en/matches/568274fc/Young-Boys-Aston-Villa-September-17-2024-Champions-League)","(2.0, None)","(eng Aston Villa, /en/squads/8602292d/Aston-Villa-Stats)","(31,500, None)","(Stadion Wankdorf, None)","(Georgi Kabakov, None)","('Match Report', '/en/matches/568274fc/Young-Boys-Aston-Villa-September-17-2024-Champions-League')","(, None)",https://fbref.com/en/matches/568274fc/Young-Boys-Aston-Villa-September-17-2024-Champions-League
1,"(League phase, /en/comps/8/Champions-League-Stats)","(1, None)","(Tue, None)","(2024-09-17, /en/matches/2024-09-17)","(18:45, None)","(Juventus it, /en/squads/e0652b02/Juventus-Stats)","(2.9, None)","(3–1, /en/matches/931cd5fb/Juventus-PSV-Eindhoven-September-17-2024-Champions-League)","(1.0, None)","(nl PSV Eindhoven, /en/squads/e334d850/PSV-Eindhoven-Stats)","(40,417, None)","(Allianz Stadium, None)","(Alejandro Hernández, None)","('Match Report', '/en/matches/931cd5fb/Juventus-PSV-Eindhoven-September-17-2024-Champions-League')","(, None)",https://fbref.com/en/matches/931cd5fb/Juventus-PSV-Eindhoven-September-17-2024-Champions-League
2,"(League phase, /en/comps/8/Champions-League-Stats)","(1, None)","(Tue, None)","(2024-09-17, /en/matches/2024-09-17)","(20:00, None)","(Sporting CP pt, /en/squads/13dc44fd/Sporting-CP-Stats)","(1.6, None)","(2–0, /en/matches/aaca158d/Sporting-CP-Lille-September-17-2024-Champions-League)","(0.4, None)","(fr Lille, /en/squads/cb188c0c/Lille-Stats)","(40,024, None)","(Estádio José Alvalade, None)","(Donatas Rumšas, None)","('Match Report', '/en/matches/aaca158d/Sporting-CP-Lille-September-17-2024-Champions-League')","(, None)",https://fbref.com/en/matches/aaca158d/Sporting-CP-Lille-September-17-2024-Champions-League
3,"(League phase, /en/comps/8/Champions-League-Stats)","(1, None)","(Tue, None)","(2024-09-17, /en/matches/2024-09-17)","(21:00, None)","(Real Madrid es, /en/squads/53a2f082/Real-Madrid-Stats)","(2.6, None)","(3–1, /en/matches/4fb5fcbd/Real-Madrid-Stuttgart-September-17-2024-Champions-League)","(1.9, None)","(de Stuttgart, /en/squads/598bc722/Stuttgart-Stats)","(71,288, None)","(Estadio Santiago Bernabéu, None)","(Halil Umut Meler, None)","('Match Report', '/en/matches/4fb5fcbd/Real-Madrid-Stuttgart-September-17-2024-Champions-League')","(, None)",https://fbref.com/en/matches/4fb5fcbd/Real-Madrid-Stuttgart-September-17-2024-Champions-League
4,"(League phase, /en/comps/8/Champions-League-Stats)","(1, None)","(Tue, None)","(2024-09-17, /en/matches/2024-09-17)","(21:00, None)","(Milan it, /en/squads/dc56fe14/Milan-Stats)","(0.6, None)","(1–3, /en/matches/54ed5557/Milan-Liverpool-September-17-2024-Champions-League)","(3.1, None)","(eng Liverpool, /en/squads/822bd0ba/Liverpool-Stats)","(59,826, None)","(Stadio Giuseppe Meazza, None)","(Espen Eskås, None)","('Match Report', '/en/matches/54ed5557/Milan-Liverpool-September-17-2024-Champions-League')","(, None)",https://fbref.com/en/matches/54ed5557/Milan-Liverpool-September-17-2024-Champions-League
5,"(League phase, /en/comps/8/Champions-League-Stats)","(1, None)","(Tue, None)","(2024-09-17, /en/matches/2024-09-17)","(21:00, None)","(Bayern Munich de, /en/squads/054efa67/Bayern-Munich-Stats)","(5.9, None)","(9–2, /en/matches/7c5c2955/Bayern-Munich-Dinamo-Zagreb-September-17-2024-Champions-League)","(0.7, None)","(hr Dinamo Zagreb, /en/squads/edd0d381/Dinamo-Zagreb-Stats)","(75,000, None)","(Allianz Arena, None)","(Juan Martínez, None)","('Match Report', '/en/matches/7c5c2955/Bayern-Munich-Dinamo-Zagreb-September-17-2024-Champions-League')","(, None)",https://fbref.com/en/matches/7c5c2955/Bayern-Munich-Dinamo-Zagreb-September-17-2024-Champions-League
6,"(League phase, /en/comps/8/Champions-League-Stats)","(1, None)","(Wed, None)","(2024-09-18, /en/matches/2024-09-18)","(18:45, None)","(Sparta Prague cz, /en/squads/ecb862be/Sparta-Prague-Stats)","(2.5, None)","(3–0, /en/matches/936f3ee0/Sparta-Prague-Red-Bull-Salzburg-September-18-2024-Champions-League)","(0.6, None)","(at RB Salzburg, /en/squads/50f2a074/Red-Bull-Salzburg-Stats)","(17,612, None)","(epet Arena, None)","(Rade Obrenović, None)","('Match Report', '/en/matches/936f3ee0/Sparta-Prague-Red-Bull-Salzburg-September-18-2024-Champions-League')","(, None)",https://fbref.com/en/matches/936f3ee0/Sparta-Prague-Red-Bull-Salzburg-September-18-2024-Champions-League
7,"(League phase, /en/comps/8/Champions-League-Stats)","(1, None)","(Wed, None)","(2024-09-18, /en/matches/2024-09-18)","(18:45, None)","(Bologna it, /en/squads/1d8099f8/Bologna-Stats)","(1.2, None)","(0–0, /en/matches/85075de5/Bologna-Shakhtar-Donetsk-September-18-2024-Champions-League)","(0.9, None)","(ua Shakhtar, /en/squads/e89d5a28/Shakhtar-Donetsk-Stats)","(23,130, None)","(Stadio Renato Dall'Ara, None)","(Rohit Saggi, None)","('Match Report', '/en/matches/85075de5/Bologna-Shakhtar-Donetsk-September-18-2024-Champions-League')","(, None)",https://fbref.com/en/matches/85075de5/Bologna-Shakhtar-Donetsk-September-18-2024-Champions-League
8,"(League phase, /en/comps/8/Champions-League-Stats)","(1, None)","(Wed, None)","(2024-09-18, /en/matches/2024-09-18)","(20:00, None)","(Celtic sct, /en/squads/b81aa4fa/Celtic-Stats)","(3.8, None)","(5–1, /en/matches/16af036c/Celtic-Slovan-Bratislava-September-18-2024-Champions-League)","(0.5, None)","(sk Slovan Bratislava, /en/squads/ae7f2f70/Slovan-Bratislava-Stats)","(56,826, None)","(Celtic Park, None)","(Danny Makkelie, None)","('Match Report', '/en/matches/16af036c/Celtic-Slovan-Bratislava-September-18-2024-Champions-League')","(, None)",https://fbref.com/en/matches/16af036c/Celtic-Slovan-Bratislava-September-18-2024-Champions-League
9,"(League phase, /en/comps/8/Champions-League-Stats)","(1, None)","(Wed, None)","(2024-09-18, /en/matches/2024-09-18)","(20:00, None)","(Manchester City eng, /en/squads/b8fd03ef/Manchester-City-Stats)","(2.3, None)","(0–0, /en/matches/db400f4b/Manchester-City-Internazionale-September-18-2024-Champions-League)","(0.7, None)","(it Inter, /en/squads/d609edc0/Internazionale-Stats)","(50,922, None)","(Etihad Stadium, None)","(Glenn Nyberg, None)","('Match Report', '/en/matches/db400f4b/Manchester-City-Internazionale-September-18-2024-Champions-League')","(, None)",https://fbref.com/en/matches/db400f4b/Manchester-City-Internazionale-September-18-2024-Champions-League
10,"(League phase, /en/comps/8/Champions-League-Stats)","(1, None)","(Wed, None)","(2024-09-18, /en/matches/2024-09-18)","(21:00, None)","(Club Brugge be, /en/squads/f1e6c5f1/Club-Brugge-Stats)","(1.2, None)","(0–3, /en/matches/722df76c/Club-Brugge-Dortmund-September-18-2024-Champions-League)","(1.9, None)","(de Dortmund, /en/squads/add600ae/Dortmund-Stats)","(19,961, None)","(Jan Breydelstadion, None)","(Irfan Peljto, None)","('Match Report', '/en/matches/722df76c/Club-Brugge-Dortmund-September-18-2024-Champions-League')","(, None)",https://fbref.com/en/matches/722df76c/Club-Brugge-Dortmund-September-18-2024-Champions-League
11,"(League phase, /en/comps/8/Champions-League-Stats)","(1, None)","(Wed, None)","(2024-09-18, /en/matches/2024-09-18)","(21:00, None)","(Paris S-G fr, /en/squads/e2d8892c/Paris-Saint-Germain-Stats)","(2.1, None)","(1–0, /en/matches/53cfba8e/Paris-Saint-Germain-Girona-September-18-2024-Champions-League)","(0.2, None)","(es Girona, /en/squads/9024a00a/Girona-Stats)","(39,951, None)","(Parc des Princes, None)","(Daniel Siebert, None)","('Match Report', '/en/matches/53cfba8e/Paris-Saint-Germain-Girona-September-18-2024-Champions-League')","(, None)",https://fbref.com/en/matches/53cfba8e/Paris-Saint-Germain-Girona-September-18-2024-Champions-League
12,"(League phase, /en/comps/8/Champions-League-Stats)","(1, None)","(Thu, None)","(2024-09-19, /en/matches/2024-09-19)","(18:45, None)","(Red Star rs, /en/squads/099c6eb5/Red-Star-Belgrade-Stats)","(1.0, None)","(1–2, /en/matches/2d931c93/Red-Star-Belgrade-Benfica-September-19-2024-Champions-League)","(1.3, None)","(pt Benfica, /en/squads/a77c513e/Benfica-Stats)","(44,238, None)","(Stadion Rajko Mitić, None)","(Michael Oliver, None)","('Match Report', '/en/matches/2d931c93/Red-Star-Belgrade-Benfica-September-19-2024-Champions-League')","(, None)",https://fbref.com/en/matches/2d931c93/Red-Star-Belgrade-Benfica-September-19-2024-Champions-League
13,"(League phase, /en/comps/8/Champions-League-Stats)","(1, None)","(Thu, None)","(2024-09-19, /en/matches/2024-09-19)","(18:45, None)","(Feyenoord nl, /en/squads/fb4ca611/Feyenoord-Stats)","(0.8, None)","(0–4, /en/matches/24c1d39c/Feyenoord-Bayer-Leverkusen-September-19-2024-Champions-League)","(1.7, None)","(de Leverkusen, /en/squads/c7a9f859/Bayer-Leverkusen-Stats)","(42,297, None)","(Stadion Feijenoord, None)","(Davide Massa, None)","('Match Report', '/en/matches/24c1d39c/Feyenoord-Bayer-Leverkusen-September-19-2024-Champions-League')","(, None)",https://fbref.com/en/matches/24c1d39c/Feyenoord-Bayer-Leverkusen-September-19-2024-Champions-League
14,"(League phase, /en/comps/8/Champions-League-Stats)","(1, None)","(Thu, None)","(2024-09-19, /en/matches/2024-09-19)","(21:00, None)","(Monaco fr, /en/squads/fd6114db/Monaco-Stats)","(1.3, None)","(2–1, /en/matches/745d19c2/Monaco-Barcelona-September-19-2024-Champions-League)","(0.4, None)","(es Barcelona, /en/squads/206d90db/Barcelona-Stats)","(13,296, None)","(Stade Louis II, None)","(Allard Lindhout, None)","('Match Report', '/en/matches/745d19c2/Monaco-Barcelona-September-19-2024-Champions-League')","(, None)",https://fbref.com/en/matches/745d19c2/Monaco-Barcelona-September-19-2024-Champions-League
15,"(League phase, /en/comps/8/Champions-League-Stats)","(1, None)","(Thu, None)","(2024-09-19, /en/matches/2024-09-19)","(21:00, None)","(Atalanta it, /en/squads/922493f3/Atalanta-Stats)","(1.2, None)","(0–0, /en/matches/108b9e41/Atalanta-Arsenal-September-19-2024-Champions-League)","(0.8, None)","(eng Arsenal, /en/squads/18bb7c10/Arsenal-Stats)","(22,858, None)","(Gewiss Stadium, None)","(Clément Turpin, None)","('Match Report', '/en/matches/108b9e41/Atalanta-Arsenal-September-19-2024-Champions-League')","(, None)",https://fbref.com/en/matches/108b9e41/Atalanta-Arsenal-September-19-2024-Champions-League
16,"(League phase, /en/comps/8/Champions-League-Stats)","(1, None)","(Thu, None)","(2024-09-19, /en/matches/2024-09-19)","(21:00, None)","(Brest fr, /en/squads/fb08dbb3/Brest-Stats)","(2.1, None)","(2–1, /en/matches/162f5233/Brest-Sturm-Graz-September-19-2024-Champions-League)","(0.5, None)","(at Sturm Graz, /en/squads/3f4fe568/Sturm-Graz-Stats)","(14,518, None)","(Stade du Roudourou, None)","(Nick Walsh, None)","('Match Report', '/en/matches/162f5233/Brest-Sturm-Graz-September-19-2024-Champions-League')","(, None)",https://fbref.com/en/matches/162f5233/Brest-Sturm-Graz-September-19-2024-Champions-League
17,"(League phase, /en/comps/8/Champions-League-Stats)","(1, None)","(Thu, None)","(2024-09-19, /en/matches/2024-09-19)","(21:00, None)","(Atlético Madrid es, /en/squads/db3b9613/Atletico-Madrid-Stats)","(1.7, None)","(2–1, /en/matches/a112dcca/Atletico-Madrid-RB-Leipzig-September-19-2024-Champions-League)","(0.7, None)","(de RB Leipzig, /en/squads/acbb6a5b/RB-Leipzig-Stats)","(57,856, None)","(Riyadh Air Metropolitan Stadium, None)","(Ivan Kružliak, None)","('Match Report', '/en/matches/a112dcca/Atletico-Madrid-RB-Leipzig-September-19-2024-Champions-League')","(, None)",https://fbref.com/en/matches/a112dcca/Atletico-Madrid-RB-Leipzig-September-19-2024-Champions-League
18,"(League phase, /en/comps/8/Champions-League-Stats)","(2, None)","(Tue, None)","(2024-10-01, /en/matches/2024-10-01)","(18:45, None)","(Stuttgart de, /en/squads/598bc722/Stuttgart-Stats)","(1.7, None)","(1–1, /en/matches/80c7f5c5/Stuttgart-Sparta-Prague-October-1-2024-Champions-League)","(1.0, None)","(cz Sparta Prague, /en/squads/ecb862be/Sparta-Prague-Stats)","(60,000, None)","(MHPArena, None)","(Manfredas Lukjančukas, None)","('Match Report', '/en/matches/80c7f5c5/Stuttgart-Sparta-Prague-October-1-2024-Champions-League')","(, None)",https://fbref.com/en/matches/80c7f5c5/Stuttgart-Sparta-Prague-October-1-2024-Champions-League
19,"(League phase, /en/comps/8/Champions-League-Stats)","(2, None)","(Tue, None)","(2024-10-01, /en/matches/2024-10-01)","(18:45, None)","(RB Salzburg at, /en/squads/50f2a074/Red-Bull-Salzburg-Stats)","(1.6, None)","(0–4, /en/matches/aa293551/Red-Bull-Salzburg-Brest-October-1-2024-Champions-League)","(2.0, None)","(fr Brest, /en/squads/fb08dbb3/Brest-Stats)","(20,232, None)","(Red Bull Arena, None)","(Anthony Taylor, None)","('Match Report', '/en/matches/aa293551/Red-Bull-Salzburg-Brest-October-1-2024-Champions-League')","(, None)",https://fbref.com/en/matches/aa293551/Red-Bull-Salzburg-Brest-October-1-2024-Champions-League
20,"(League phase, /en/comps/8/Champions-League-Stats)","(2, None)","(Tue, None)","(2024-10-01, /en/matches/2024-10-01)","(20:00, None)","(Arsenal eng, /en/squads/18bb7c10/Arsenal-Stats)","(0.7, None)","(2–0, /en/matches/190f7f3f/Arsenal-Paris-Saint-Germain-October-1-2024-Champions-League)","(0.4, None)","(fr Paris S-G, /en/squads/e2d8892c/Paris-Saint-Germain-Stats)","(60,103, None)","(Emirates Stadium, None)","(Slavko Vinčič, None)","('Match Report', '/en/matches/190f7f3f/Arsenal-Paris-Saint-Germain-October-1-2024-Champions-League')","(, None)",https://fbref.com/en/matches/190f7f3f/Arsenal-Paris-Saint-Germain-October-1-2024-Champions-League
21,"(League phase, /en/comps/8/Champions-League-Stats)","(2, None)","(Tue, None)","(2024-10-01, /en/matches/2024-10-01)","(21:00, None)","(Barcelona es, /en/squads/206d90db/Barcelona-Stats)","(3.4, None)","(5–0, /en/matches/9efdd96e/Barcelona-Young-Boys-October-1-2024-Champions-League)","(0.8, None)","(ch Young Boys, /en/squads/4b682260/Young-Boys-Stats)","(45,097, None)","(Estadi Olímpic Lluís Companys, None)","(Erik Lambrechts, None)","('Match Report', '/en/matches/9efdd96e/Barcelona-Young-Boys-October-1-2024-Champions-League')","(, None)",https://fbref.com/en/matches/9efdd96e/Barcelona-Young-Boys-October-1-2024-Champions-League
22,"(League phase, /en/comps/8/Champions-League-Stats)","(2, None)","(Tue, None)","(2024-10-01, /en/matches/2024-10-01)","(21:00, None)","(Dortmund de, /en/squads/add600ae/Dortmund-Stats)","(2.6, None)","(7–1, /en/matches/925ea41c/Dortmund-Celtic-October-1-2024-Champions-League)","(2.1, None)","(sct Celtic, /en/squads/b81aa4fa/Celtic-Stats)","(81,365, None)","(Signal Iduna Park, None)","(Jose Maria Sánchez, None)","('Match Report', '/en/matches/925ea41c/Dortmund-Celtic-October-1-2024-Champions-League')","(, None)",https://fbref.com/en/matches/925ea41c/Dortmund-Celtic-October-1-2024-Champions-League
23,"(League phase, /en/comps/8/Champions-League-Stats)","(2, None)","(Tue, None)","(2024-10-01, /en/matches/2024-10-01)","(21:00, None)","(Inter it, /en/squads/d609edc0/Internazionale-Stats)","(2.8, None)","(4–0, /en/matches/19b3b47e/Internazionale-Red-Star-Belgrade-October-1-2024-Champions-League)","(0.5, None)","(rs Red Star, /en/squads/099c6eb5/Red-Star-Belgrade-Stats)","(56,391, None)","(Stadio Giuseppe Meazza, None)","(Felix Zwayer, None)","('Match Report', '/en/matches/19b3b47e/Internazionale-Red-Star-Belgrade-October-1-2024-Champions-League')","(, None)",https://fbref.com/en/matches/19b3b47e/Internazionale-Red-Star-Belgrade-October-1-2024-Champions-League
24,"(League phase, /en/comps/8/Champions-League-Stats)","(2, None)","(Tue, None)","(2024-10-01, /en/matches/2024-10-01)","(21:00, None)","(Slovan Bratislava sk, /en/squads/ae7f2f70/Slovan-Bratislava-Stats)","(0.1, None)","(0–4, /en/matches/c46d8356/Slovan-Bratislava-Manchester-City-October-1-2024-Champions-League)","(3.7, None)","(eng Manchester City, /en/squads/b8fd03ef/Manchester-City-Stats)","(22,500, None)","(Štadión Tehelné pole, None)","(Davide Massa, None)","('Match Report', '/en/matches/c46d8356/Slovan-Bratislava-Manchester-City-October-1-2024-Champions-League')","(, None)",https://fbref.com/en/matches/c46d8356/Slovan-Bratislava-Manchester-City-October-1-2024-Champions-League
25,"(League phase, /en/comps/8/Champions-League-Stats)","(2, None)","(Tue, None)","(2024-10-01, /en/matches/2024-10-01)","(21:00, None)","(PSV Eindhoven nl, /en/squads/e334d850/PSV-Eindhoven-Stats)","(2.6, None)","(1–1, /en/matches/bd985714/PSV-Eindhoven-Sporting-CP-October-1-2024-Champions-League)","(1.3, None)","(pt Sporting CP, /en/squads/13dc44fd/Sporting-CP-Stats)","(34,400, None)","(Philips Stadion, None)","(Marco Guida, None)","('Match Report', '/en/matches/bd985714/PSV-Eindhoven-Sporting-CP-October-1-2024-Champions-League')","(, None)",https://fbref.com/en/matches/bd985714/PSV-Eindhoven-Sporting-CP-October-1-2024-Champions-League
26,"(League phase, /en/comps/8/Champions-League-Stats)","(2, None)","(Tue, None)","(2024-10-01, /en/matches/2024-10-01)","(21:00, None)","(Leverkusen de, /en/squads/c7a9f859/Bayer-Leverkusen-Stats)","(1.8, None)","(1–0, /en/matches/91294a8b/Bayer-Leverkusen-Milan-October-1-2024-Champions-League)","(1.0, None)","(it Milan, /en/squads/dc56fe14/Milan-Stats)","(30,210, None)","(BayArena, None)","(Sandro Schärer, None)","('Match Report', '/en/matches/91294a8b/Bayer-Leverkusen-Milan-October-1-2024-Champions-League')","(, None)",https://fbref.com/en/matches/91294a8b/Bayer-Leverkusen-Milan-October-1-2024-Champions-League
27,"(League phase, /en/comps/8/Champions-League-Stats)","(2, None)","(Wed, None)","(2024-10-02, /en/matches/2024-10-02)","(18:45, None)","(Girona es, /en/squads/9024a00a/Girona-Stats)","(2.2, None)","(2–3, /en/matches/67eb4cdc/Girona-Feyenoord-October-2-2024-Champions-League)","(1.9, None)","(nl Feyenoord, /en/squads/fb4ca611/Feyenoord-Stats)","(8,752, None)","(Estadi Municipal de Montilivi, None)","(Urs Schnyder, None)","('Match Report', '/en/matches/67eb4cdc/Girona-Feyenoord-October-2-2024-Champions-League')","(, None)",https://fbref.com/en/matches/67eb4cdc/Girona-Feyenoord-October-2-2024-Champions-League
28,"(League phase, /en/comps/8/Champions-League-Stats)","(2, None)","(Wed, None)","(2024-10-02, /en/matches/2024-10-02)","(18:45, None)","(Shakhtar ua, /en/squads/e89d5a28/Shakhtar-Donetsk-Stats)","(0.3, None)","(0–3, /en/matches/c5e0de02/Shakhtar-Donetsk-Atalanta-October-2-2024-Champions-League)","(2.6, None)","(it Atalanta, /en/squads/922493f3/Atalanta-Stats)","(21,636, None)","(Veltins-Arena, None)","(João Pinheiro, None)","('Match Report', '/en/matches/c5e0de02/Shakhtar-Donetsk-Atalanta-October-2-2024-Champions-League')","(, None)",https://fbref.com/en/matches/c5e0de02/Shakhtar-Donetsk-Atalanta-October-2-2024-Champions-League
29,"(League phase, /en/comps/8/Champions-League-Stats)","(2, None)","(Wed, None)","(2024-10-02, /en/matches/2024-10-02)","(20:00, None)","(Liverpool eng, /en/squads/822bd0ba/Liverpool-Stats)","(1.2, None)","(2–0, /en/matches/a749c1fe/Liverpool-Bologna-October-2-2024-Champions-League)","(0.6, None)","(it Bologna, /en/squads/1d8099f8/Bologna-Stats)","(59,816, None)","(Anfield, None)","(Nikola Dabanović, None)","('Match Report', '/en/matches/a749c1fe/Liverpool-Bologna-October-2-2024-Champions-League')","(, None)",https://fbref.com/en/matches/a749c1fe/Liverpool-Bologna-October-2-2024-Champions-League
30,"(League phase, /en/comps/8/Champions-League-Stats)","(2, None)","(Wed, None)","(2024-10-02, /en/matches/2024-10-02)","(20:00, None)","(Aston Villa eng, /en/squads/8602292d/Aston-Villa-Stats)","(0.4, None)","(1–0, /en/matches/a516238d/Aston-Villa-Bayern-Munich-October-2-2024-Champions-League)","(1.5, None)","(de Bayern Munich, /en/squads/054efa67/Bayern-Munich-Stats)","(38,991, None)","(Villa Park, None)","(Radu Petrescu, None)","('Match Report', '/en/matches/a516238d/Aston-Villa-Bayern-Munich-October-2-2024-Champions-League')","(, None)",https://fbref.com/en/matches/a516238d/Aston-Villa-Bayern-Munich-October-2-2024-Champions-League

In [8]:
dfs1 = pd.read_html(url)
df1 = dfs1[0]

df1 = df1[df1['Match Report'].str.contains('Match Report', na=False)]

df1 = df1.drop(columns=['Match Report', 'Notes'])

df1 = df1[df1['Wk'] != 'Wk']

df1.reset_index(drop=True, inplace=True)

df1

,Round,Wk,Day,Date,Time,Home,xG,Score,xG.1,Away,Attendance,Venue,Referee
0,League phase,1,Tue,2024-09-17,18:45,Young Boys ch,0.6,0–3,2.0,eng Aston Villa,31500,Stadion Wankdorf,Georgi Kabakov
1,League phase,1,Tue,2024-09-17,18:45,Juventus it,2.9,3–1,1.0,nl PSV Eindhoven,40417,Allianz Stadium,Alejandro Hernández
2,League phase,1,Tue,2024-09-17,20:00,Sporting CP pt,1.6,2–0,0.4,fr Lille,40024,Estádio José Alvalade,Donatas Rumšas
3,League phase,1,Tue,2024-09-17,21:00,Real Madrid es,2.6,3–1,1.9,de Stuttgart,71288,Estadio Santiago Bernabéu,Halil Umut Meler
4,League phase,1,Tue,2024-09-17,21:00,Milan it,0.6,1–3,3.1,eng Liverpool,59826,Stadio Giuseppe Meazza,Espen Eskås
5,League phase,1,Tue,2024-09-17,21:00,Bayern Munich de,5.9,9–2,0.7,hr Dinamo Zagreb,75000,Allianz Arena,Juan Martínez
6,League phase,1,Wed,2024-09-18,18:45,Sparta Prague cz,2.5,3–0,0.6,at RB Salzburg,17612,epet Arena,Rade Obrenović
7,League phase,1,Wed,2024-09-18,18:45,Bologna it,1.2,0–0,0.9,ua Shakhtar,23130,Stadio Renato Dall'Ara,Rohit Saggi
8,League phase,1,Wed,2024-09-18,20:00,Celtic sct,3.8,5–1,0.5,sk Slovan Bratislava,56826,Celtic Park,Danny Makkelie
9,League phase,1,Wed,2024-09-18,20:00,Manchester City eng,2.3,0–0,0.7,it Inter,50922,Etihad Stadium,Glenn Nyberg
10,League phase,1,Wed,2024-09-18,21:00,Club Brugge be,1.2,0–3,1.9,de Dortmund,19961,Jan Breydelstadion,Irfan Peljto
11,League phase,1,Wed,2024-09-18,21:00,Paris S-G fr,2.1,1–0,0.2,es Girona,39951,Parc des Princes,Daniel Siebert
12,League phase,1,Thu,2024-09-19,18:45,Red Star rs,1.0,1–2,1.3,pt Benfica,44238,Stadion Rajko Mitić,Michael Oliver
13,League phase,1,Thu,2024-09-19,18:45,Feyenoord nl,0.8,0–4,1.7,de Leverkusen,42297,Stadion Feijenoord,Davide Massa
14,League phase,1,Thu,2024-09-19,21:00,Monaco fr,1.3,2–1,0.4,es Barcelona,13296,Stade Louis II,Allard Lindhout
15,League phase,1,Thu,2024-09-19,21:00,Atalanta it,1.2,0–0,0.8,eng Arsenal,22858,Gewiss Stadium,Clément Turpin
16,League phase,1,Thu,2024-09-19,21:00,Brest fr,2.1,2–1,0.5,at Sturm Graz,14518,Stade du Roudourou,Nick Walsh
17,League phase,1,Thu,2024-09-19,21:00,Atlético Madrid es,1.7,2–1,0.7,de RB Leipzig,57856,Riyadh Air Metropolitan Stadium,Ivan Kružliak
18,League phase,2,Tue,2024-10-01,18:45,Stuttgart de,1.7,1–1,1.0,cz Sparta Prague,60000,MHPArena,Manfredas Lukjančukas
19,League phase,2,Tue,2024-10-01,18:45,RB Salzburg at,1.6,0–4,2.0,fr Brest,20232,Red Bull Arena,Anthony Taylor
20,League phase,2,Tue,2024-10-01,20:00,Arsenal eng,0.7,2–0,0.4,fr Paris S-G,60103,Emirates Stadium,Slavko Vinčič
21,League phase,2,Tue,2024-10-01,21:00,Barcelona es,3.4,5–0,0.8,ch Young Boys,45097,Estadi Olímpic Lluís Companys,Erik Lambrechts
22,League phase,2,Tue,2024-10-01,21:00,Dortmund de,2.6,7–1,2.1,sct Celtic,81365,Signal Iduna Park,Jose Maria Sánchez
23,League phase,2,Tue,2024-10-01,21:00,Inter it,2.8,4–0,0.5,rs Red Star,56391,Stadio Giuseppe Meazza,Felix Zwayer
24,League phase,2,Tue,2024-10-01,21:00,Slovan Bratislava sk,0.1,0–4,3.7,eng Manchester City,22500,Štadión Tehelné pole,Davide Massa
25,League phase,2,Tue,2024-10-01,21:00,PSV Eindhoven nl,2.6,1–1,1.3,pt Sporting CP,34400,Philips Stadion,Marco Guida
26,League phase,2,Tue,2024-10-01,21:00,Leverkusen de,1.8,1–0,1.0,it Milan,30210,BayArena,Sandro Schärer
27,League phase,2,Wed,2024-10-02,18:45,Girona es,2.2,2–3,1.9,nl Feyenoord,8752,Estadi Municipal de Montilivi,Urs Schnyder
28,League phase,2,Wed,2024-10-02,18:45,Shakhtar ua,0.3,0–3,2.6,it Atalanta,21636,Veltins-Arena,João Pinheiro
29,League phase,2,Wed,2024-10-02,20:00,Liverpool eng,1.2,2–0,0.6,it Bologna,59816,Anfield,Nikola Dabanović
30,League phase,2,Wed,2024-10-02,20:00,Aston Villa eng,0.4,1–0,1.5,de Bayern Munich,38991,Villa Park,Radu Petrescu
31,League phase,2,Wed,2024-10-02,20:00,Benfica pt,4.4,4–0,0.2,es Atlético Madrid,62028,Estádio do Sport Lisboa e Benfica,Serdar Gözübüyük
32,League phase,2,Wed,2024-10-02,21:00,Dinamo Zagreb hr,1.0,2–2,1.9,fr Monaco,12462,Stadion Maksimir,Harm Osmers
33,League phase,2,Wed,2024-10-02,21:00,RB Leipzig de,3.3,2–3,1.2,it Juventus,45228,Red Bull Arena,François Letexier
34,League phase,2,Wed,2024-10-02,21:00,Sturm Graz at,0.4,0–1,0.7,be Club Brugge,23205,Merkur Arena,Əliyar Ağayev
35,League phase,2,Wed,2024-10-02,21:00,Lille fr,1.1,1–0,2.0,es Real Madrid,48205,Decathlon Arena - Stade Pierre-Mauroy,Maurizio Mariani
36,League phase,3,Tue,2024-10-22,18:45,Monaco fr,3.3,5–1,1.0,rs Red Star,9590,Stade Louis II,Tobias Stieler
37,League phase,3,Tue,2024-10-22,18:45,Milan it,1.2,3–1,0.6,be Club Brugge,58649,Stadio Giuseppe Meazza,Felix Zwayer
38,League phase,3,Tue,2024-10-22,20:00,Arsenal eng,1.8,1–0,0.7,ua Shakhtar,59594,Emirates Stadium,Benoît Bastien
39,League phase,3,Tue,2024-10-22,20:00,Aston Villa eng,1.2,2–0,0.9,it Bologna,41847,Villa Park,João Pinheiro
40,League phase,3,Tue,2024-10-22,21:00,Sturm Graz at,0.7,0–2,1.4,pt Sporting CP,23691,Merkur Arena,Giorgi Kruashvili
41,League phase,3,Tue,2024-10-22,21:00,Juventus it,0.2,0–1,2.5,de Stuttgart,41306,Allianz Stadium,Espen Eskås
42,League phase,3,Tue,2024-10-22,21:00,Real Madrid es,3.5,5–2,1.6,de Dortmund,74642,Estadio Santiago Bernabéu,István Kovács
43,League phase,3,Tue,2024-10-22,21:00,Girona es,1.7,2–0,0.5,sk Slovan Bratislava,9246,Estadi Municipal de Montilivi,Horațiu Fesnic
44,League phase,3,Tue,2024-10-22,21:00,Paris S-G fr,2.5,1–1,0.2,nl PSV Eindhoven,47511,Parc des Princes,Glenn Nyberg
45,League phase,3,Wed,2024-10-23,18:45,Brest fr,0.5,1–1,1.0,de Leverkusen,15510,Stade du Roudourou,Ivan Kružliak
46,League phase,3,Wed,2024-10-23,18:45,Atalanta it,2.4,0–0,0.3,sct Celtic,21614,Gewiss Stadium,Irfan Peljto
47,League phase,3,Wed,2024-10-23,20:00,Benfica pt,1.7,1–3,1.0,nl Feyenoord,61687,Estádio do Sport Lisboa e Benfica,Halil Umut Meler
48,League phase,3,Wed,2024-10-23,20:00,Manchester City eng,2.9,5–0,0.2,cz Sparta Prague,50116,Etihad Stadium,Maurizio Mariani
49,League phase,3,Wed,2024-10-23,21:00,RB Salzburg at,1.2,0–2,1.6,hr Dinamo Zagreb,24018,Red Bull Arena,Danny Makkelie
50,League phase,3,Wed,2024-10-23,21:00,Young Boys ch,0.8,0–1,3.3,it Inter,31500,Stadion Wankdorf,Michael Oliver
51,League phase,3,Wed,2024-10-23,21:00,Barcelona es,2.2,4–1,1.0,de Bayern Munich,50312,Estadi Olímpic Lluís Companys,Slavko Vinčič
52,League phase,3,Wed,2024-10-23,21:00,Atlético Madrid es,2.3,1–3,1.3,fr Lille,61197,Riyadh Air Metropolitan Stadium,Marco Guida
53,League phase,3,Wed,2024-10-23,21:00,RB Leipzig de,0.8,0–1,2.3,eng Liverpool,45228,Red Bull Arena,Sandro Schärer
54,League phase,4,Tue,2024-11-05,18:45,Slovan Bratislava sk,1.7,1–4,1.5,hr Dinamo Zagreb,22132,Štadión Tehelné pole,Anthony Taylor
55,League phase,4,Tue,2024-11-05,18:45,PSV Eindhoven nl,2.0,4–0,0.8,es Girona,34400,Philips Stadion,Michael Oliver
56,League phase,4,Tue,2024-11-05,20:00,Sporting CP pt,2.9,4–1,2.1,eng Manchester City,47453,Estádio José Alvalade,Daniel Siebert
57,League phase,4,Tue,2024-11-05,20:00,Liverpool eng,3.7,4–0,0.9,de Leverkusen,59790,Anfield,Danny Makkelie
58,League phase,4,Tue,2024-11-05,20:00,Celtic sct,1.8,3–1,1.3,de RB Leipzig,57551,Celtic Park,Benoît Bastien
59,League phase,4,Tue,2024-11-05,21:00,Bologna it,0.5,0–1,0.9,fr Monaco,23084,Stadio Renato Dall'Ara,Əliyar Ağayev
60,League phase,4,Tue,2024-11-05,21:00,Real Madrid es,2.6,1–3,2.5,it Milan,75561,Estadio Santiago Bernabéu,Slavko Vinčič
61,League phase,4,Tue,2024-11-05,21:00,Lille fr,0.8,1–1,1.4,it Juventus,48312,Decathlon Arena - Stade Pierre-Mauroy,Irfan Peljto
62,League phase,4,Tue,2024-11-05,21:00,Dortmund de,2.0,1–0,0.4,at Sturm Graz,81365,Signal Iduna Park,Erik Lambrechts
63,League phase,4,Wed,2024-11-06,18:45,Club Brugge be,1.4,1–0,0.4,eng Aston Villa,23466,Jan Breydelstadion,Tobias Stieler
64,League phase,4,Wed,2024-11-06,19:45,Shakhtar ua,2.0,2–1,1.0,ch Young Boys,17420,Veltins-Arena,Orel Grinfeeld
65,League phase,4,Wed,2024-11-06,21:00,Paris S-G fr,2.1,1–2,0.7,es Atlético Madrid,47369,Parc des Princes,Szymon Marciniak
66,League phase,4,Wed,2024-11-06,21:00,Bayern Munich de,1.4,1–0,0.1,pt Benfica,75000,Allianz Arena,Davide Massa
67,League phase,4,Wed,2024-11-06,21:00,Red Star rs,0.2,2–5,3.6,es Barcelona,48886,Stadion Rajko Mitić,Espen Eskås
68,League phase,4,Wed,2024-11-06,21:00,Sparta Prague cz,0.5,1–2,1.6,fr Brest,18033,epet Arena,Mykola Balakin
69,League phase,4,Wed,2024-11-06,21:00,Feyenoord nl,0.8,1–3,1.7,at RB Salzburg,42774,Stadion Feijenoord,Donatas Rumšas
70,League phase,4,Wed,2024-11-06,21:00,Stuttgart de,1.0,0–2,2.3,it Atalanta,60000,MHPArena,Rade Obrenović
71,League phase,4,Wed,2024-11-06,21:00,Inter it,1.1,1–0,1.8,eng Arsenal,75222,Stadio Giuseppe Meazza,István Kovács
72,League phase,5,Tue,2024-11-26,18:45,Slovan Bratislava sk,1.5,2–3,1.9,it Milan,22500,Štadión Tehelné pole,Jose Maria Sánchez
73,League phase,5,Tue,2024-11-26,18:45,Sparta Prague cz,0.2,0–6,3.1,es Atlético Madrid,18110,epet Arena,Danny Makkelie
74,League phase,5,Tue,2024-11-26,20:00,Manchester City eng,2.1,3–3,2.2,nl Feyenoord,47011,Etihad Stadium,Radu Petrescu
75,League phase,5,Tue,2024-11-26,20:00,Sporting CP pt,1.0,1–5,4.0,eng Arsenal,47386,Estádio José Alvalade,Szymon Marciniak
76,League phase,5,Tue,2024-11-26,21:00,Barcelona es,2.8,3–0,0.1,fr Brest,46317,Estadi Olímpic Lluís Companys,Irfan Peljto
77,League phase,5,Tue,2024-11-26,21:00,Leverkusen de,4.3,5–0,0.3,at RB Salzburg,29211,BayArena,Mykola Balakin
78,League phase,5,Tue,2024-11-26,21:00,Inter it,1.4,1–0,0.1,de RB Leipzig,63174,Stadio Giuseppe Meazza,João Pinheiro
79,League phase,5,Tue,2024-11-26,21:00,Bayern Munich de,2.4,1–0,0.8,fr Paris S-G,75000,Allianz Arena,István Kovács
80,League phase,5,Tue,2024-11-26,21:00,Young Boys ch,0.8,1–6,2.5,it Atalanta,31500,Stadion Wankdorf,Manfredas Lukjančukas
81,League phase,5,Wed,2024-11-27,18:45,Red Star rs,1.8,5–1,0.6,de Stuttgart,41372,Stadion Rajko Mitić,Erik Lambrechts
82,League phase,5,Wed,2024-11-27,18:45,Sturm Graz at,0.8,1–0,1.7,es Girona,21502,Merkur Arena,Rohit Saggi
83,League phase,5,Wed,2024-11-27,20:00,Aston Villa eng,1.2,0–0,0.4,it Juventus,42589,Villa Park,Jesús Gil
84,League phase,5,Wed,2024-11-27,20:00,Liverpool eng,2.7,2–0,1.2,es Real Madrid,59546,Anfield,François Letexier
85,League phase,5,Wed,2024-11-27,20:00,Celtic sct,1.0,1–1,1.1,be Club Brugge,57456,Celtic Park,Georgi Kabakov
86,League phase,5,Wed,2024-11-27,21:00,PSV Eindhoven nl,2.6,3–2,1.0,ua Shakhtar,35100,Philips Stadion,Urs Schnyder
87,League phase,5,Wed,2024-11-27,21:00,Bologna it,1.7,1–2,2.1,fr Lille,22420,Stadio Renato Dall'Ara,Michael Oliver
88,League phase,5,Wed,2024-11-27,21:00,Dinamo Zagreb hr,0.2,0–3,1.7,de Dortmund,20019,Stadion Maksimir,Clément Turpin
89,League phase,5,Wed,2024-11-27,21:00,Monaco fr,1.6,2–3,3.0,pt Benfica,13581,Stade Louis II,Rade Obrenović
90,League phase,6,Tue,2024-12-10,18:45,Dinamo Zagreb hr,0.5,0–0,0.4,sct Celtic,18158,Stadion Maksimir,Felix Zwayer
91,League phase,6,Tue,2024-12-10,18:45,Girona es,1.2,0–1,1.8,eng Liverpool,9241,Estadi Municipal de Montilivi,Benoît Bastien
92,League phase,6,Tue,2024-12-10,21:00,Leverkusen de,1.1,1–0,0.3,it Inter,30210,BayArena,Slavko Vinčič
93,League phase,6,Tue,2024-12-10,21:00,Brest fr,1.6,1–0,1.6,nl PSV Eindhoven,15778,Stade du Roudourou,Jose Maria Sánchez
94,League phase,6,Tue,2024-12-10,21:00,Club Brugge be,1.0,2–1,1.2,pt Sporting CP,22254,Jan Breydelstadion,Anthony Taylor
95,League phase,6,Tue,2024-12-10,21:00,RB Salzburg at,0.2,0–3,3.2,fr Paris S-G,25065,Red Bull Arena,Michael Oliver
96,League phase,6,Tue,2024-12-10,21:00,RB Leipzig de,2.2,2–3,2.1,eng Aston Villa,40406,Red Bull Arena,Maurizio Mariani
97,League phase,6,Tue,2024-12-10,21:00,Atalanta it,3.3,2–3,2.1,es Real Madrid,22967,Gewiss Stadium,Szymon Marciniak
98,League phase,6,Tue,2024-12-10,22:00,Shakhtar ua,1.2,1–5,3.6,de Bayern Munich,57079,Veltins-Arena,Halil Umut Meler
99,League phase,6,Wed,2024-12-11,18:45,Lille fr,2.0,3–2,1.3,at Sturm Graz,45796,Decathlon Arena - Stade Pierre-Mauroy,Georgi Kabakov
100,League phase,6,Wed,2024-12-11,18:45,Atlético Madrid es,2.0,3–1,1.0,sk Slovan Bratislava,59134,Riyadh Air Metropolitan Stadium,Manfredas Lukjančukas
101,League phase,6,Wed,2024-12-11,20:00,Arsenal eng,2.3,3–0,0.5,fr Monaco,60157,Emirates Stadium,Davide Massa
102,League phase,6,Wed,2024-12-11,20:00,Benfica pt,1.3,0–0,0.2,it Bologna,60650,Estádio do Sport Lisboa e Benfica,Radu Petrescu
103,League phase,6,Wed,2024-12-11,21:00,Milan it,2.0,2–1,0.4,rs Red Star,53717,Stadio Giuseppe Meazza,Jesús Gil
104,League phase,6,Wed,2024-12-11,21:00,Juventus it,1.1,2–0,1.2,eng Manchester City,40890,Allianz Stadium,Clément Turpin
105,League phase,6,Wed,2024-12-11,21:00,Stuttgart de,2.3,5–1,0.2,ch Young Boys,60000,MHPArena,Giorgi Kruashvili
106,League phase,6,Wed,2024-12-11,21:00,Dortmund de,2.7,2–3,2.0,es Barcelona,81365,Signal Iduna Park,François Letexier
107,League phase,6,Wed,2024-12-11,21:00,Feyenoord nl,1.0,4–2,0.7,cz Sparta Prague,45000,Stadion Feijenoord,Tobias Stieler
108,League phase,7,Tue,2025-01-21,18:45,Atalanta it,4.9,5–0,0.8,at Sturm Graz,19469,Gewiss Stadium,Donatas Rumšas
109,League phase,7,Tue,2025-01-21,18:45,Monaco fr,1.5,1–0,0.9,eng Aston Villa,13508,Stade Louis II,Slavko Vinčič
110,League phase,7,Tue,2025-01-21,20:00,Liverpool eng,2.5,2–1,0.5,fr Lille,59782,Anfield,Felix Zwayer
111,League phase,7,Tue,2025-01-21,20:00,Benfica pt,3.3,4–5,3.6,es Barcelona,63225,Estádio do Sport Lisboa e Benfica,Danny Makkelie
112,League phase,7,Tue,2025-01-21,21:00,Bologna it,2.1,2–1,1.0,de Dortmund,26801,Stadio Renato Dall'Ara,Serdar Gözübüyük
113,League phase,7,Tue,2025-01-21,21:00,Club Brugge be,0.7,0–0,0.4,it Juventus,26700,Jan Breydelstadion,Benoît Bastien
114,League phase,7,Tue,2025-01-21,21:00,Red Star rs,2.6,2–3,0.8,nl PSV Eindhoven,36648,Stadion Rajko Mitić,István Kovács
115,League phase,7,Tue,2025-01-21,21:00,Slovan Bratislava sk,0.6,1–3,3.4,de Stuttgart,22500,Štadión Tehelné pole,Chris Kavanagh
116,League phase,7,Tue,2025-01-21,21:00,Atlético Madrid es,0.8,2–1,0.8,de Leverkusen,66820,Riyadh Air Metropolitan Stadium,Davide Massa
117,League phase,7,Wed,2025-01-22,18:45,RB Leipzig de,2.3,2–1,0.9,pt Sporting CP,33478,Red Bull Arena,Manfredas Lukjančukas
118,League phase,7,Wed,2025-01-22,19:45,Shakhtar ua,1.9,2–0,0.4,fr Brest,15282,Veltins-Arena,Sandro Schärer
119,League phase,7,Wed,2025-01-22,20:00,Arsenal eng,2.4,3–0,0.1,hr Dinamo Zagreb,60024,Emirates Stadium,Daniel Siebert
120,League phase,7,Wed,2025-01-22,20:00,Celtic sct,1.8,1–0,1.0,ch Young Boys,56544,Celtic Park,Rohit Saggi
121,League phase,7,Wed,2025-01-22,21:00,Real Madrid es,2.8,5–1,0.4,at RB Salzburg,73692,Estadio Santiago Bernabéu,Glenn Nyberg
122,League phase,7,Wed,2025-01-22,21:00,Milan it,1.3,1–0,1.0,es Girona,66030,Stadio Giuseppe Meazza,Tobias Stieler
123,League phase,7,Wed,2025-01-22,21:00,Paris S-G fr,2.8,4–2,1.7,eng Manchester City,47818,Parc des Princes,Szymon Marciniak
124,League phase,7,Wed,2025-01-22,21:00,Sparta Prague cz,0.4,0–1,0.9,it Inter,18010,epet Arena,Alejandro Hernández
125,League phase,7,Wed,2025-01-22,21:00,Feyenoord nl,1.7,3–0,2.4,de Bayern Munich,43106,Stadion Feijenoord,François Letexier
126,League phase,8,Wed,2025-01-29,20:00,Manchester City eng,2.0,3–1,1.1,be Club Brugge,51237,Etihad Stadium,Jose Maria Sánchez
127,League phase,8,Wed,2025-01-29,20:00,Aston Villa eng,3.9,4–2,0.8,sct Celtic,42824,Villa Park,Clément Turpin
128,League phase,8,Wed,2025-01-29,20:00,Sporting CP pt,1.3,1–1,1.1,it Bologna,37328,Estádio José Alvalade,Benoît Bastien
129,League phase,8,Wed,2025-01-29,21:00,Bayern Munich de,3.7,3–1,0.9,sk Slovan Bratislava,75000,Allianz Arena,João Pinheiro
130,League phase,8,Wed,2025-01-29,21:00,Juventus it,0.9,0–2,2.2,pt Benfica,41402,Allianz Stadium,István Kovács
131,League phase,8,Wed,2025-01-29,21:00,Barcelona es,2.4,2–2,1.2,it Atalanta,42728,Estadi Olímpic Lluís Companys,Michael Oliver
132,League phase,8,Wed,2025-01-29,21:00,Dortmund de,2.4,3–1,0.4,ua Shakhtar,81365,Signal Iduna Park,Glenn Nyberg
133,League phase,8,Wed,2025-01-29,21:00,Brest fr,1.4,0–3,2.6,es Real Madrid,15405,Stade du Roudourou,Espen Eskås
134,League phase,8,Wed,2025-01-29,21:00,PSV Eindhoven nl,1.3,3–2,1.6,eng Liverpool,35000,Philips Stadion,Tobias Stieler
135,League phase,8,Wed,2025-01-29,21:00,Inter it,3.9,3–0,0.2,fr Monaco,71601,Stadio Giuseppe Meazza,Irfan Peljto
136,League phase,8,Wed,2025-01-29,21:00,Leverkusen de,1.7,2–0,0.7,cz Sparta Prague,30210,BayArena,Georgi Kabakov
137,League phase,8,Wed,2025-01-29,21:00,Stuttgart de,0.8,1–4,2.4,fr Paris S-G,60000,MHPArena,Davide Massa
138,League phase,8,Wed,2025-01-29,21:00,Lille fr,1.3,6–1,0.7,nl Feyenoord,44071,Decathlon Arena - Stade Pierre-Mauroy,Slavko Vinčič
139,League phase,8,Wed,2025-01-29,21:00,Sturm Graz at,1.3,1–0,1.5,de RB Leipzig,26851,28 Black Arena,Mykola Balakin
140,League phase,8,Wed,2025-01-29,21:00,Young Boys ch,0.4,0–1,1.8,rs Red Star,31500,Stadion Wankdorf,Halil Umut Meler
141,League phase,8,Wed,2025-01-29,21:00,Girona es,0.7,1–2,2.1,eng Arsenal,9048,Estadi Municipal de Montilivi,Maurizio Mariani
142,League phase,8,Wed,2025-01-29,21:00,Dinamo Zagreb hr,1.4,2–1,1.1,it Milan,18856,Stadion Maksimir,François Letexier
143,League phase,8,Wed,2025-01-29,21:00,RB Salzburg at,0.6,1–4,2.1,es Atlético Madrid,23389,Red Bull Arena,Anthony Taylor
144,Knockout phase play-offs,NaN,Tue,2025-02-11,18:45,Brest fr,0.9,0–3,2.6,fr Paris S-G,15831,Stade du Roudourou,Irfan Peljto
145,Knockout phase play-offs,NaN,Tue,2025-02-11,20:00,Manchester City eng,1.5,2–3,3.2,es Real Madrid,52081,Etihad Stadium,Clément Turpin
146,Knockout phase play-offs,NaN,Tue,2025-02-11,20:00,Sporting CP pt,0.7,0–3,1.8,de Dortmund,41543,Estádio José Alvalade,Espen Eskås
147,Knockout phase play-offs,NaN,Tue,2025-02-11,21:00,Juventus it,1.4,2–1,0.8,nl PSV Eindhoven,39886,Allianz Stadium,Daniel Siebert
148,Knockout phase play-offs,NaN,Wed,2025-02-12,18:45,Club Brugge be,1.4,2–1,1.0,it Atalanta,24242,Jan Breydelstadion,Halil Umut Meler
149,Knockout phase play-offs,NaN,Wed,2025-02-12,20:00,Celtic sct,1.3,1–2,0.7,de Bayern Munich,57406,Celtic Park,Jesús Gil
150,Knockout phase play-offs,NaN,Wed,2025-02-12,21:00,Monaco fr,0.4,0–1,2.1,pt Benfica,12159,Stade Louis II,Maurizio Mariani
151,Knockout phase play-offs,NaN,Wed,2025-02-12,21:00,Feyenoord nl,0.5,1–0,0.6,it Milan,45000,Stadion Feijenoord,Jose Maria Sánchez
152,Knockout phase play-offs,NaN,Tue,2025-02-18,18:45,Milan it,1.7,1–1,0.9,nl Feyenoord,54749,Stadio Giuseppe Meazza,Szymon Marciniak
153,Knockout phase play-offs,NaN,Tue,2025-02-18,20:00,Benfica pt,1.9,3–3,1.5,fr Monaco,60776,Estádio do Sport Lisboa e Benfica,Glenn Nyberg
154,Knockout phase play-offs,NaN,Tue,2025-02-18,21:00,Atalanta it,3.1,1–3,1.1,be Club Brugge,21727,Gewiss Stadium,Felix Zwayer
155,Knockout phase play-offs,NaN,Tue,2025-02-18,21:00,Bayern Munich de,2.3,1–1,1.3,sct Celtic,75000,Allianz Arena,Benoît Bastien
156,Knockout phase play-offs,NaN,Wed,2025-02-19,18:45,Dortmund de,1.9,0–0,0.4,pt Sporting CP,80300,Signal Iduna Park,Davide Massa
157,Knockout phase play-offs,NaN,Wed,2025-02-19,21:00,Real Madrid es,1.8,3–1,1.3,eng Manchester City,77023,Estadio Santiago Bernabéu,István Kovács
158,Knockout phase play-offs,NaN,Wed,2025-02-19,21:00,PSV Eindhoven nl,3.4,3–1,1.7,it Juventus,35000,Philips Stadion,Slavko Vinčič
159,Knockout phase play-offs,NaN,Wed,2025-02-19,21:00,Paris S-G fr,3.2,7–0,0.9,fr Brest,47211,Parc des Princes,Michael Oliver
160,Round of 16,NaN,Tue,2025-03-04,18:45,Club Brugge be,1.1,1–3,1.4,eng Aston Villa,26890,Jan Breydelstadion,João Pinheiro
161,Round of 16,NaN,Tue,2025-03-04,21:00,PSV Eindhoven nl,1.4,1–7,1.9,eng Arsenal,34400,Philips Stadion,Jesús Gil
162,Round of 16,NaN,Tue,2025-03-04,21:00,Real Madrid es,0.7,2–1,0.2,es Atlético Madrid,77261,Estadio Santiago Bernabéu,Clément Turpin
163,Round of 16,NaN,Tue,2025-03-04,21:00,Dortmund de,0.3,1–1,0.9,fr Lille,81365,Signal Iduna Park,Jose Maria Sánchez
164,Round of 16,NaN,Wed,2025-03-05,18:45,Feyenoord nl,0.4,0–2,2.2,it Inter,43789,Stadion Feijenoord,Espen Eskås
165,Round of 16,NaN,Wed,2025-03-05,20:00,Benfica pt,1.7,0–1,1.2,es Barcelona,62437,Estádio do Sport Lisboa e Benfica,Felix Zwayer

In [9]:
df2 = pd.merge(df1, df[['URL']], left_index=True, right_index=True, how='left')
df2

,Round,Wk,Day,Date,Time,Home,xG,Score,xG.1,Away,Attendance,Venue,Referee,URL
0,League phase,1,Tue,2024-09-17,18:45,Young Boys ch,0.6,0–3,2.0,eng Aston Villa,31500,Stadion Wankdorf,Georgi Kabakov,https://fbref.com/en/matches/568274fc/Young-Boys-Aston-Villa-September-17-2024-Champions-League
1,League phase,1,Tue,2024-09-17,18:45,Juventus it,2.9,3–1,1.0,nl PSV Eindhoven,40417,Allianz Stadium,Alejandro Hernández,https://fbref.com/en/matches/931cd5fb/Juventus-PSV-Eindhoven-September-17-2024-Champions-League
2,League phase,1,Tue,2024-09-17,20:00,Sporting CP pt,1.6,2–0,0.4,fr Lille,40024,Estádio José Alvalade,Donatas Rumšas,https://fbref.com/en/matches/aaca158d/Sporting-CP-Lille-September-17-2024-Champions-League
3,League phase,1,Tue,2024-09-17,21:00,Real Madrid es,2.6,3–1,1.9,de Stuttgart,71288,Estadio Santiago Bernabéu,Halil Umut Meler,https://fbref.com/en/matches/4fb5fcbd/Real-Madrid-Stuttgart-September-17-2024-Champions-League
4,League phase,1,Tue,2024-09-17,21:00,Milan it,0.6,1–3,3.1,eng Liverpool,59826,Stadio Giuseppe Meazza,Espen Eskås,https://fbref.com/en/matches/54ed5557/Milan-Liverpool-September-17-2024-Champions-League
5,League phase,1,Tue,2024-09-17,21:00,Bayern Munich de,5.9,9–2,0.7,hr Dinamo Zagreb,75000,Allianz Arena,Juan Martínez,https://fbref.com/en/matches/7c5c2955/Bayern-Munich-Dinamo-Zagreb-September-17-2024-Champions-League
6,League phase,1,Wed,2024-09-18,18:45,Sparta Prague cz,2.5,3–0,0.6,at RB Salzburg,17612,epet Arena,Rade Obrenović,https://fbref.com/en/matches/936f3ee0/Sparta-Prague-Red-Bull-Salzburg-September-18-2024-Champions-League
7,League phase,1,Wed,2024-09-18,18:45,Bologna it,1.2,0–0,0.9,ua Shakhtar,23130,Stadio Renato Dall'Ara,Rohit Saggi,https://fbref.com/en/matches/85075de5/Bologna-Shakhtar-Donetsk-September-18-2024-Champions-League
8,League phase,1,Wed,2024-09-18,20:00,Celtic sct,3.8,5–1,0.5,sk Slovan Bratislava,56826,Celtic Park,Danny Makkelie,https://fbref.com/en/matches/16af036c/Celtic-Slovan-Bratislava-September-18-2024-Champions-League
9,League phase,1,Wed,2024-09-18,20:00,Manchester City eng,2.3,0–0,0.7,it Inter,50922,Etihad Stadium,Glenn Nyberg,https://fbref.com/en/matches/db400f4b/Manchester-City-Internazionale-September-18-2024-Champions-League
10,League phase,1,Wed,2024-09-18,21:00,Club Brugge be,1.2,0–3,1.9,de Dortmund,19961,Jan Breydelstadion,Irfan Peljto,https://fbref.com/en/matches/722df76c/Club-Brugge-Dortmund-September-18-2024-Champions-League
11,League phase,1,Wed,2024-09-18,21:00,Paris S-G fr,2.1,1–0,0.2,es Girona,39951,Parc des Princes,Daniel Siebert,https://fbref.com/en/matches/53cfba8e/Paris-Saint-Germain-Girona-September-18-2024-Champions-League
12,League phase,1,Thu,2024-09-19,18:45,Red Star rs,1.0,1–2,1.3,pt Benfica,44238,Stadion Rajko Mitić,Michael Oliver,https://fbref.com/en/matches/2d931c93/Red-Star-Belgrade-Benfica-September-19-2024-Champions-League
13,League phase,1,Thu,2024-09-19,18:45,Feyenoord nl,0.8,0–4,1.7,de Leverkusen,42297,Stadion Feijenoord,Davide Massa,https://fbref.com/en/matches/24c1d39c/Feyenoord-Bayer-Leverkusen-September-19-2024-Champions-League
14,League phase,1,Thu,2024-09-19,21:00,Monaco fr,1.3,2–1,0.4,es Barcelona,13296,Stade Louis II,Allard Lindhout,https://fbref.com/en/matches/745d19c2/Monaco-Barcelona-September-19-2024-Champions-League
15,League phase,1,Thu,2024-09-19,21:00,Atalanta it,1.2,0–0,0.8,eng Arsenal,22858,Gewiss Stadium,Clément Turpin,https://fbref.com/en/matches/108b9e41/Atalanta-Arsenal-September-19-2024-Champions-League
16,League phase,1,Thu,2024-09-19,21:00,Brest fr,2.1,2–1,0.5,at Sturm Graz,14518,Stade du Roudourou,Nick Walsh,https://fbref.com/en/matches/162f5233/Brest-Sturm-Graz-September-19-2024-Champions-League
17,League phase,1,Thu,2024-09-19,21:00,Atlético Madrid es,1.7,2–1,0.7,de RB Leipzig,57856,Riyadh Air Metropolitan Stadium,Ivan Kružliak,https://fbref.com/en/matches/a112dcca/Atletico-Madrid-RB-Leipzig-September-19-2024-Champions-League
18,League phase,2,Tue,2024-10-01,18:45,Stuttgart de,1.7,1–1,1.0,cz Sparta Prague,60000,MHPArena,Manfredas Lukjančukas,https://fbref.com/en/matches/80c7f5c5/Stuttgart-Sparta-Prague-October-1-2024-Champions-League
19,League phase,2,Tue,2024-10-01,18:45,RB Salzburg at,1.6,0–4,2.0,fr Brest,20232,Red Bull Arena,Anthony Taylor,https://fbref.com/en/matches/aa293551/Red-Bull-Salzburg-Brest-October-1-2024-Champions-League
20,League phase,2,Tue,2024-10-01,20:00,Arsenal eng,0.7,2–0,0.4,fr Paris S-G,60103,Emirates Stadium,Slavko Vinčič,https://fbref.com/en/matches/190f7f3f/Arsenal-Paris-Saint-Germain-October-1-2024-Champions-League
21,League phase,2,Tue,2024-10-01,21:00,Barcelona es,3.4,5–0,0.8,ch Young Boys,45097,Estadi Olímpic Lluís Companys,Erik Lambrechts,https://fbref.com/en/matches/9efdd96e/Barcelona-Young-Boys-October-1-2024-Champions-League
22,League phase,2,Tue,2024-10-01,21:00,Dortmund de,2.6,7–1,2.1,sct Celtic,81365,Signal Iduna Park,Jose Maria Sánchez,https://fbref.com/en/matches/925ea41c/Dortmund-Celtic-October-1-2024-Champions-League
23,League phase,2,Tue,2024-10-01,21:00,Inter it,2.8,4–0,0.5,rs Red Star,56391,Stadio Giuseppe Meazza,Felix Zwayer,https://fbref.com/en/matches/19b3b47e/Internazionale-Red-Star-Belgrade-October-1-2024-Champions-League
24,League phase,2,Tue,2024-10-01,21:00,Slovan Bratislava sk,0.1,0–4,3.7,eng Manchester City,22500,Štadión Tehelné pole,Davide Massa,https://fbref.com/en/matches/c46d8356/Slovan-Bratislava-Manchester-City-October-1-2024-Champions-League
25,League phase,2,Tue,2024-10-01,21:00,PSV Eindhoven nl,2.6,1–1,1.3,pt Sporting CP,34400,Philips Stadion,Marco Guida,https://fbref.com/en/matches/bd985714/PSV-Eindhoven-Sporting-CP-October-1-2024-Champions-League
26,League phase,2,Tue,2024-10-01,21:00,Leverkusen de,1.8,1–0,1.0,it Milan,30210,BayArena,Sandro Schärer,https://fbref.com/en/matches/91294a8b/Bayer-Leverkusen-Milan-October-1-2024-Champions-League
27,League phase,2,Wed,2024-10-02,18:45,Girona es,2.2,2–3,1.9,nl Feyenoord,8752,Estadi Municipal de Montilivi,Urs Schnyder,https://fbref.com/en/matches/67eb4cdc/Girona-Feyenoord-October-2-2024-Champions-League
28,League phase,2,Wed,2024-10-02,18:45,Shakhtar ua,0.3,0–3,2.6,it Atalanta,21636,Veltins-Arena,João Pinheiro,https://fbref.com/en/matches/c5e0de02/Shakhtar-Donetsk-Atalanta-October-2-2024-Champions-League
29,League phase,2,Wed,2024-10-02,20:00,Liverpool eng,1.2,2–0,0.6,it Bologna,59816,Anfield,Nikola Dabanović,https://fbref.com/en/matches/a749c1fe/Liverpool-Bologna-October-2-2024-Champions-League
30,League phase,2,Wed,2024-10-02,20:00,Aston Villa eng,0.4,1–0,1.5,de Bayern Munich,38991,Villa Park,Radu Petrescu,https://fbref.com/en/matches/a516238d/Aston-Villa-Bayern-Munich-October-2-2024-Champions-League
31,League phase,2,Wed,2024-10-02,20:00,Benfica pt,4.4,4–0,0.2,es Atlético Madrid,62028,Estádio do Sport Lisboa e Benfica,Serdar Gözübüyük,https://fbref.com/en/matches/e5e2d3a2/Benfica-Atletico-Madrid-October-2-2024-Champions-League
32,League phase,2,Wed,2024-10-02,21:00,Dinamo Zagreb hr,1.0,2–2,1.9,fr Monaco,12462,Stadion Maksimir,Harm Osmers,https://fbref.com/en/matches/facef700/Dinamo-Zagreb-Monaco-October-2-2024-Champions-League
33,League phase,2,Wed,2024-10-02,21:00,RB Leipzig de,3.3,2–3,1.2,it Juventus,45228,Red Bull Arena,François Letexier,https://fbref.com/en/matches/2e8465b9/RB-Leipzig-Juventus-October-2-2024-Champions-League
34,League phase,2,Wed,2024-10-02,21:00,Sturm Graz at,0.4,0–1,0.7,be Club Brugge,23205,Merkur Arena,Əliyar Ağayev,https://fbref.com/en/matches/f871e405/Sturm-Graz-Club-Brugge-October-2-2024-Champions-League
35,League phase,2,Wed,2024-10-02,21:00,Lille fr,1.1,1–0,2.0,es Real Madrid,48205,Decathlon Arena - Stade Pierre-Mauroy,Maurizio Mariani,https://fbref.com/en/matches/70cd3947/Lille-Real-Madrid-October-2-2024-Champions-League
36,League phase,3,Tue,2024-10-22,18:45,Monaco fr,3.3,5–1,1.0,rs Red Star,9590,Stade Louis II,Tobias Stieler,https://fbref.com/en/matches/8450b165/Monaco-Red-Star-Belgrade-October-22-2024-Champions-League
37,League phase,3,Tue,2024-10-22,18:45,Milan it,1.2,3–1,0.6,be Club Brugge,58649,Stadio Giuseppe Meazza,Felix Zwayer,https://fbref.com/en/matches/e11229bf/Milan-Club-Brugge-October-22-2024-Champions-League
38,League phase,3,Tue,2024-10-22,20:00,Arsenal eng,1.8,1–0,0.7,ua Shakhtar,59594,Emirates Stadium,Benoît Bastien,https://fbref.com/en/matches/32f2220e/Arsenal-Shakhtar-Donetsk-October-22-2024-Champions-League
39,League phase,3,Tue,2024-10-22,20:00,Aston Villa eng,1.2,2–0,0.9,it Bologna,41847,Villa Park,João Pinheiro,https://fbref.com/en/matches/e546b256/Aston-Villa-Bologna-October-22-2024-Champions-League
40,League phase,3,Tue,2024-10-22,21:00,Sturm Graz at,0.7,0–2,1.4,pt Sporting CP,23691,Merkur Arena,Giorgi Kruashvili,https://fbref.com/en/matches/48444796/Sturm-Graz-Sporting-CP-October-22-2024-Champions-League
41,League phase,3,Tue,2024-10-22,21:00,Juventus it,0.2,0–1,2.5,de Stuttgart,41306,Allianz Stadium,Espen Eskås,https://fbref.com/en/matches/3f121c09/Juventus-Stuttgart-October-22-2024-Champions-League
42,League phase,3,Tue,2024-10-22,21:00,Real Madrid es,3.5,5–2,1.6,de Dortmund,74642,Estadio Santiago Bernabéu,István Kovács,https://fbref.com/en/matches/b77278d7/Real-Madrid-Dortmund-October-22-2024-Champions-League
43,League phase,3,Tue,2024-10-22,21:00,Girona es,1.7,2–0,0.5,sk Slovan Bratislava,9246,Estadi Municipal de Montilivi,Horațiu Fesnic,https://fbref.com/en/matches/bde57607/Girona-Slovan-Bratislava-October-22-2024-Champions-League
44,League phase,3,Tue,2024-10-22,21:00,Paris S-G fr,2.5,1–1,0.2,nl PSV Eindhoven,47511,Parc des Princes,Glenn Nyberg,https://fbref.com/en/matches/59f18bd3/Paris-Saint-Germain-PSV-Eindhoven-October-22-2024-Champions-League
45,League phase,3,Wed,2024-10-23,18:45,Brest fr,0.5,1–1,1.0,de Leverkusen,15510,Stade du Roudourou,Ivan Kružliak,https://fbref.com/en/matches/7afed8dc/Brest-Bayer-Leverkusen-October-23-2024-Champions-League
46,League phase,3,Wed,2024-10-23,18:45,Atalanta it,2.4,0–0,0.3,sct Celtic,21614,Gewiss Stadium,Irfan Peljto,https://fbref.com/en/matches/ef40e844/Atalanta-Celtic-October-23-2024-Champions-League
47,League phase,3,Wed,2024-10-23,20:00,Benfica pt,1.7,1–3,1.0,nl Feyenoord,61687,Estádio do Sport Lisboa e Benfica,Halil Umut Meler,https://fbref.com/en/matches/75a4583e/Benfica-Feyenoord-October-23-2024-Champions-League
48,League phase,3,Wed,2024-10-23,20:00,Manchester City eng,2.9,5–0,0.2,cz Sparta Prague,50116,Etihad Stadium,Maurizio Mariani,https://fbref.com/en/matches/b192c7c9/Manchester-City-Sparta-Prague-October-23-2024-Champions-League
49,League phase,3,Wed,2024-10-23,21:00,RB Salzburg at,1.2,0–2,1.6,hr Dinamo Zagreb,24018,Red Bull Arena,Danny Makkelie,https://fbref.com/en/matches/007fa209/Red-Bull-Salzburg-Dinamo-Zagreb-October-23-2024-Champions-League
50,League phase,3,Wed,2024-10-23,21:00,Young Boys ch,0.8,0–1,3.3,it Inter,31500,Stadion Wankdorf,Michael Oliver,https://fbref.com/en/matches/f9298241/Young-Boys-Internazionale-October-23-2024-Champions-League
51,League phase,3,Wed,2024-10-23,21:00,Barcelona es,2.2,4–1,1.0,de Bayern Munich,50312,Estadi Olímpic Lluís Companys,Slavko Vinčič,https://fbref.com/en/matches/710ee5bb/Barcelona-Bayern-Munich-October-23-2024-Champions-League
52,League phase,3,Wed,2024-10-23,21:00,Atlético Madrid es,2.3,1–3,1.3,fr Lille,61197,Riyadh Air Metropolitan Stadium,Marco Guida,https://fbref.com/en/matches/c956d6a4/Atletico-Madrid-Lille-October-23-2024-Champions-League
53,League phase,3,Wed,2024-10-23,21:00,RB Leipzig de,0.8,0–1,2.3,eng Liverpool,45228,Red Bull Arena,Sandro Schärer,https://fbref.com/en/matches/7acc13f8/RB-Leipzig-Liverpool-October-23-2024-Champions-League
54,League phase,4,Tue,2024-11-05,18:45,Slovan Bratislava sk,1.7,1–4,1.5,hr Dinamo Zagreb,22132,Štadión Tehelné pole,Anthony Taylor,https://fbref.com/en/matches/b17b4e64/Slovan-Bratislava-Dinamo-Zagreb-November-5-2024-Champions-League
55,League phase,4,Tue,2024-11-05,18:45,PSV Eindhoven nl,2.0,4–0,0.8,es Girona,34400,Philips Stadion,Michael Oliver,https://fbref.com/en/matches/e12ec3c6/PSV-Eindhoven-Girona-November-5-2024-Champions-League
56,League phase,4,Tue,2024-11-05,20:00,Sporting CP pt,2.9,4–1,2.1,eng Manchester City,47453,Estádio José Alvalade,Daniel Siebert,https://fbref.com/en/matches/342c86f6/Sporting-CP-Manchester-City-November-5-2024-Champions-League
57,League phase,4,Tue,2024-11-05,20:00,Liverpool eng,3.7,4–0,0.9,de Leverkusen,59790,Anfield,Danny Makkelie,https://fbref.com/en/matches/8fca6c33/Liverpool-Bayer-Leverkusen-November-5-2024-Champions-League
58,League phase,4,Tue,2024-11-05,20:00,Celtic sct,1.8,3–1,1.3,de RB Leipzig,57551,Celtic Park,Benoît Bastien,https://fbref.com/en/matches/c3867638/Celtic-RB-Leipzig-November-5-2024-Champions-League
59,League phase,4,Tue,2024-11-05,21:00,Bologna it,0.5,0–1,0.9,fr Monaco,23084,Stadio Renato Dall'Ara,Əliyar Ağayev,https://fbref.com/en/matches/2a80a9cc/Bologna-Monaco-November-5-2024-Champions-League
60,League phase,4,Tue,2024-11-05,21:00,Real Madrid es,2.6,1–3,2.5,it Milan,75561,Estadio Santiago Bernabéu,Slavko Vinčič,https://fbref.com/en/matches/3e59f3e0/Real-Madrid-Milan-November-5-2024-Champions-League
61,League phase,4,Tue,2024-11-05,21:00,Lille fr,0.8,1–1,1.4,it Juventus,48312,Decathlon Arena - Stade Pierre-Mauroy,Irfan Peljto,https://fbref.com/en/matches/f222cf32/Lille-Juventus-November-5-2024-Champions-League
62,League phase,4,Tue,2024-11-05,21:00,Dortmund de,2.0,1–0,0.4,at Sturm Graz,81365,Signal Iduna Park,Erik Lambrechts,https://fbref.com/en/matches/fcac354a/Dortmund-Sturm-Graz-November-5-2024-Champions-League
63,League phase,4,Wed,2024-11-06,18:45,Club Brugge be,1.4,1–0,0.4,eng Aston Villa,23466,Jan Breydelstadion,Tobias Stieler,https://fbref.com/en/matches/b11407d0/Club-Brugge-Aston-Villa-November-6-2024-Champions-League
64,League phase,4,Wed,2024-11-06,19:45,Shakhtar ua,2.0,2–1,1.0,ch Young Boys,17420,Veltins-Arena,Orel Grinfeeld,https://fbref.com/en/matches/a4b98ad4/Shakhtar-Donetsk-Young-Boys-November-6-2024-Champions-League
65,League phase,4,Wed,2024-11-06,21:00,Paris S-G fr,2.1,1–2,0.7,es Atlético Madrid,47369,Parc des Princes,Szymon Marciniak,https://fbref.com/en/matches/c32806c8/Paris-Saint-Germain-Atletico-Madrid-November-6-2024-Champions-League
66,League phase,4,Wed,2024-11-06,21:00,Bayern Munich de,1.4,1–0,0.1,pt Benfica,75000,Allianz Arena,Davide Massa,https://fbref.com/en/matches/07796431/Bayern-Munich-Benfica-November-6-2024-Champions-League
67,League phase,4,Wed,2024-11-06,21:00,Red Star rs,0.2,2–5,3.6,es Barcelona,48886,Stadion Rajko Mitić,Espen Eskås,https://fbref.com/en/matches/9a70feac/Red-Star-Belgrade-Barcelona-November-6-2024-Champions-League
68,League phase,4,Wed,2024-11-06,21:00,Sparta Prague cz,0.5,1–2,1.6,fr Brest,18033,epet Arena,Mykola Balakin,https://fbref.com/en/matches/9cef455e/Sparta-Prague-Brest-November-6-2024-Champions-League
69,League phase,4,Wed,2024-11-06,21:00,Feyenoord nl,0.8,1–3,1.7,at RB Salzburg,42774,Stadion Feijenoord,Donatas Rumšas,https://fbref.com/en/matches/164e2c72/Feyenoord-Red-Bull-Salzburg-November-6-2024-Champions-League
70,League phase,4,Wed,2024-11-06,21:00,Stuttgart de,1.0,0–2,2.3,it Atalanta,60000,MHPArena,Rade Obrenović,https://fbref.com/en/matches/506c92bc/Stuttgart-Atalanta-November-6-2024-Champions-League
71,League phase,4,Wed,2024-11-06,21:00,Inter it,1.1,1–0,1.8,eng Arsenal,75222,Stadio Giuseppe Meazza,István Kovács,https://fbref.com/en/matches/16d01a57/Internazionale-Arsenal-November-6-2024-Champions-League
72,League phase,5,Tue,2024-11-26,18:45,Slovan Bratislava sk,1.5,2–3,1.9,it Milan,22500,Štadión Tehelné pole,Jose Maria Sánchez,https://fbref.com/en/matches/28984772/Slovan-Bratislava-Milan-November-26-2024-Champions-League
73,League phase,5,Tue,2024-11-26,18:45,Sparta Prague cz,0.2,0–6,3.1,es Atlético Madrid,18110,epet Arena,Danny Makkelie,https://fbref.com/en/matches/7832fcc1/Sparta-Prague-Atletico-Madrid-November-26-2024-Champions-League
74,League phase,5,Tue,2024-11-26,20:00,Manchester City eng,2.1,3–3,2.2,nl Feyenoord,47011,Etihad Stadium,Radu Petrescu,https://fbref.com/en/matches/552c5c03/Manchester-City-Feyenoord-November-26-2024-Champions-League
75,League phase,5,Tue,2024-11-26,20:00,Sporting CP pt,1.0,1–5,4.0,eng Arsenal,47386,Estádio José Alvalade,Szymon Marciniak,https://fbref.com/en/matches/160ca071/Sporting-CP-Arsenal-November-26-2024-Champions-League
76,League phase,5,Tue,2024-11-26,21:00,Barcelona es,2.8,3–0,0.1,fr Brest,46317,Estadi Olímpic Lluís Companys,Irfan Peljto,https://fbref.com/en/matches/d22fed87/Barcelona-Brest-November-26-2024-Champions-League
77,League phase,5,Tue,2024-11-26,21:00,Leverkusen de,4.3,5–0,0.3,at RB Salzburg,29211,BayArena,Mykola Balakin,https://fbref.com/en/matches/3a843132/Bayer-Leverkusen-Red-Bull-Salzburg-November-26-2024-Champions-League
78,League phase,5,Tue,2024-11-26,21:00,Inter it,1.4,1–0,0.1,de RB Leipzig,63174,Stadio Giuseppe Meazza,João Pinheiro,https://fbref.com/en/matches/36f27dd4/Internazionale-RB-Leipzig-November-26-2024-Champions-League
79,League phase,5,Tue,2024-11-26,21:00,Bayern Munich de,2.4,1–0,0.8,fr Paris S-G,75000,Allianz Arena,István Kovács,https://fbref.com/en/matches/93b1eab0/Bayern-Munich-Paris-Saint-Germain-November-26-2024-Champions-League
80,League phase,5,Tue,2024-11-26,21:00,Young Boys ch,0.8,1–6,2.5,it Atalanta,31500,Stadion Wankdorf,Manfredas Lukjančukas,https://fbref.com/en/matches/cd869829/Young-Boys-Atalanta-November-26-2024-Champions-League
81,League phase,5,Wed,2024-11-27,18:45,Red Star rs,1.8,5–1,0.6,de Stuttgart,41372,Stadion Rajko Mitić,Erik Lambrechts,https://fbref.com/en/matches/8bd536f4/Red-Star-Belgrade-Stuttgart-November-27-2024-Champions-League
82,League phase,5,Wed,2024-11-27,18:45,Sturm Graz at,0.8,1–0,1.7,es Girona,21502,Merkur Arena,Rohit Saggi,https://fbref.com/en/matches/dcfcf574/Sturm-Graz-Girona-November-27-2024-Champions-League
83,League phase,5,Wed,2024-11-27,20:00,Aston Villa eng,1.2,0–0,0.4,it Juventus,42589,Villa Park,Jesús Gil,https://fbref.com/en/matches/c862f866/Aston-Villa-Juventus-November-27-2024-Champions-League
84,League phase,5,Wed,2024-11-27,20:00,Liverpool eng,2.7,2–0,1.2,es Real Madrid,59546,Anfield,François Letexier,https://fbref.com/en/matches/fe779356/Liverpool-Real-Madrid-November-27-2024-Champions-League
85,League phase,5,Wed,2024-11-27,20:00,Celtic sct,1.0,1–1,1.1,be Club Brugge,57456,Celtic Park,Georgi Kabakov,https://fbref.com/en/matches/c9fbb00d/Celtic-Club-Brugge-November-27-2024-Champions-League
86,League phase,5,Wed,2024-11-27,21:00,PSV Eindhoven nl,2.6,3–2,1.0,ua Shakhtar,35100,Philips Stadion,Urs Schnyder,https://fbref.com/en/matches/d6fcf0d3/PSV-Eindhoven-Shakhtar-Donetsk-November-27-2024-Champions-League
87,League phase,5,Wed,2024-11-27,21:00,Bologna it,1.7,1–2,2.1,fr Lille,22420,Stadio Renato Dall'Ara,Michael Oliver,https://fbref.com/en/matches/defdad60/Bologna-Lille-November-27-2024-Champions-League
88,League phase,5,Wed,2024-11-27,21:00,Dinamo Zagreb hr,0.2,0–3,1.7,de Dortmund,20019,Stadion Maksimir,Clément Turpin,https://fbref.com/en/matches/813836d2/Dinamo-Zagreb-Dortmund-November-27-2024-Champions-League
89,League phase,5,Wed,2024-11-27,21:00,Monaco fr,1.6,2–3,3.0,pt Benfica,13581,Stade Louis II,Rade Obrenović,https://fbref.com/en/matches/877f4c95/Monaco-Benfica-November-27-2024-Champions-League
90,League phase,6,Tue,2024-12-10,18:45,Dinamo Zagreb hr,0.5,0–0,0.4,sct Celtic,18158,Stadion Maksimir,Felix Zwayer,https://fbref.com/en/matches/bf1ff0cd/Dinamo-Zagreb-Celtic-December-10-2024-Champions-League
91,League phase,6,Tue,2024-12-10,18:45,Girona es,1.2,0–1,1.8,eng Liverpool,9241,Estadi Municipal de Montilivi,Benoît Bastien,https://fbref.com/en/matches/ac8de702/Girona-Liverpool-December-10-2024-Champions-League
92,League phase,6,Tue,2024-12-10,21:00,Leverkusen de,1.1,1–0,0.3,it Inter,30210,BayArena,Slavko Vinčič,https://fbref.com/en/matches/f53ce891/Bayer-Leverkusen-Internazionale-December-10-2024-Champions-League
93,League phase,6,Tue,2024-12-10,21:00,Brest fr,1.6,1–0,1.6,nl PSV Eindhoven,15778,Stade du Roudourou,Jose Maria Sánchez,https://fbref.com/en/matches/bcee1130/Brest-PSV-Eindhoven-December-10-2024-Champions-League

In [11]:
df2['Round'] = df2['Round'].astype(str)

In [13]:
league_phase = df2[df2['Round'] == 'League phase']

In [14]:
league_phase

,Round,Wk,Day,Date,Time,Home,xG,Score,xG.1,Away,Attendance,Venue,Referee,URL
0,League phase,1,Tue,2024-09-17,18:45,Young Boys ch,0.6,0–3,2.0,eng Aston Villa,31500,Stadion Wankdorf,Georgi Kabakov,https://fbref.com/en/matches/568274fc/Young-Boys-Aston-Villa-September-17-2024-Champions-League
1,League phase,1,Tue,2024-09-17,18:45,Juventus it,2.9,3–1,1.0,nl PSV Eindhoven,40417,Allianz Stadium,Alejandro Hernández,https://fbref.com/en/matches/931cd5fb/Juventus-PSV-Eindhoven-September-17-2024-Champions-League
2,League phase,1,Tue,2024-09-17,20:00,Sporting CP pt,1.6,2–0,0.4,fr Lille,40024,Estádio José Alvalade,Donatas Rumšas,https://fbref.com/en/matches/aaca158d/Sporting-CP-Lille-September-17-2024-Champions-League
3,League phase,1,Tue,2024-09-17,21:00,Real Madrid es,2.6,3–1,1.9,de Stuttgart,71288,Estadio Santiago Bernabéu,Halil Umut Meler,https://fbref.com/en/matches/4fb5fcbd/Real-Madrid-Stuttgart-September-17-2024-Champions-League
4,League phase,1,Tue,2024-09-17,21:00,Milan it,0.6,1–3,3.1,eng Liverpool,59826,Stadio Giuseppe Meazza,Espen Eskås,https://fbref.com/en/matches/54ed5557/Milan-Liverpool-September-17-2024-Champions-League
5,League phase,1,Tue,2024-09-17,21:00,Bayern Munich de,5.9,9–2,0.7,hr Dinamo Zagreb,75000,Allianz Arena,Juan Martínez,https://fbref.com/en/matches/7c5c2955/Bayern-Munich-Dinamo-Zagreb-September-17-2024-Champions-League
6,League phase,1,Wed,2024-09-18,18:45,Sparta Prague cz,2.5,3–0,0.6,at RB Salzburg,17612,epet Arena,Rade Obrenović,https://fbref.com/en/matches/936f3ee0/Sparta-Prague-Red-Bull-Salzburg-September-18-2024-Champions-League
7,League phase,1,Wed,2024-09-18,18:45,Bologna it,1.2,0–0,0.9,ua Shakhtar,23130,Stadio Renato Dall'Ara,Rohit Saggi,https://fbref.com/en/matches/85075de5/Bologna-Shakhtar-Donetsk-September-18-2024-Champions-League
8,League phase,1,Wed,2024-09-18,20:00,Celtic sct,3.8,5–1,0.5,sk Slovan Bratislava,56826,Celtic Park,Danny Makkelie,https://fbref.com/en/matches/16af036c/Celtic-Slovan-Bratislava-September-18-2024-Champions-League
9,League phase,1,Wed,2024-09-18,20:00,Manchester City eng,2.3,0–0,0.7,it Inter,50922,Etihad Stadium,Glenn Nyberg,https://fbref.com/en/matches/db400f4b/Manchester-City-Internazionale-September-18-2024-Champions-League
10,League phase,1,Wed,2024-09-18,21:00,Club Brugge be,1.2,0–3,1.9,de Dortmund,19961,Jan Breydelstadion,Irfan Peljto,https://fbref.com/en/matches/722df76c/Club-Brugge-Dortmund-September-18-2024-Champions-League
11,League phase,1,Wed,2024-09-18,21:00,Paris S-G fr,2.1,1–0,0.2,es Girona,39951,Parc des Princes,Daniel Siebert,https://fbref.com/en/matches/53cfba8e/Paris-Saint-Germain-Girona-September-18-2024-Champions-League
12,League phase,1,Thu,2024-09-19,18:45,Red Star rs,1.0,1–2,1.3,pt Benfica,44238,Stadion Rajko Mitić,Michael Oliver,https://fbref.com/en/matches/2d931c93/Red-Star-Belgrade-Benfica-September-19-2024-Champions-League
13,League phase,1,Thu,2024-09-19,18:45,Feyenoord nl,0.8,0–4,1.7,de Leverkusen,42297,Stadion Feijenoord,Davide Massa,https://fbref.com/en/matches/24c1d39c/Feyenoord-Bayer-Leverkusen-September-19-2024-Champions-League
14,League phase,1,Thu,2024-09-19,21:00,Monaco fr,1.3,2–1,0.4,es Barcelona,13296,Stade Louis II,Allard Lindhout,https://fbref.com/en/matches/745d19c2/Monaco-Barcelona-September-19-2024-Champions-League
15,League phase,1,Thu,2024-09-19,21:00,Atalanta it,1.2,0–0,0.8,eng Arsenal,22858,Gewiss Stadium,Clément Turpin,https://fbref.com/en/matches/108b9e41/Atalanta-Arsenal-September-19-2024-Champions-League
16,League phase,1,Thu,2024-09-19,21:00,Brest fr,2.1,2–1,0.5,at Sturm Graz,14518,Stade du Roudourou,Nick Walsh,https://fbref.com/en/matches/162f5233/Brest-Sturm-Graz-September-19-2024-Champions-League
17,League phase,1,Thu,2024-09-19,21:00,Atlético Madrid es,1.7,2–1,0.7,de RB Leipzig,57856,Riyadh Air Metropolitan Stadium,Ivan Kružliak,https://fbref.com/en/matches/a112dcca/Atletico-Madrid-RB-Leipzig-September-19-2024-Champions-League
18,League phase,2,Tue,2024-10-01,18:45,Stuttgart de,1.7,1–1,1.0,cz Sparta Prague,60000,MHPArena,Manfredas Lukjančukas,https://fbref.com/en/matches/80c7f5c5/Stuttgart-Sparta-Prague-October-1-2024-Champions-League
19,League phase,2,Tue,2024-10-01,18:45,RB Salzburg at,1.6,0–4,2.0,fr Brest,20232,Red Bull Arena,Anthony Taylor,https://fbref.com/en/matches/aa293551/Red-Bull-Salzburg-Brest-October-1-2024-Champions-League
20,League phase,2,Tue,2024-10-01,20:00,Arsenal eng,0.7,2–0,0.4,fr Paris S-G,60103,Emirates Stadium,Slavko Vinčič,https://fbref.com/en/matches/190f7f3f/Arsenal-Paris-Saint-Germain-October-1-2024-Champions-League
21,League phase,2,Tue,2024-10-01,21:00,Barcelona es,3.4,5–0,0.8,ch Young Boys,45097,Estadi Olímpic Lluís Companys,Erik Lambrechts,https://fbref.com/en/matches/9efdd96e/Barcelona-Young-Boys-October-1-2024-Champions-League
22,League phase,2,Tue,2024-10-01,21:00,Dortmund de,2.6,7–1,2.1,sct Celtic,81365,Signal Iduna Park,Jose Maria Sánchez,https://fbref.com/en/matches/925ea41c/Dortmund-Celtic-October-1-2024-Champions-League
23,League phase,2,Tue,2024-10-01,21:00,Inter it,2.8,4–0,0.5,rs Red Star,56391,Stadio Giuseppe Meazza,Felix Zwayer,https://fbref.com/en/matches/19b3b47e/Internazionale-Red-Star-Belgrade-October-1-2024-Champions-League
24,League phase,2,Tue,2024-10-01,21:00,Slovan Bratislava sk,0.1,0–4,3.7,eng Manchester City,22500,Štadión Tehelné pole,Davide Massa,https://fbref.com/en/matches/c46d8356/Slovan-Bratislava-Manchester-City-October-1-2024-Champions-League
25,League phase,2,Tue,2024-10-01,21:00,PSV Eindhoven nl,2.6,1–1,1.3,pt Sporting CP,34400,Philips Stadion,Marco Guida,https://fbref.com/en/matches/bd985714/PSV-Eindhoven-Sporting-CP-October-1-2024-Champions-League
26,League phase,2,Tue,2024-10-01,21:00,Leverkusen de,1.8,1–0,1.0,it Milan,30210,BayArena,Sandro Schärer,https://fbref.com/en/matches/91294a8b/Bayer-Leverkusen-Milan-October-1-2024-Champions-League
27,League phase,2,Wed,2024-10-02,18:45,Girona es,2.2,2–3,1.9,nl Feyenoord,8752,Estadi Municipal de Montilivi,Urs Schnyder,https://fbref.com/en/matches/67eb4cdc/Girona-Feyenoord-October-2-2024-Champions-League
28,League phase,2,Wed,2024-10-02,18:45,Shakhtar ua,0.3,0–3,2.6,it Atalanta,21636,Veltins-Arena,João Pinheiro,https://fbref.com/en/matches/c5e0de02/Shakhtar-Donetsk-Atalanta-October-2-2024-Champions-League
29,League phase,2,Wed,2024-10-02,20:00,Liverpool eng,1.2,2–0,0.6,it Bologna,59816,Anfield,Nikola Dabanović,https://fbref.com/en/matches/a749c1fe/Liverpool-Bologna-October-2-2024-Champions-League
30,League phase,2,Wed,2024-10-02,20:00,Aston Villa eng,0.4,1–0,1.5,de Bayern Munich,38991,Villa Park,Radu Petrescu,https://fbref.com/en/matches/a516238d/Aston-Villa-Bayern-Munich-October-2-2024-Champions-League
31,League phase,2,Wed,2024-10-02,20:00,Benfica pt,4.4,4–0,0.2,es Atlético Madrid,62028,Estádio do Sport Lisboa e Benfica,Serdar Gözübüyük,https://fbref.com/en/matches/e5e2d3a2/Benfica-Atletico-Madrid-October-2-2024-Champions-League
32,League phase,2,Wed,2024-10-02,21:00,Dinamo Zagreb hr,1.0,2–2,1.9,fr Monaco,12462,Stadion Maksimir,Harm Osmers,https://fbref.com/en/matches/facef700/Dinamo-Zagreb-Monaco-October-2-2024-Champions-League
33,League phase,2,Wed,2024-10-02,21:00,RB Leipzig de,3.3,2–3,1.2,it Juventus,45228,Red Bull Arena,François Letexier,https://fbref.com/en/matches/2e8465b9/RB-Leipzig-Juventus-October-2-2024-Champions-League
34,League phase,2,Wed,2024-10-02,21:00,Sturm Graz at,0.4,0–1,0.7,be Club Brugge,23205,Merkur Arena,Əliyar Ağayev,https://fbref.com/en/matches/f871e405/Sturm-Graz-Club-Brugge-October-2-2024-Champions-League
35,League phase,2,Wed,2024-10-02,21:00,Lille fr,1.1,1–0,2.0,es Real Madrid,48205,Decathlon Arena - Stade Pierre-Mauroy,Maurizio Mariani,https://fbref.com/en/matches/70cd3947/Lille-Real-Madrid-October-2-2024-Champions-League
36,League phase,3,Tue,2024-10-22,18:45,Monaco fr,3.3,5–1,1.0,rs Red Star,9590,Stade Louis II,Tobias Stieler,https://fbref.com/en/matches/8450b165/Monaco-Red-Star-Belgrade-October-22-2024-Champions-League
37,League phase,3,Tue,2024-10-22,18:45,Milan it,1.2,3–1,0.6,be Club Brugge,58649,Stadio Giuseppe Meazza,Felix Zwayer,https://fbref.com/en/matches/e11229bf/Milan-Club-Brugge-October-22-2024-Champions-League
38,League phase,3,Tue,2024-10-22,20:00,Arsenal eng,1.8,1–0,0.7,ua Shakhtar,59594,Emirates Stadium,Benoît Bastien,https://fbref.com/en/matches/32f2220e/Arsenal-Shakhtar-Donetsk-October-22-2024-Champions-League
39,League phase,3,Tue,2024-10-22,20:00,Aston Villa eng,1.2,2–0,0.9,it Bologna,41847,Villa Park,João Pinheiro,https://fbref.com/en/matches/e546b256/Aston-Villa-Bologna-October-22-2024-Champions-League
40,League phase,3,Tue,2024-10-22,21:00,Sturm Graz at,0.7,0–2,1.4,pt Sporting CP,23691,Merkur Arena,Giorgi Kruashvili,https://fbref.com/en/matches/48444796/Sturm-Graz-Sporting-CP-October-22-2024-Champions-League
41,League phase,3,Tue,2024-10-22,21:00,Juventus it,0.2,0–1,2.5,de Stuttgart,41306,Allianz Stadium,Espen Eskås,https://fbref.com/en/matches/3f121c09/Juventus-Stuttgart-October-22-2024-Champions-League
42,League phase,3,Tue,2024-10-22,21:00,Real Madrid es,3.5,5–2,1.6,de Dortmund,74642,Estadio Santiago Bernabéu,István Kovács,https://fbref.com/en/matches/b77278d7/Real-Madrid-Dortmund-October-22-2024-Champions-League
43,League phase,3,Tue,2024-10-22,21:00,Girona es,1.7,2–0,0.5,sk Slovan Bratislava,9246,Estadi Municipal de Montilivi,Horațiu Fesnic,https://fbref.com/en/matches/bde57607/Girona-Slovan-Bratislava-October-22-2024-Champions-League
44,League phase,3,Tue,2024-10-22,21:00,Paris S-G fr,2.5,1–1,0.2,nl PSV Eindhoven,47511,Parc des Princes,Glenn Nyberg,https://fbref.com/en/matches/59f18bd3/Paris-Saint-Germain-PSV-Eindhoven-October-22-2024-Champions-League
45,League phase,3,Wed,2024-10-23,18:45,Brest fr,0.5,1–1,1.0,de Leverkusen,15510,Stade du Roudourou,Ivan Kružliak,https://fbref.com/en/matches/7afed8dc/Brest-Bayer-Leverkusen-October-23-2024-Champions-League
46,League phase,3,Wed,2024-10-23,18:45,Atalanta it,2.4,0–0,0.3,sct Celtic,21614,Gewiss Stadium,Irfan Peljto,https://fbref.com/en/matches/ef40e844/Atalanta-Celtic-October-23-2024-Champions-League
47,League phase,3,Wed,2024-10-23,20:00,Benfica pt,1.7,1–3,1.0,nl Feyenoord,61687,Estádio do Sport Lisboa e Benfica,Halil Umut Meler,https://fbref.com/en/matches/75a4583e/Benfica-Feyenoord-October-23-2024-Champions-League
48,League phase,3,Wed,2024-10-23,20:00,Manchester City eng,2.9,5–0,0.2,cz Sparta Prague,50116,Etihad Stadium,Maurizio Mariani,https://fbref.com/en/matches/b192c7c9/Manchester-City-Sparta-Prague-October-23-2024-Champions-League
49,League phase,3,Wed,2024-10-23,21:00,RB Salzburg at,1.2,0–2,1.6,hr Dinamo Zagreb,24018,Red Bull Arena,Danny Makkelie,https://fbref.com/en/matches/007fa209/Red-Bull-Salzburg-Dinamo-Zagreb-October-23-2024-Champions-League
50,League phase,3,Wed,2024-10-23,21:00,Young Boys ch,0.8,0–1,3.3,it Inter,31500,Stadion Wankdorf,Michael Oliver,https://fbref.com/en/matches/f9298241/Young-Boys-Internazionale-October-23-2024-Champions-League
51,League phase,3,Wed,2024-10-23,21:00,Barcelona es,2.2,4–1,1.0,de Bayern Munich,50312,Estadi Olímpic Lluís Companys,Slavko Vinčič,https://fbref.com/en/matches/710ee5bb/Barcelona-Bayern-Munich-October-23-2024-Champions-League
52,League phase,3,Wed,2024-10-23,21:00,Atlético Madrid es,2.3,1–3,1.3,fr Lille,61197,Riyadh Air Metropolitan Stadium,Marco Guida,https://fbref.com/en/matches/c956d6a4/Atletico-Madrid-Lille-October-23-2024-Champions-League
53,League phase,3,Wed,2024-10-23,21:00,RB Leipzig de,0.8,0–1,2.3,eng Liverpool,45228,Red Bull Arena,Sandro Schärer,https://fbref.com/en/matches/7acc13f8/RB-Leipzig-Liverpool-October-23-2024-Champions-League
54,League phase,4,Tue,2024-11-05,18:45,Slovan Bratislava sk,1.7,1–4,1.5,hr Dinamo Zagreb,22132,Štadión Tehelné pole,Anthony Taylor,https://fbref.com/en/matches/b17b4e64/Slovan-Bratislava-Dinamo-Zagreb-November-5-2024-Champions-League
55,League phase,4,Tue,2024-11-05,18:45,PSV Eindhoven nl,2.0,4–0,0.8,es Girona,34400,Philips Stadion,Michael Oliver,https://fbref.com/en/matches/e12ec3c6/PSV-Eindhoven-Girona-November-5-2024-Champions-League
56,League phase,4,Tue,2024-11-05,20:00,Sporting CP pt,2.9,4–1,2.1,eng Manchester City,47453,Estádio José Alvalade,Daniel Siebert,https://fbref.com/en/matches/342c86f6/Sporting-CP-Manchester-City-November-5-2024-Champions-League
57,League phase,4,Tue,2024-11-05,20:00,Liverpool eng,3.7,4–0,0.9,de Leverkusen,59790,Anfield,Danny Makkelie,https://fbref.com/en/matches/8fca6c33/Liverpool-Bayer-Leverkusen-November-5-2024-Champions-League
58,League phase,4,Tue,2024-11-05,20:00,Celtic sct,1.8,3–1,1.3,de RB Leipzig,57551,Celtic Park,Benoît Bastien,https://fbref.com/en/matches/c3867638/Celtic-RB-Leipzig-November-5-2024-Champions-League
59,League phase,4,Tue,2024-11-05,21:00,Bologna it,0.5,0–1,0.9,fr Monaco,23084,Stadio Renato Dall'Ara,Əliyar Ağayev,https://fbref.com/en/matches/2a80a9cc/Bologna-Monaco-November-5-2024-Champions-League
60,League phase,4,Tue,2024-11-05,21:00,Real Madrid es,2.6,1–3,2.5,it Milan,75561,Estadio Santiago Bernabéu,Slavko Vinčič,https://fbref.com/en/matches/3e59f3e0/Real-Madrid-Milan-November-5-2024-Champions-League
61,League phase,4,Tue,2024-11-05,21:00,Lille fr,0.8,1–1,1.4,it Juventus,48312,Decathlon Arena - Stade Pierre-Mauroy,Irfan Peljto,https://fbref.com/en/matches/f222cf32/Lille-Juventus-November-5-2024-Champions-League
62,League phase,4,Tue,2024-11-05,21:00,Dortmund de,2.0,1–0,0.4,at Sturm Graz,81365,Signal Iduna Park,Erik Lambrechts,https://fbref.com/en/matches/fcac354a/Dortmund-Sturm-Graz-November-5-2024-Champions-League
63,League phase,4,Wed,2024-11-06,18:45,Club Brugge be,1.4,1–0,0.4,eng Aston Villa,23466,Jan Breydelstadion,Tobias Stieler,https://fbref.com/en/matches/b11407d0/Club-Brugge-Aston-Villa-November-6-2024-Champions-League
64,League phase,4,Wed,2024-11-06,19:45,Shakhtar ua,2.0,2–1,1.0,ch Young Boys,17420,Veltins-Arena,Orel Grinfeeld,https://fbref.com/en/matches/a4b98ad4/Shakhtar-Donetsk-Young-Boys-November-6-2024-Champions-League
65,League phase,4,Wed,2024-11-06,21:00,Paris S-G fr,2.1,1–2,0.7,es Atlético Madrid,47369,Parc des Princes,Szymon Marciniak,https://fbref.com/en/matches/c32806c8/Paris-Saint-Germain-Atletico-Madrid-November-6-2024-Champions-League
66,League phase,4,Wed,2024-11-06,21:00,Bayern Munich de,1.4,1–0,0.1,pt Benfica,75000,Allianz Arena,Davide Massa,https://fbref.com/en/matches/07796431/Bayern-Munich-Benfica-November-6-2024-Champions-League
67,League phase,4,Wed,2024-11-06,21:00,Red Star rs,0.2,2–5,3.6,es Barcelona,48886,Stadion Rajko Mitić,Espen Eskås,https://fbref.com/en/matches/9a70feac/Red-Star-Belgrade-Barcelona-November-6-2024-Champions-League
68,League phase,4,Wed,2024-11-06,21:00,Sparta Prague cz,0.5,1–2,1.6,fr Brest,18033,epet Arena,Mykola Balakin,https://fbref.com/en/matches/9cef455e/Sparta-Prague-Brest-November-6-2024-Champions-League
69,League phase,4,Wed,2024-11-06,21:00,Feyenoord nl,0.8,1–3,1.7,at RB Salzburg,42774,Stadion Feijenoord,Donatas Rumšas,https://fbref.com/en/matches/164e2c72/Feyenoord-Red-Bull-Salzburg-November-6-2024-Champions-League
70,League phase,4,Wed,2024-11-06,21:00,Stuttgart de,1.0,0–2,2.3,it Atalanta,60000,MHPArena,Rade Obrenović,https://fbref.com/en/matches/506c92bc/Stuttgart-Atalanta-November-6-2024-Champions-League
71,League phase,4,Wed,2024-11-06,21:00,Inter it,1.1,1–0,1.8,eng Arsenal,75222,Stadio Giuseppe Meazza,István Kovács,https://fbref.com/en/matches/16d01a57/Internazionale-Arsenal-November-6-2024-Champions-League
72,League phase,5,Tue,2024-11-26,18:45,Slovan Bratislava sk,1.5,2–3,1.9,it Milan,22500,Štadión Tehelné pole,Jose Maria Sánchez,https://fbref.com/en/matches/28984772/Slovan-Bratislava-Milan-November-26-2024-Champions-League
73,League phase,5,Tue,2024-11-26,18:45,Sparta Prague cz,0.2,0–6,3.1,es Atlético Madrid,18110,epet Arena,Danny Makkelie,https://fbref.com/en/matches/7832fcc1/Sparta-Prague-Atletico-Madrid-November-26-2024-Champions-League
74,League phase,5,Tue,2024-11-26,20:00,Manchester City eng,2.1,3–3,2.2,nl Feyenoord,47011,Etihad Stadium,Radu Petrescu,https://fbref.com/en/matches/552c5c03/Manchester-City-Feyenoord-November-26-2024-Champions-League
75,League phase,5,Tue,2024-11-26,20:00,Sporting CP pt,1.0,1–5,4.0,eng Arsenal,47386,Estádio José Alvalade,Szymon Marciniak,https://fbref.com/en/matches/160ca071/Sporting-CP-Arsenal-November-26-2024-Champions-League
76,League phase,5,Tue,2024-11-26,21:00,Barcelona es,2.8,3–0,0.1,fr Brest,46317,Estadi Olímpic Lluís Companys,Irfan Peljto,https://fbref.com/en/matches/d22fed87/Barcelona-Brest-November-26-2024-Champions-League
77,League phase,5,Tue,2024-11-26,21:00,Leverkusen de,4.3,5–0,0.3,at RB Salzburg,29211,BayArena,Mykola Balakin,https://fbref.com/en/matches/3a843132/Bayer-Leverkusen-Red-Bull-Salzburg-November-26-2024-Champions-League
78,League phase,5,Tue,2024-11-26,21:00,Inter it,1.4,1–0,0.1,de RB Leipzig,63174,Stadio Giuseppe Meazza,João Pinheiro,https://fbref.com/en/matches/36f27dd4/Internazionale-RB-Leipzig-November-26-2024-Champions-League
79,League phase,5,Tue,2024-11-26,21:00,Bayern Munich de,2.4,1–0,0.8,fr Paris S-G,75000,Allianz Arena,István Kovács,https://fbref.com/en/matches/93b1eab0/Bayern-Munich-Paris-Saint-Germain-November-26-2024-Champions-League
80,League phase,5,Tue,2024-11-26,21:00,Young Boys ch,0.8,1–6,2.5,it Atalanta,31500,Stadion Wankdorf,Manfredas Lukjančukas,https://fbref.com/en/matches/cd869829/Young-Boys-Atalanta-November-26-2024-Champions-League
81,League phase,5,Wed,2024-11-27,18:45,Red Star rs,1.8,5–1,0.6,de Stuttgart,41372,Stadion Rajko Mitić,Erik Lambrechts,https://fbref.com/en/matches/8bd536f4/Red-Star-Belgrade-Stuttgart-November-27-2024-Champions-League
82,League phase,5,Wed,2024-11-27,18:45,Sturm Graz at,0.8,1–0,1.7,es Girona,21502,Merkur Arena,Rohit Saggi,https://fbref.com/en/matches/dcfcf574/Sturm-Graz-Girona-November-27-2024-Champions-League
83,League phase,5,Wed,2024-11-27,20:00,Aston Villa eng,1.2,0–0,0.4,it Juventus,42589,Villa Park,Jesús Gil,https://fbref.com/en/matches/c862f866/Aston-Villa-Juventus-November-27-2024-Champions-League
84,League phase,5,Wed,2024-11-27,20:00,Liverpool eng,2.7,2–0,1.2,es Real Madrid,59546,Anfield,François Letexier,https://fbref.com/en/matches/fe779356/Liverpool-Real-Madrid-November-27-2024-Champions-League
85,League phase,5,Wed,2024-11-27,20:00,Celtic sct,1.0,1–1,1.1,be Club Brugge,57456,Celtic Park,Georgi Kabakov,https://fbref.com/en/matches/c9fbb00d/Celtic-Club-Brugge-November-27-2024-Champions-League
86,League phase,5,Wed,2024-11-27,21:00,PSV Eindhoven nl,2.6,3–2,1.0,ua Shakhtar,35100,Philips Stadion,Urs Schnyder,https://fbref.com/en/matches/d6fcf0d3/PSV-Eindhoven-Shakhtar-Donetsk-November-27-2024-Champions-League
87,League phase,5,Wed,2024-11-27,21:00,Bologna it,1.7,1–2,2.1,fr Lille,22420,Stadio Renato Dall'Ara,Michael Oliver,https://fbref.com/en/matches/defdad60/Bologna-Lille-November-27-2024-Champions-League
88,League phase,5,Wed,2024-11-27,21:00,Dinamo Zagreb hr,0.2,0–3,1.7,de Dortmund,20019,Stadion Maksimir,Clément Turpin,https://fbref.com/en/matches/813836d2/Dinamo-Zagreb-Dortmund-November-27-2024-Champions-League
89,League phase,5,Wed,2024-11-27,21:00,Monaco fr,1.6,2–3,3.0,pt Benfica,13581,Stade Louis II,Rade Obrenović,https://fbref.com/en/matches/877f4c95/Monaco-Benfica-November-27-2024-Champions-League
90,League phase,6,Tue,2024-12-10,18:45,Dinamo Zagreb hr,0.5,0–0,0.4,sct Celtic,18158,Stadion Maksimir,Felix Zwayer,https://fbref.com/en/matches/bf1ff0cd/Dinamo-Zagreb-Celtic-December-10-2024-Champions-League
91,League phase,6,Tue,2024-12-10,18:45,Girona es,1.2,0–1,1.8,eng Liverpool,9241,Estadi Municipal de Montilivi,Benoît Bastien,https://fbref.com/en/matches/ac8de702/Girona-Liverpool-December-10-2024-Champions-League
92,League phase,6,Tue,2024-12-10,21:00,Leverkusen de,1.1,1–0,0.3,it Inter,30210,BayArena,Slavko Vinčič,https://fbref.com/en/matches/f53ce891/Bayer-Leverkusen-Internazionale-December-10-2024-Champions-League
93,League phase,6,Tue,2024-12-10,21:00,Brest fr,1.6,1–0,1.6,nl PSV Eindhoven,15778,Stade du Roudourou,Jose Maria Sánchez,https://fbref.com/en/matches/bcee1130/Brest-PSV-Eindhoven-December-10-2024-Champions-League

In [17]:
league_phase['URL'].to_list()

['https://fbref.com/en/matches/568274fc/Young-Boys-Aston-Villa-September-17-2024-Champions-League',
 'https://fbref.com/en/matches/931cd5fb/Juventus-PSV-Eindhoven-September-17-2024-Champions-League',
 'https://fbref.com/en/matches/aaca158d/Sporting-CP-Lille-September-17-2024-Champions-League',
 'https://fbref.com/en/matches/4fb5fcbd/Real-Madrid-Stuttgart-September-17-2024-Champions-League',
 'https://fbref.com/en/matches/54ed5557/Milan-Liverpool-September-17-2024-Champions-League',
 'https://fbref.com/en/matches/7c5c2955/Bayern-Munich-Dinamo-Zagreb-September-17-2024-Champions-League',
 'https://fbref.com/en/matches/936f3ee0/Sparta-Prague-Red-Bull-Salzburg-September-18-2024-Champions-League',
 'https://fbref.com/en/matches/85075de5/Bologna-Shakhtar-Donetsk-September-18-2024-Champions-League',
 'https://fbref.com/en/matches/16af036c/Celtic-Slovan-Bratislava-September-18-2024-Champions-League',
 'https://fbref.com/en/matches/db400f4b/Manchester-City-Internazionale-September-18-2024-Champions-League',
 'https://fbref.com/en/matches/722df76c/Club-Brugge-Dortmund-September-18-2024-Champions-League',
 'https://fbref.com/en/matches/53cfba8e/Paris-Saint-Germain-Girona-September-18-2024-Champions-League',
 'https://fbref.com/en/matches/2d931c93/Red-Star-Belgrade-Benfica-September-19-2024-Champions-League',
 'https://fbref.com/en/matches/24c1d39c/Feyenoord-Bayer-Leverkusen-September-19-2024-Champions-League',
 'https://fbref.com/en/matches/745d19c2/Monaco-Barcelona-September-19-2024-Champions-League',
 'https://fbref.com/en/matches/108b9e41/Atalanta-Arsenal-September-19-2024-Champions-League',
 'https://fbref.com/en/matches/162f5233/Brest-Sturm-Graz-September-19-2024-Champions-League',
 'https://fbref.com/en/matches/a112dcca/Atletico-Madrid-RB-Leipzig-September-19-2024-Champions-League',
 'https://fbref.com/en/matches/80c7f5c5/Stuttgart-Sparta-Prague-October-1-2024-Champions-League',
 'https://fbref.com/en/matches/aa293551/Red-Bull-Salzburg-Brest-October-1-2024-Champions-League',
 'https://fbref.com/en/matches/190f7f3f/Arsenal-Paris-Saint-Germain-October-1-2024-Champions-League',
 'https://fbref.com/en/matches/9efdd96e/Barcelona-Young-Boys-October-1-2024-Champions-League',
 'https://fbref.com/en/matches/925ea41c/Dortmund-Celtic-October-1-2024-Champions-League',
 'https://fbref.com/en/matches/19b3b47e/Internazionale-Red-Star-Belgrade-October-1-2024-Champions-League',
 'https://fbref.com/en/matches/c46d8356/Slovan-Bratislava-Manchester-City-October-1-2024-Champions-League',
 'https://fbref.com/en/matches/bd985714/PSV-Eindhoven-Sporting-CP-October-1-2024-Champions-League',
 'https://fbref.com/en/matches/91294a8b/Bayer-Leverkusen-Milan-October-1-2024-Champions-League',
 'https://fbref.com/en/matches/67eb4cdc/Girona-Feyenoord-October-2-2024-Champions-League',
 'https://fbref.com/en/matches/c5e0de02/Shakhtar-Donetsk-Atalanta-October-2-2024-Champions-League',
 'https://fbref.com/en/matches/a749c1fe/Liverpool-Bologna-October-2-2024-Champions-League',
 'https://fbref.com/en/matches/a516238d/Aston-Villa-Bayern-Munich-October-2-2024-Champions-League',
 'https://fbref.com/en/matches/e5e2d3a2/Benfica-Atletico-Madrid-October-2-2024-Champions-League',
 'https://fbref.com/en/matches/facef700/Dinamo-Zagreb-Monaco-October-2-2024-Champions-League',
 'https://fbref.com/en/matches/2e8465b9/RB-Leipzig-Juventus-October-2-2024-Champions-League',
 'https://fbref.com/en/matches/f871e405/Sturm-Graz-Club-Brugge-October-2-2024-Champions-League',
 'https://fbref.com/en/matches/70cd3947/Lille-Real-Madrid-October-2-2024-Champions-League',
 'https://fbref.com/en/matches/8450b165/Monaco-Red-Star-Belgrade-October-22-2024-Champions-League',
 'https://fbref.com/en/matches/e11229bf/Milan-Club-Brugge-October-22-2024-Champions-League',
 'https://fbref.com/en/matches/32f2220e/Arsenal-Shakhtar-Donetsk-October-22-2024-Champions-League',
 'https://fbref.com/en/matches/e546b256/Aston-Villa-Bologna-October-22-2024-Champions-League',
 'https://fbref.com/en/matches/48444796/Sturm-Graz-Sporting-CP-October-22-2024-Champions-League',
 'https://fbref.com/en/matches/3f121c09/Juventus-Stuttgart-October-22-2024-Champions-League',
 'https://fbref.com/en/matches/b77278d7/Real-Madrid-Dortmund-October-22-2024-Champions-League',
 'https://fbref.com/en/matches/bde57607/Girona-Slovan-Bratislava-October-22-2024-Champions-League',
 'https://fbref.com/en/matches/59f18bd3/Paris-Saint-Germain-PSV-Eindhoven-October-22-2024-Champions-League',
 'https://fbref.com/en/matches/7afed8dc/Brest-Bayer-Leverkusen-October-23-2024-Champions-League',
 'https://fbref.com/en/matches/ef40e844/Atalanta-Celtic-October-23-2024-Champions-League',
 'https://fbref.com/en/matches/75a4583e/Benfica-Feyenoord-October-23-2024-Champions-League',
 'https://fbref.com/en/matches/b192c7c9/Manchester-City-Sparta-Prague-October-23-2024-Champions-League',
 'https://fbref.com/en/matches/007fa209/Red-Bull-Salzburg-Dinamo-Zagreb-October-23-2024-Champions-League',
 'https://fbref.com/en/matches/f9298241/Young-Boys-Internazionale-October-23-2024-Champions-League',
 'https://fbref.com/en/matches/710ee5bb/Barcelona-Bayern-Munich-October-23-2024-Champions-League',
 'https://fbref.com/en/matches/c956d6a4/Atletico-Madrid-Lille-October-23-2024-Champions-League',
 'https://fbref.com/en/matches/7acc13f8/RB-Leipzig-Liverpool-October-23-2024-Champions-League',
 'https://fbref.com/en/matches/b17b4e64/Slovan-Bratislava-Dinamo-Zagreb-November-5-2024-Champions-League',
 'https://fbref.com/en/matches/e12ec3c6/PSV-Eindhoven-Girona-November-5-2024-Champions-League',
 'https://fbref.com/en/matches/342c86f6/Sporting-CP-Manchester-City-November-5-2024-Champions-League',
 'https://fbref.com/en/matches/8fca6c33/Liverpool-Bayer-Leverkusen-November-5-2024-Champions-League',
 'https://fbref.com/en/matches/c3867638/Celtic-RB-Leipzig-November-5-2024-Champions-League',
 'https://fbref.com/en/matches/2a80a9cc/Bologna-Monaco-November-5-2024-Champions-League',
 'https://fbref.com/en/matches/3e59f3e0/Real-Madrid-Milan-November-5-2024-Champions-League',
 'https://fbref.com/en/matches/f222cf32/Lille-Juventus-November-5-2024-Champions-League',
 'https://fbref.com/en/matches/fcac354a/Dortmund-Sturm-Graz-November-5-2024-Champions-League',
 'https://fbref.com/en/matches/b11407d0/Club-Brugge-Aston-Villa-November-6-2024-Champions-League',
 'https://fbref.com/en/matches/a4b98ad4/Shakhtar-Donetsk-Young-Boys-November-6-2024-Champions-League',
 'https://fbref.com/en/matches/c32806c8/Paris-Saint-Germain-Atletico-Madrid-November-6-2024-Champions-League',
 'https://fbref.com/en/matches/07796431/Bayern-Munich-Benfica-November-6-2024-Champions-League',
 'https://fbref.com/en/matches/9a70feac/Red-Star-Belgrade-Barcelona-November-6-2024-Champions-League',
 'https://fbref.com/en/matches/9cef455e/Sparta-Prague-Brest-November-6-2024-Champions-League',
 'https://fbref.com/en/matches/164e2c72/Feyenoord-Red-Bull-Salzburg-November-6-2024-Champions-League',
 'https://fbref.com/en/matches/506c92bc/Stuttgart-Atalanta-November-6-2024-Champions-League',
 'https://fbref.com/en/matches/16d01a57/Internazionale-Arsenal-November-6-2024-Champions-League',
 'https://fbref.com/en/matches/28984772/Slovan-Bratislava-Milan-November-26-2024-Champions-League',
 'https://fbref.com/en/matches/7832fcc1/Sparta-Prague-Atletico-Madrid-November-26-2024-Champions-League',
 'https://fbref.com/en/matches/552c5c03/Manchester-City-Feyenoord-November-26-2024-Champions-League',
 'https://fbref.com/en/matches/160ca071/Sporting-CP-Arsenal-November-26-2024-Champions-League',
 'https://fbref.com/en/matches/d22fed87/Barcelona-Brest-November-26-2024-Champions-League',
 'https://fbref.com/en/matches/3a843132/Bayer-Leverkusen-Red-Bull-Salzburg-November-26-2024-Champions-League',
 'https://fbref.com/en/matches/36f27dd4/Internazionale-RB-Leipzig-November-26-2024-Champions-League',
 'https://fbref.com/en/matches/93b1eab0/Bayern-Munich-Paris-Saint-Germain-November-26-2024-Champions-League',
 'https://fbref.com/en/matches/cd869829/Young-Boys-Atalanta-November-26-2024-Champions-League',
 'https://fbref.com/en/matches/8bd536f4/Red-Star-Belgrade-Stuttgart-November-27-2024-Champions-League',
 'https://fbref.com/en/matches/dcfcf574/Sturm-Graz-Girona-November-27-2024-Champions-League',
 'https://fbref.com/en/matches/c862f866/Aston-Villa-Juventus-November-27-2024-Champions-League',
 'https://fbref.com/en/matches/fe779356/Liverpool-Real-Madrid-November-27-2024-Champions-League',
 'https://fbref.com/en/matches/c9fbb00d/Celtic-Club-Brugge-November-27-2024-Champions-League',
 'https://fbref.com/en/matches/d6fcf0d3/PSV-Eindhoven-Shakhtar-Donetsk-November-27-2024-Champions-League',
 'https://fbref.com/en/matches/defdad60/Bologna-Lille-November-27-2024-Champions-League',
 'https://fbref.com/en/matches/813836d2/Dinamo-Zagreb-Dortmund-November-27-2024-Champions-League',
 'https://fbref.com/en/matches/877f4c95/Monaco-Benfica-November-27-2024-Champions-League',
 'https://fbref.com/en/matches/bf1ff0cd/Dinamo-Zagreb-Celtic-December-10-2024-Champions-League',
 'https://fbref.com/en/matches/ac8de702/Girona-Liverpool-December-10-2024-Champions-League',
 'https://fbref.com/en/matches/f53ce891/Bayer-Leverkusen-Internazionale-December-10-2024-Champions-League',
 'https://fbref.com/en/matches/bcee1130/Brest-PSV-Eindhoven-December-10-2024-Champions-League',
 'https://fbref.com/en/matches/2e40ef5f/Club-Brugge-Sporting-CP-December-10-2024-Champions-League',
 'https://fbref.com/en/matches/4ae86197/Red-Bull-Salzburg-Paris-Saint-Germain-December-10-2024-Champions-League',
 'https://fbref.com/en/matches/64174109/RB-Leipzig-Aston-Villa-December-10-2024-Champions-League',
 'https://fbref.com/en/matches/f8e116ea/Atalanta-Real-Madrid-December-10-2024-Champions-League',
 'https://fbref.com/en/matches/d54ab572/Shakhtar-Donetsk-Bayern-Munich-December-10-2024-Champions-League',
 'https://fbref.com/en/matches/e80b91b4/Lille-Sturm-Graz-December-11-2024-Champions-League',
 'https://fbref.com/en/matches/bfe9f8f6/Atletico-Madrid-Slovan-Bratislava-December-11-2024-Champions-League',
 'https://fbref.com/en/matches/6aa52408/Arsenal-Monaco-December-11-2024-Champions-League',
 'https://fbref.com/en/matches/539a620f/Benfica-Bologna-December-11-2024-Champions-League',
 'https://fbref.com/en/matches/5ff4551f/Milan-Red-Star-Belgrade-December-11-2024-Champions-League',
 'https://fbref.com/en/matches/10b5de7b/Juventus-Manchester-City-December-11-2024-Champions-League',
 'https://fbref.com/en/matches/379275b8/Stuttgart-Young-Boys-December-11-2024-Champions-League',
 'https://fbref.com/en/matches/cf33e56f/Dortmund-Barcelona-December-11-2024-Champions-League',
 'https://fbref.com/en/matches/4e152dc8/Feyenoord-Sparta-Prague-December-11-2024-Champions-League',
 'https://fbref.com/en/matches/16649d85/Atalanta-Sturm-Graz-January-21-2025-Champions-League',
 'https://fbref.com/en/matches/283b037e/Monaco-Aston-Villa-January-21-2025-Champions-League',
 'https://fbref.com/en/matches/99c3796e/Liverpool-Lille-January-21-2025-Champions-League',
 'https://fbref.com/en/matches/b72a4588/Benfica-Barcelona-January-21-2025-Champions-League',
 'https://fbref.com/en/matches/d18fc520/Bologna-Dortmund-January-21-2025-Champions-League',
 'https://fbref.com/en/matches/56137f1a/Club-Brugge-Juventus-January-21-2025-Champions-League',
 'https://fbref.com/en/matches/753c8418/Red-Star-Belgrade-PSV-Eindhoven-January-21-2025-Champions-League',
 'https://fbref.com/en/matches/c0617888/Slovan-Bratislava-Stuttgart-January-21-2025-Champions-League',
 'https://fbref.com/en/matches/1db7242e/Atletico-Madrid-Bayer-Leverkusen-January-21-2025-Champions-League',
 'https://fbref.com/en/matches/ccdff5cf/RB-Leipzig-Sporting-CP-January-22-2025-Champions-League',
 'https://fbref.com/en/matches/84478d9e/Shakhtar-Donetsk-Brest-January-22-2025-Champions-League',
 'https://fbref.com/en/matches/99da618c/Arsenal-Dinamo-Zagreb-January-22-2025-Champions-League',
 'https://fbref.com/en/matches/893e3e53/Celtic-Young-Boys-January-22-2025-Champions-League',
 'https://fbref.com/en/matches/392ed912/Real-Madrid-Red-Bull-Salzburg-January-22-2025-Champions-League',
 'https://fbref.com/en/matches/f10cc3c6/Milan-Girona-January-22-2025-Champions-League',
 'https://fbref.com/en/matches/f60939a2/Paris-Saint-Germain-Manchester-City-January-22-2025-Champions-League',
 'https://fbref.com/en/matches/8a6b0026/Sparta-Prague-Internazionale-January-22-2025-Champions-League',
 'https://fbref.com/en/matches/24be9d81/Feyenoord-Bayern-Munich-January-22-2025-Champions-League',
 'https://fbref.com/en/matches/85437667/Manchester-City-Club-Brugge-January-29-2025-Champions-League',
 'https://fbref.com/en/matches/25e58fe8/Aston-Villa-Celtic-January-29-2025-Champions-League',
 'https://fbref.com/en/matches/49c46c78/Sporting-CP-Bologna-January-29-2025-Champions-League',
 'https://fbref.com/en/matches/e44e7126/Bayern-Munich-Slovan-Bratislava-January-29-2025-Champions-League',
 'https://fbref.com/en/matches/2505e711/Juventus-Benfica-January-29-2025-Champions-League',
 'https://fbref.com/en/matches/7fd1f0e9/Barcelona-Atalanta-January-29-2025-Champions-League',
 'https://fbref.com/en/matches/6afd7012/Dortmund-Shakhtar-Donetsk-January-29-2025-Champions-League',
 'https://fbref.com/en/matches/12d6e866/Brest-Real-Madrid-January-29-2025-Champions-League',
 'https://fbref.com/en/matches/9c6b4eca/PSV-Eindhoven-Liverpool-January-29-2025-Champions-League',
 'https://fbref.com/en/matches/9d8d169c/Internazionale-Monaco-January-29-2025-Champions-League',
 'https://fbref.com/en/matches/9dc1db6f/Bayer-Leverkusen-Sparta-Prague-January-29-2025-Champions-League',
 'https://fbref.com/en/matches/438254ac/Stuttgart-Paris-Saint-Germain-January-29-2025-Champions-League',
 'https://fbref.com/en/matches/39998098/Lille-Feyenoord-January-29-2025-Champions-League',
 'https://fbref.com/en/matches/30a931ba/Sturm-Graz-RB-Leipzig-January-29-2025-Champions-League',
 'https://fbref.com/en/matches/d385302d/Young-Boys-Red-Star-Belgrade-January-29-2025-Champions-League',
 'https://fbref.com/en/matches/d7d20b67/Girona-Arsenal-January-29-2025-Champions-League',
 'https://fbref.com/en/matches/e54e9914/Dinamo-Zagreb-Milan-January-29-2025-Champions-League',
 'https://fbref.com/en/matches/48d705ae/Red-Bull-Salzburg-Atletico-Madrid-January-29-2025-Champions-League']

In [ ]:
league_phase = df1[pd.to_numeric(df1['Wk'], errors='coerce') <= 9]

In [ ]:
gladbach = df1[(df1['Home'] == 'Gladbach') | (df1['Away'] == 'Gladbach')]
lista_gladbach = gladbach['URL'].to_list()