<a href="https://colab.research.google.com/github/guilhermefrrr/ucl2425/blob/main/Python%20notebooks/extracting_fixtures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from google.colab import drive

In [2]:
pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_columns', None)  # Show all columns

In [3]:
df = pd.read_html('https://fbref.com/en/comps/8/schedule/Champions-League-Scores-and-Fixtures', attrs={"id": "sched_all"})[0]

In [4]:
df['Home'] = df['Home'].str.replace(r'\s[a-zA-Z]{2,3}$', '', regex=True, case=False)
df['Away'] = df['Away'].str.replace(r'^[a-zA-Z]{2,3}\s', '', regex=True, case=False)

In [5]:
df = df.drop(columns=['Match Report'])
df = df.drop(columns=['Notes'])

In [6]:
df = df.dropna(subset=['Score'])

In [7]:
df = df.rename(columns={'Wk': 'MD'})
df = df[df['Score'] != 'Score']

In [8]:
df['MD'] = pd.to_numeric(df['MD'], errors='coerce')

In [9]:
df

,Round,MD,Day,Date,Time,Home,xG,Score,xG.1,Away,Attendance,Venue,Referee
0,League phase,1.0,Tue,2024-09-17,18:45,Young Boys,0.6,0–3,2.0,Aston Villa,31500,Stadion Wankdorf,Georgi Kabakov
1,League phase,1.0,Tue,2024-09-17,18:45,Juventus,2.9,3–1,1.0,PSV Eindhoven,40417,Allianz Stadium,Alejandro Hernández
2,League phase,1.0,Tue,2024-09-17,20:00,Sporting CP,1.6,2–0,0.4,Lille,40024,Estádio José Alvalade,Donatas Rumšas
3,League phase,1.0,Tue,2024-09-17,21:00,Real Madrid,2.6,3–1,1.9,Stuttgart,71288,Estadio Santiago Bernabéu,Halil Umut Meler
4,League phase,1.0,Tue,2024-09-17,21:00,Milan,0.6,1–3,3.1,Liverpool,59826,Stadio Giuseppe Meazza,Espen Eskås
5,League phase,1.0,Tue,2024-09-17,21:00,Bayern Munich,5.9,9–2,0.7,Dinamo Zagreb,75000,Allianz Arena,Juan Martínez
6,League phase,1.0,Wed,2024-09-18,18:45,Sparta Prague,2.5,3–0,0.6,RB Salzburg,17612,epet Arena,Rade Obrenović
7,League phase,1.0,Wed,2024-09-18,18:45,Bologna,1.2,0–0,0.9,Shakhtar,23130,Stadio Renato Dall'Ara,Rohit Saggi
8,League phase,1.0,Wed,2024-09-18,20:00,Celtic,3.8,5–1,0.5,Slovan Bratislava,56826,Celtic Park,Danny Makkelie
9,League phase,1.0,Wed,2024-09-18,20:00,Manchester City,2.3,0–0,0.7,Inter,50922,Etihad Stadium,Glenn Nyberg
10,League phase,1.0,Wed,2024-09-18,21:00,Club Brugge,1.2,0–3,1.9,Dortmund,19961,Jan Breydelstadion,Irfan Peljto
11,League phase,1.0,Wed,2024-09-18,21:00,Paris S-G,2.1,1–0,0.2,Girona,39951,Parc des Princes,Daniel Siebert
12,League phase,1.0,Thu,2024-09-19,18:45,Red Star,1.0,1–2,1.3,Benfica,44238,Stadion Rajko Mitić,Michael Oliver
13,League phase,1.0,Thu,2024-09-19,18:45,Feyenoord,0.8,0–4,1.7,Leverkusen,42297,Stadion Feijenoord,Davide Massa
14,League phase,1.0,Thu,2024-09-19,21:00,Monaco,1.3,2–1,0.4,Barcelona,13296,Stade Louis II,Allard Lindhout
15,League phase,1.0,Thu,2024-09-19,21:00,Atalanta,1.2,0–0,0.8,Arsenal,22858,Gewiss Stadium,Clément Turpin
16,League phase,1.0,Thu,2024-09-19,21:00,Brest,2.1,2–1,0.5,Sturm Graz,14518,Stade du Roudourou,Nick Walsh
17,League phase,1.0,Thu,2024-09-19,21:00,Atlético Madrid,1.7,2–1,0.7,RB Leipzig,57856,Riyadh Air Metropolitan Stadium,Ivan Kružliak
19,League phase,2.0,Tue,2024-10-01,18:45,Stuttgart,1.7,1–1,1.0,Sparta Prague,60000,MHPArena,Manfredas Lukjančukas
20,League phase,2.0,Tue,2024-10-01,18:45,RB Salzburg,1.6,0–4,2.0,Brest,20232,Red Bull Arena,Anthony Taylor
21,League phase,2.0,Tue,2024-10-01,20:00,Arsenal,0.7,2–0,0.4,Paris S-G,60103,Emirates Stadium,Slavko Vinčič
22,League phase,2.0,Tue,2024-10-01,21:00,Barcelona,3.4,5–0,0.8,Young Boys,45097,Estadi Olímpic Lluís Companys,Erik Lambrechts
23,League phase,2.0,Tue,2024-10-01,21:00,Dortmund,2.6,7–1,2.1,Celtic,81365,Signal Iduna Park,Jose Maria Sánchez
24,League phase,2.0,Tue,2024-10-01,21:00,Inter,2.8,4–0,0.5,Red Star,56391,Stadio Giuseppe Meazza,Felix Zwayer
25,League phase,2.0,Tue,2024-10-01,21:00,Slovan Bratislava,0.1,0–4,3.7,Manchester City,22500,Štadión Tehelné pole,Davide Massa
26,League phase,2.0,Tue,2024-10-01,21:00,PSV Eindhoven,2.6,1–1,1.3,Sporting CP,34400,Philips Stadion,Marco Guida
27,League phase,2.0,Tue,2024-10-01,21:00,Leverkusen,1.8,1–0,1.0,Milan,30210,BayArena,Sandro Schärer
28,League phase,2.0,Wed,2024-10-02,18:45,Girona,2.2,2–3,1.9,Feyenoord,8752,Estadi Municipal de Montilivi,Urs Schnyder
29,League phase,2.0,Wed,2024-10-02,18:45,Shakhtar,0.3,0–3,2.6,Atalanta,21636,Veltins-Arena,João Pinheiro
30,League phase,2.0,Wed,2024-10-02,20:00,Liverpool,1.2,2–0,0.6,Bologna,59816,Anfield,Nikola Dabanović
31,League phase,2.0,Wed,2024-10-02,20:00,Aston Villa,0.4,1–0,1.5,Bayern Munich,38991,Villa Park,Radu Petrescu
32,League phase,2.0,Wed,2024-10-02,20:00,Benfica,4.4,4–0,0.2,Atlético Madrid,62028,Estádio do Sport Lisboa e Benfica,Serdar Gözübüyük
33,League phase,2.0,Wed,2024-10-02,21:00,Dinamo Zagreb,1.0,2–2,1.9,Monaco,12462,Stadion Maksimir,Harm Osmers
34,League phase,2.0,Wed,2024-10-02,21:00,RB Leipzig,3.3,2–3,1.2,Juventus,45228,Red Bull Arena,François Letexier
35,League phase,2.0,Wed,2024-10-02,21:00,Sturm Graz,0.4,0–1,0.7,Club Brugge,23205,Merkur Arena,Əliyar Ağayev
36,League phase,2.0,Wed,2024-10-02,21:00,Lille,1.1,1–0,2.0,Real Madrid,48205,Decathlon Arena - Stade Pierre-Mauroy,Maurizio Mariani
38,League phase,3.0,Tue,2024-10-22,18:45,Monaco,3.3,5–1,1.0,Red Star,9590,Stade Louis II,Tobias Stieler
39,League phase,3.0,Tue,2024-10-22,18:45,Milan,1.2,3–1,0.6,Club Brugge,58649,Stadio Giuseppe Meazza,Felix Zwayer
40,League phase,3.0,Tue,2024-10-22,20:00,Arsenal,1.8,1–0,0.7,Shakhtar,59594,Emirates Stadium,Benoît Bastien
41,League phase,3.0,Tue,2024-10-22,20:00,Aston Villa,1.2,2–0,0.9,Bologna,41847,Villa Park,João Pinheiro
42,League phase,3.0,Tue,2024-10-22,21:00,Sturm Graz,0.7,0–2,1.4,Sporting CP,23691,Merkur Arena,Giorgi Kruashvili
43,League phase,3.0,Tue,2024-10-22,21:00,Juventus,0.2,0–1,2.5,Stuttgart,41306,Allianz Stadium,Espen Eskås
44,League phase,3.0,Tue,2024-10-22,21:00,Real Madrid,3.5,5–2,1.6,Dortmund,74642,Estadio Santiago Bernabéu,István Kovács
45,League phase,3.0,Tue,2024-10-22,21:00,Girona,1.7,2–0,0.5,Slovan Bratislava,9246,Estadi Municipal de Montilivi,Horațiu Fesnic
46,League phase,3.0,Tue,2024-10-22,21:00,Paris S-G,2.5,1–1,0.2,PSV Eindhoven,47511,Parc des Princes,Glenn Nyberg
47,League phase,3.0,Wed,2024-10-23,18:45,Brest,0.5,1–1,1.0,Leverkusen,15510,Stade du Roudourou,Ivan Kružliak
48,League phase,3.0,Wed,2024-10-23,18:45,Atalanta,2.4,0–0,0.3,Celtic,21614,Gewiss Stadium,Irfan Peljto
49,League phase,3.0,Wed,2024-10-23,20:00,Benfica,1.7,1–3,1.0,Feyenoord,61687,Estádio do Sport Lisboa e Benfica,Halil Umut Meler
50,League phase,3.0,Wed,2024-10-23,20:00,Manchester City,2.9,5–0,0.2,Sparta Prague,50116,Etihad Stadium,Maurizio Mariani
51,League phase,3.0,Wed,2024-10-23,21:00,RB Salzburg,1.2,0–2,1.6,Dinamo Zagreb,24018,Red Bull Arena,Danny Makkelie
52,League phase,3.0,Wed,2024-10-23,21:00,Young Boys,0.8,0–1,3.3,Inter,31500,Stadion Wankdorf,Michael Oliver
53,League phase,3.0,Wed,2024-10-23,21:00,Barcelona,2.2,4–1,1.0,Bayern Munich,50312,Estadi Olímpic Lluís Companys,Slavko Vinčič
54,League phase,3.0,Wed,2024-10-23,21:00,Atlético Madrid,2.3,1–3,1.3,Lille,61197,Riyadh Air Metropolitan Stadium,Marco Guida
55,League phase,3.0,Wed,2024-10-23,21:00,RB Leipzig,0.8,0–1,2.3,Liverpool,45228,Red Bull Arena,Sandro Schärer
57,League phase,4.0,Tue,2024-11-05,18:45,Slovan Bratislava,1.7,1–4,1.5,Dinamo Zagreb,22132,Štadión Tehelné pole,Anthony Taylor
58,League phase,4.0,Tue,2024-11-05,18:45,PSV Eindhoven,2.0,4–0,0.8,Girona,34400,Philips Stadion,Michael Oliver
59,League phase,4.0,Tue,2024-11-05,20:00,Sporting CP,2.9,4–1,2.1,Manchester City,47453,Estádio José Alvalade,Daniel Siebert
60,League phase,4.0,Tue,2024-11-05,20:00,Liverpool,3.7,4–0,0.9,Leverkusen,59790,Anfield,Danny Makkelie
61,League phase,4.0,Tue,2024-11-05,20:00,Celtic,1.8,3–1,1.3,RB Leipzig,57551,Celtic Park,Benoît Bastien
62,League phase,4.0,Tue,2024-11-05,21:00,Bologna,0.5,0–1,0.9,Monaco,23084,Stadio Renato Dall'Ara,Əliyar Ağayev
63,League phase,4.0,Tue,2024-11-05,21:00,Real Madrid,2.6,1–3,2.5,Milan,75561,Estadio Santiago Bernabéu,Slavko Vinčič
64,League phase,4.0,Tue,2024-11-05,21:00,Lille,0.8,1–1,1.4,Juventus,48312,Decathlon Arena - Stade Pierre-Mauroy,Irfan Peljto
65,League phase,4.0,Tue,2024-11-05,21:00,Dortmund,2.0,1–0,0.4,Sturm Graz,81365,Signal Iduna Park,Erik Lambrechts
66,League phase,4.0,Wed,2024-11-06,18:45,Club Brugge,1.4,1–0,0.4,Aston Villa,23466,Jan Breydelstadion,Tobias Stieler
67,League phase,4.0,Wed,2024-11-06,19:45,Shakhtar,2.0,2–1,1.0,Young Boys,17420,Veltins-Arena,Orel Grinfeeld
68,League phase,4.0,Wed,2024-11-06,21:00,Paris S-G,2.1,1–2,0.7,Atlético Madrid,47369,Parc des Princes,Szymon Marciniak
69,League phase,4.0,Wed,2024-11-06,21:00,Bayern Munich,1.4,1–0,0.1,Benfica,75000,Allianz Arena,Davide Massa
70,League phase,4.0,Wed,2024-11-06,21:00,Red Star,0.2,2–5,3.6,Barcelona,48886,Stadion Rajko Mitić,Espen Eskås
71,League phase,4.0,Wed,2024-11-06,21:00,Sparta Prague,0.5,1–2,1.6,Brest,18033,epet Arena,Mykola Balakin
72,League phase,4.0,Wed,2024-11-06,21:00,Feyenoord,0.8,1–3,1.7,RB Salzburg,42774,Stadion Feijenoord,Donatas Rumšas
73,League phase,4.0,Wed,2024-11-06,21:00,Stuttgart,1.0,0–2,2.3,Atalanta,60000,MHPArena,Rade Obrenović
74,League phase,4.0,Wed,2024-11-06,21:00,Inter,1.1,1–0,1.8,Arsenal,75222,Stadio Giuseppe Meazza,István Kovács
76,League phase,5.0,Tue,2024-11-26,18:45,Slovan Bratislava,1.5,2–3,1.9,Milan,22500,Štadión Tehelné pole,Jose Maria Sánchez
77,League phase,5.0,Tue,2024-11-26,18:45,Sparta Prague,0.2,0–6,3.1,Atlético Madrid,18110,epet Arena,Danny Makkelie
78,League phase,5.0,Tue,2024-11-26,20:00,Manchester City,2.1,3–3,2.2,Feyenoord,47011,Etihad Stadium,Radu Petrescu
79,League phase,5.0,Tue,2024-11-26,20:00,Sporting CP,1.0,1–5,4.0,Arsenal,47386,Estádio José Alvalade,Szymon Marciniak
80,League phase,5.0,Tue,2024-11-26,21:00,Barcelona,2.8,3–0,0.1,Brest,46317,Estadi Olímpic Lluís Companys,Irfan Peljto
81,League phase,5.0,Tue,2024-11-26,21:00,Leverkusen,4.3,5–0,0.3,RB Salzburg,29211,BayArena,Mykola Balakin
82,League phase,5.0,Tue,2024-11-26,21:00,Inter,1.4,1–0,0.1,RB Leipzig,63174,Stadio Giuseppe Meazza,João Pinheiro
83,League phase,5.0,Tue,2024-11-26,21:00,Bayern Munich,2.4,1–0,0.8,Paris S-G,75000,Allianz Arena,István Kovács
84,League phase,5.0,Tue,2024-11-26,21:00,Young Boys,0.8,1–6,2.5,Atalanta,31500,Stadion Wankdorf,Manfredas Lukjančukas
85,League phase,5.0,Wed,2024-11-27,18:45,Red Star,1.8,5–1,0.6,Stuttgart,41372,Stadion Rajko Mitić,Erik Lambrechts
86,League phase,5.0,Wed,2024-11-27,18:45,Sturm Graz,0.8,1–0,1.7,Girona,21502,Merkur Arena,Rohit Saggi
87,League phase,5.0,Wed,2024-11-27,20:00,Aston Villa,1.2,0–0,0.4,Juventus,42589,Villa Park,Jesús Gil
88,League phase,5.0,Wed,2024-11-27,20:00,Liverpool,2.7,2–0,1.2,Real Madrid,59546,Anfield,François Letexier
89,League phase,5.0,Wed,2024-11-27,20:00,Celtic,1.0,1–1,1.1,Club Brugge,57456,Celtic Park,Georgi Kabakov
90,League phase,5.0,Wed,2024-11-27,21:00,PSV Eindhoven,2.6,3–2,1.0,Shakhtar,35100,Philips Stadion,Urs Schnyder
91,League phase,5.0,Wed,2024-11-27,21:00,Bologna,1.7,1–2,2.1,Lille,22420,Stadio Renato Dall'Ara,Michael Oliver
92,League phase,5.0,Wed,2024-11-27,21:00,Dinamo Zagreb,0.2,0–3,1.7,Dortmund,20019,Stadion Maksimir,Clément Turpin
93,League phase,5.0,Wed,2024-11-27,21:00,Monaco,1.6,2–3,3.0,Benfica,13581,Stade Louis II,Rade Obrenović
95,League phase,6.0,Tue,2024-12-10,18:45,Dinamo Zagreb,0.5,0–0,0.4,Celtic,18158,Stadion Maksimir,Felix Zwayer
96,League phase,6.0,Tue,2024-12-10,18:45,Girona,1.2,0–1,1.8,Liverpool,9241,Estadi Municipal de Montilivi,Benoît Bastien
97,League phase,6.0,Tue,2024-12-10,21:00,Leverkusen,1.1,1–0,0.3,Inter,30210,BayArena,Slavko Vinčič
98,League phase,6.0,Tue,2024-12-10,21:00,Brest,1.6,1–0,1.6,PSV Eindhoven,15778,Stade du Roudourou,Jose Maria Sánchez
99,League phase,6.0,Tue,2024-12-10,21:00,Club Brugge,1.0,2–1,1.2,Sporting CP,22254,Jan Breydelstadion,Anthony Taylor
100,League phase,6.0,Tue,2024-12-10,21:00,RB Salzburg,0.2,0–3,3.2,Paris S-G,25065,Red Bull Arena,Michael Oliver
101,League phase,6.0,Tue,2024-12-10,21:00,RB Leipzig,2.2,2–3,2.1,Aston Villa,40406,Red Bull Arena,Maurizio Mariani
102,League phase,6.0,Tue,2024-12-10,21:00,Atalanta,3.3,2–3,2.1,Real Madrid,22967,Gewiss Stadium,Szymon Marciniak
103,League phase,6.0,Tue,2024-12-10,22:00,Shakhtar,1.2,1–5,3.6,Bayern Munich,57079,Veltins-Arena,Halil Umut Meler
104,League phase,6.0,Wed,2024-12-11,18:45,Lille,2.0,3–2,1.3,Sturm Graz,45796,Decathlon Arena - Stade Pierre-Mauroy,Georgi Kabakov
105,League phase,6.0,Wed,2024-12-11,18:45,Atlético Madrid,2.0,3–1,1.0,Slovan Bratislava,59134,Riyadh Air Metropolitan Stadium,Manfredas Lukjančukas
106,League phase,6.0,Wed,2024-12-11,20:00,Arsenal,2.3,3–0,0.5,Monaco,60157,Emirates Stadium,Davide Massa
107,League phase,6.0,Wed,2024-12-11,20:00,Benfica,1.3,0–0,0.2,Bologna,60650,Estádio do Sport Lisboa e Benfica,Radu Petrescu
108,League phase,6.0,Wed,2024-12-11,21:00,Milan,2.0,2–1,0.4,Red Star,53717,Stadio Giuseppe Meazza,Jesús Gil
109,League phase,6.0,Wed,2024-12-11,21:00,Juventus,1.1,2–0,1.2,Manchester City,40890,Allianz Stadium,Clément Turpin
110,League phase,6.0,Wed,2024-12-11,21:00,Stuttgart,2.3,5–1,0.2,Young Boys,60000,MHPArena,Giorgi Kruashvili
111,League phase,6.0,Wed,2024-12-11,21:00,Dortmund,2.7,2–3,2.0,Barcelona,81365,Signal Iduna Park,François Letexier
112,League phase,6.0,Wed,2024-12-11,21:00,Feyenoord,1.0,4–2,0.7,Sparta Prague,45000,Stadion Feijenoord,Tobias Stieler
114,League phase,7.0,Tue,2025-01-21,18:45,Atalanta,4.9,5–0,0.8,Sturm Graz,19469,Gewiss Stadium,Donatas Rumšas
115,League phase,7.0,Tue,2025-01-21,18:45,Monaco,1.5,1–0,0.9,Aston Villa,13508,Stade Louis II,Slavko Vinčič
116,League phase,7.0,Tue,2025-01-21,20:00,Liverpool,2.5,2–1,0.5,Lille,59782,Anfield,Felix Zwayer
117,League phase,7.0,Tue,2025-01-21,20:00,Benfica,3.3,4–5,3.6,Barcelona,63225,Estádio do Sport Lisboa e Benfica,Danny Makkelie
118,League phase,7.0,Tue,2025-01-21,21:00,Bologna,2.1,2–1,1.0,Dortmund,26801,Stadio Renato Dall'Ara,Serdar Gözübüyük
119,League phase,7.0,Tue,2025-01-21,21:00,Club Brugge,0.7,0–0,0.4,Juventus,26700,Jan Breydelstadion,Benoît Bastien
120,League phase,7.0,Tue,2025-01-21,21:00,Red Star,2.6,2–3,0.8,PSV Eindhoven,36648,Stadion Rajko Mitić,István Kovács
121,League phase,7.0,Tue,2025-01-21,21:00,Slovan Bratislava,0.6,1–3,3.4,Stuttgart,22500,Štadión Tehelné pole,Chris Kavanagh
122,League phase,7.0,Tue,2025-01-21,21:00,Atlético Madrid,0.8,2–1,0.8,Leverkusen,66820,Riyadh Air Metropolitan Stadium,Davide Massa
123,League phase,7.0,Wed,2025-01-22,18:45,RB Leipzig,2.3,2–1,0.9,Sporting CP,33478,Red Bull Arena,Manfredas Lukjančukas
124,League phase,7.0,Wed,2025-01-22,19:45,Shakhtar,1.9,2–0,0.4,Brest,15282,Veltins-Arena,Sandro Schärer
125,League phase,7.0,Wed,2025-01-22,20:00,Arsenal,2.4,3–0,0.1,Dinamo Zagreb,60024,Emirates Stadium,Daniel Siebert
126,League phase,7.0,Wed,2025-01-22,20:00,Celtic,1.8,1–0,1.0,Young Boys,56544,Celtic Park,Rohit Saggi
127,League phase,7.0,Wed,2025-01-22,21:00,Real Madrid,2.8,5–1,0.4,RB Salzburg,73692,Estadio Santiago Bernabéu,Glenn Nyberg
128,League phase,7.0,Wed,2025-01-22,21:00,Milan,1.3,1–0,1.0,Girona,66030,Stadio Giuseppe Meazza,Tobias Stieler
129,League phase,7.0,Wed,2025-01-22,21:00,Paris S-G,2.8,4–2,1.7,Manchester City,47818,Parc des Princes,Szymon Marciniak
130,League phase,7.0,Wed,2025-01-22,21:00,Sparta Prague,0.4,0–1,0.9,Inter,18010,epet Arena,Alejandro Hernández
131,League phase,7.0,Wed,2025-01-22,21:00,Feyenoord,1.7,3–0,2.4,Bayern Munich,43106,Stadion Feijenoord,François Letexier
133,League phase,8.0,Wed,2025-01-29,20:00,Manchester City,2.0,3–1,1.1,Club Brugge,51237,Etihad Stadium,Jose Maria Sánchez
134,League phase,8.0,Wed,2025-01-29,20:00,Aston Villa,3.9,4–2,0.8,Celtic,42824,Villa Park,Clément Turpin
135,League phase,8.0,Wed,2025-01-29,20:00,Sporting CP,1.3,1–1,1.1,Bologna,37328,Estádio José Alvalade,Benoît Bastien
136,League phase,8.0,Wed,2025-01-29,21:00,Bayern Munich,3.7,3–1,0.9,Slovan Bratislava,75000,Allianz Arena,João Pinheiro
137,League phase,8.0,Wed,2025-01-29,21:00,Juventus,0.9,0–2,2.2,Benfica,41402,Allianz Stadium,István Kovács
138,League phase,8.0,Wed,2025-01-29,21:00,Barcelona,2.4,2–2,1.2,Atalanta,42728,Estadi Olímpic Lluís Companys,Michael Oliver
139,League phase,8.0,Wed,2025-01-29,21:00,Dortmund,2.4,3–1,0.4,Shakhtar,81365,Signal Iduna Park,Glenn Nyberg
140,League phase,8.0,Wed,2025-01-29,21:00,Brest,1.4,0–3,2.6,Real Madrid,15405,Stade du Roudourou,Espen Eskås
141,League phase,8.0,Wed,2025-01-29,21:00,PSV Eindhoven,1.3,3–2,1.6,Liverpool,35000,Philips Stadion,Tobias Stieler
142,League phase,8.0,Wed,2025-01-29,21:00,Inter,3.9,3–0,0.2,Monaco,71601,Stadio Giuseppe Meazza,Irfan Peljto
143,League phase,8.0,Wed,2025-01-29,21:00,Leverkusen,1.7,2–0,0.7,Sparta Prague,30210,BayArena,Georgi Kabakov
144,League phase,8.0,Wed,2025-01-29,21:00,Stuttgart,0.8,1–4,2.4,Paris S-G,60000,MHPArena,Davide Massa
145,League phase,8.0,Wed,2025-01-29,21:00,Lille,1.3,6–1,0.7,Feyenoord,44071,Decathlon Arena - Stade Pierre-Mauroy,Slavko Vinčič
146,League phase,8.0,Wed,2025-01-29,21:00,Sturm Graz,1.3,1–0,1.5,RB Leipzig,26851,28 Black Arena,Mykola Balakin
147,League phase,8.0,Wed,2025-01-29,21:00,Young Boys,0.4,0–1,1.8,Red Star,31500,Stadion Wankdorf,Halil Umut Meler
148,League phase,8.0,Wed,2025-01-29,21:00,Girona,0.7,1–2,2.1,Arsenal,9048,Estadi Municipal de Montilivi,Maurizio Mariani
149,League phase,8.0,Wed,2025-01-29,21:00,Dinamo Zagreb,1.4,2–1,1.1,Milan,18856,Stadion Maksimir,François Letexier
150,League phase,8.0,Wed,2025-01-29,21:00,RB Salzburg,0.6,1–4,2.1,Atlético Madrid,23389,Red Bull Arena,Anthony Taylor
152,Knockout phase play-offs,NaN,Tue,2025-02-11,18:45,Brest,0.9,0–3,2.6,Paris S-G,15831,Stade du Roudourou,Irfan Peljto
153,Knockout phase play-offs,NaN,Tue,2025-02-11,20:00,Manchester City,1.5,2–3,3.2,Real Madrid,52081,Etihad Stadium,Clément Turpin
154,Knockout phase play-offs,NaN,Tue,2025-02-11,20:00,Sporting CP,0.7,0–3,1.8,Dortmund,41543,Estádio José Alvalade,Espen Eskås
155,Knockout phase play-offs,NaN,Tue,2025-02-11,21:00,Juventus,1.4,2–1,0.8,PSV Eindhoven,39886,Allianz Stadium,Daniel Siebert
156,Knockout phase play-offs,NaN,Wed,2025-02-12,18:45,Club Brugge,1.4,2–1,1.0,Atalanta,24242,Jan Breydelstadion,Halil Umut Meler
157,Knockout phase play-offs,NaN,Wed,2025-02-12,20:00,Celtic,1.3,1–2,0.7,Bayern Munich,57406,Celtic Park,Jesús Gil
158,Knockout phase play-offs,NaN,Wed,2025-02-12,21:00,Monaco,0.4,0–1,2.1,Benfica,12159,Stade Louis II,Maurizio Mariani
159,Knockout phase play-offs,NaN,Wed,2025-02-12,21:00,Feyenoord,0.5,1–0,0.6,Milan,45000,Stadion Feijenoord,Jose Maria Sánchez
160,Knockout phase play-offs,NaN,Tue,2025-02-18,18:45,Milan,1.7,1–1,0.9,Feyenoord,54749,Stadio Giuseppe Meazza,Szymon Marciniak
161,Knockout phase play-offs,NaN,Tue,2025-02-18,20:00,Benfica,1.9,3–3,1.5,Monaco,60776,Estádio do Sport Lisboa e Benfica,Glenn Nyberg
162,Knockout phase play-offs,NaN,Tue,2025-02-18,21:00,Atalanta,3.1,1–3,1.1,Club Brugge,21727,Gewiss Stadium,Felix Zwayer
163,Knockout phase play-offs,NaN,Tue,2025-02-18,21:00,Bayern Munich,2.3,1–1,1.3,Celtic,75000,Allianz Arena,Benoît Bastien
164,Knockout phase play-offs,NaN,Wed,2025-02-19,18:45,Dortmund,1.9,0–0,0.4,Sporting CP,80300,Signal Iduna Park,Davide Massa
165,Knockout phase play-offs,NaN,Wed,2025-02-19,21:00,Real Madrid,1.8,3–1,1.3,Manchester City,77023,Estadio Santiago Bernabéu,István Kovács
166,Knockout phase play-offs,NaN,Wed,2025-02-19,21:00,PSV Eindhoven,3.4,3–1,1.7,Juventus,35000,Philips Stadion,Slavko Vinčič
167,Knockout phase play-offs,NaN,Wed,2025-02-19,21:00,Paris S-G,3.2,7–0,0.9,Brest,47211,Parc des Princes,Michael Oliver
168,Round of 16,NaN,Tue,2025-03-04,18:45,Club Brugge,1.1,1–3,1.4,Aston Villa,26890,Jan Breydelstadion,João Pinheiro
169,Round of 16,NaN,Tue,2025-03-04,21:00,PSV Eindhoven,1.4,1–7,1.9,Arsenal,34400,Philips Stadion,Jesús Gil
170,Round of 16,NaN,Tue,2025-03-04,21:00,Real Madrid,0.7,2–1,0.2,Atlético Madrid,77261,Estadio Santiago Bernabéu,Clément Turpin
171,Round of 16,NaN,Tue,2025-03-04,21:00,Dortmund,0.3,1–1,0.9,Lille,81365,Signal Iduna Park,Jose Maria Sánchez
172,Round of 16,NaN,Wed,2025-03-05,18:45,Feyenoord,0.4,0–2,2.2,Inter,43789,Stadion Feijenoord,Espen Eskås
173,Round of 16,NaN,Wed,2025-03-05,20:00,Benfica,1.7,0–1,1.2,Barcelona,62437,Estádio do Sport Lisboa e Benfica,Felix Zwayer
174,Round of 16,NaN,Wed,2025-03-05,21:00,Bayern Munich,2.7,3–0,0.4,Leverkusen,75000,Allianz Arena,Michael Oliver
175,Round of 16,NaN,Wed,2025-03-05,21:00,Paris S-G,1.6,0–1,0.3,Liverpool,47511,Parc des Princes,Davide Massa
176,Round of 16,NaN,Tue,2025-03-11,18:45,Barcelona,2.4,3–1,0.7,Benfica,47111,Estadi Olímpic Lluís Companys,François Letexier
178,Round of 16,NaN,Tue,2025-03-11,20:00,Liverpool,1.5,(1) 0–1 (4),2.6,Paris S-G,59765,Anfield,István Kovács
179,Round of 16,NaN,Tue,2025-03-11,21:00,Inter,2.1,2–1,1.5,Feyenoord,55536,Stadio Giuseppe Meazza,Ivan Kružliak
180,Round of 16,NaN,Tue,2025-03-11,21:00,Leverkusen,1.4,0–2,2.3,Bayern Munich,30210,BayArena,Slavko Vinčič
181,Round of 16,NaN,Wed,2025-03-12,18:45,Lille,1.2,1–2,3.0,Dortmund,48042,Decathlon Arena - Stade Pierre-Mauroy,Sandro Schärer

In [10]:
df.insert(df.columns.get_loc('MD') + 1, 'Match_ID', range(1, len(df) + 1))

In [11]:
# Split the 'Score' column
df[['Score_Home', 'Score_Away']] = df['Score'].str.split('–', expand=True)

In [12]:
score_index = df.columns.get_loc('Score')
df.insert(score_index, 'Score_Home', df.pop('Score_Home'))  # Move 'Score_Home'
df.insert(score_index + 1, 'Score_Away', df.pop('Score_Away')) # Move 'Score_Away'
df = df.drop(columns=['Score'])  # Remove 'Score'

In [13]:
df = df.rename(columns={'xG': 'xG_Home', 'xG.1': 'xG_Away'})

In [14]:
df

,Round,MD,Match_ID,Day,Date,Time,Home,xG_Home,Score_Home,Score_Away,xG_Away,Away,Attendance,Venue,Referee
0,League phase,1.0,1,Tue,2024-09-17,18:45,Young Boys,0.6,0,3,2.0,Aston Villa,31500,Stadion Wankdorf,Georgi Kabakov
1,League phase,1.0,2,Tue,2024-09-17,18:45,Juventus,2.9,3,1,1.0,PSV Eindhoven,40417,Allianz Stadium,Alejandro Hernández
2,League phase,1.0,3,Tue,2024-09-17,20:00,Sporting CP,1.6,2,0,0.4,Lille,40024,Estádio José Alvalade,Donatas Rumšas
3,League phase,1.0,4,Tue,2024-09-17,21:00,Real Madrid,2.6,3,1,1.9,Stuttgart,71288,Estadio Santiago Bernabéu,Halil Umut Meler
4,League phase,1.0,5,Tue,2024-09-17,21:00,Milan,0.6,1,3,3.1,Liverpool,59826,Stadio Giuseppe Meazza,Espen Eskås
5,League phase,1.0,6,Tue,2024-09-17,21:00,Bayern Munich,5.9,9,2,0.7,Dinamo Zagreb,75000,Allianz Arena,Juan Martínez
6,League phase,1.0,7,Wed,2024-09-18,18:45,Sparta Prague,2.5,3,0,0.6,RB Salzburg,17612,epet Arena,Rade Obrenović
7,League phase,1.0,8,Wed,2024-09-18,18:45,Bologna,1.2,0,0,0.9,Shakhtar,23130,Stadio Renato Dall'Ara,Rohit Saggi
8,League phase,1.0,9,Wed,2024-09-18,20:00,Celtic,3.8,5,1,0.5,Slovan Bratislava,56826,Celtic Park,Danny Makkelie
9,League phase,1.0,10,Wed,2024-09-18,20:00,Manchester City,2.3,0,0,0.7,Inter,50922,Etihad Stadium,Glenn Nyberg
10,League phase,1.0,11,Wed,2024-09-18,21:00,Club Brugge,1.2,0,3,1.9,Dortmund,19961,Jan Breydelstadion,Irfan Peljto
11,League phase,1.0,12,Wed,2024-09-18,21:00,Paris S-G,2.1,1,0,0.2,Girona,39951,Parc des Princes,Daniel Siebert
12,League phase,1.0,13,Thu,2024-09-19,18:45,Red Star,1.0,1,2,1.3,Benfica,44238,Stadion Rajko Mitić,Michael Oliver
13,League phase,1.0,14,Thu,2024-09-19,18:45,Feyenoord,0.8,0,4,1.7,Leverkusen,42297,Stadion Feijenoord,Davide Massa
14,League phase,1.0,15,Thu,2024-09-19,21:00,Monaco,1.3,2,1,0.4,Barcelona,13296,Stade Louis II,Allard Lindhout
15,League phase,1.0,16,Thu,2024-09-19,21:00,Atalanta,1.2,0,0,0.8,Arsenal,22858,Gewiss Stadium,Clément Turpin
16,League phase,1.0,17,Thu,2024-09-19,21:00,Brest,2.1,2,1,0.5,Sturm Graz,14518,Stade du Roudourou,Nick Walsh
17,League phase,1.0,18,Thu,2024-09-19,21:00,Atlético Madrid,1.7,2,1,0.7,RB Leipzig,57856,Riyadh Air Metropolitan Stadium,Ivan Kružliak
19,League phase,2.0,19,Tue,2024-10-01,18:45,Stuttgart,1.7,1,1,1.0,Sparta Prague,60000,MHPArena,Manfredas Lukjančukas
20,League phase,2.0,20,Tue,2024-10-01,18:45,RB Salzburg,1.6,0,4,2.0,Brest,20232,Red Bull Arena,Anthony Taylor
21,League phase,2.0,21,Tue,2024-10-01,20:00,Arsenal,0.7,2,0,0.4,Paris S-G,60103,Emirates Stadium,Slavko Vinčič
22,League phase,2.0,22,Tue,2024-10-01,21:00,Barcelona,3.4,5,0,0.8,Young Boys,45097,Estadi Olímpic Lluís Companys,Erik Lambrechts
23,League phase,2.0,23,Tue,2024-10-01,21:00,Dortmund,2.6,7,1,2.1,Celtic,81365,Signal Iduna Park,Jose Maria Sánchez
24,League phase,2.0,24,Tue,2024-10-01,21:00,Inter,2.8,4,0,0.5,Red Star,56391,Stadio Giuseppe Meazza,Felix Zwayer
25,League phase,2.0,25,Tue,2024-10-01,21:00,Slovan Bratislava,0.1,0,4,3.7,Manchester City,22500,Štadión Tehelné pole,Davide Massa
26,League phase,2.0,26,Tue,2024-10-01,21:00,PSV Eindhoven,2.6,1,1,1.3,Sporting CP,34400,Philips Stadion,Marco Guida
27,League phase,2.0,27,Tue,2024-10-01,21:00,Leverkusen,1.8,1,0,1.0,Milan,30210,BayArena,Sandro Schärer
28,League phase,2.0,28,Wed,2024-10-02,18:45,Girona,2.2,2,3,1.9,Feyenoord,8752,Estadi Municipal de Montilivi,Urs Schnyder
29,League phase,2.0,29,Wed,2024-10-02,18:45,Shakhtar,0.3,0,3,2.6,Atalanta,21636,Veltins-Arena,João Pinheiro
30,League phase,2.0,30,Wed,2024-10-02,20:00,Liverpool,1.2,2,0,0.6,Bologna,59816,Anfield,Nikola Dabanović
31,League phase,2.0,31,Wed,2024-10-02,20:00,Aston Villa,0.4,1,0,1.5,Bayern Munich,38991,Villa Park,Radu Petrescu
32,League phase,2.0,32,Wed,2024-10-02,20:00,Benfica,4.4,4,0,0.2,Atlético Madrid,62028,Estádio do Sport Lisboa e Benfica,Serdar Gözübüyük
33,League phase,2.0,33,Wed,2024-10-02,21:00,Dinamo Zagreb,1.0,2,2,1.9,Monaco,12462,Stadion Maksimir,Harm Osmers
34,League phase,2.0,34,Wed,2024-10-02,21:00,RB Leipzig,3.3,2,3,1.2,Juventus,45228,Red Bull Arena,François Letexier
35,League phase,2.0,35,Wed,2024-10-02,21:00,Sturm Graz,0.4,0,1,0.7,Club Brugge,23205,Merkur Arena,Əliyar Ağayev
36,League phase,2.0,36,Wed,2024-10-02,21:00,Lille,1.1,1,0,2.0,Real Madrid,48205,Decathlon Arena - Stade Pierre-Mauroy,Maurizio Mariani
38,League phase,3.0,37,Tue,2024-10-22,18:45,Monaco,3.3,5,1,1.0,Red Star,9590,Stade Louis II,Tobias Stieler
39,League phase,3.0,38,Tue,2024-10-22,18:45,Milan,1.2,3,1,0.6,Club Brugge,58649,Stadio Giuseppe Meazza,Felix Zwayer
40,League phase,3.0,39,Tue,2024-10-22,20:00,Arsenal,1.8,1,0,0.7,Shakhtar,59594,Emirates Stadium,Benoît Bastien
41,League phase,3.0,40,Tue,2024-10-22,20:00,Aston Villa,1.2,2,0,0.9,Bologna,41847,Villa Park,João Pinheiro
42,League phase,3.0,41,Tue,2024-10-22,21:00,Sturm Graz,0.7,0,2,1.4,Sporting CP,23691,Merkur Arena,Giorgi Kruashvili
43,League phase,3.0,42,Tue,2024-10-22,21:00,Juventus,0.2,0,1,2.5,Stuttgart,41306,Allianz Stadium,Espen Eskås
44,League phase,3.0,43,Tue,2024-10-22,21:00,Real Madrid,3.5,5,2,1.6,Dortmund,74642,Estadio Santiago Bernabéu,István Kovács
45,League phase,3.0,44,Tue,2024-10-22,21:00,Girona,1.7,2,0,0.5,Slovan Bratislava,9246,Estadi Municipal de Montilivi,Horațiu Fesnic
46,League phase,3.0,45,Tue,2024-10-22,21:00,Paris S-G,2.5,1,1,0.2,PSV Eindhoven,47511,Parc des Princes,Glenn Nyberg
47,League phase,3.0,46,Wed,2024-10-23,18:45,Brest,0.5,1,1,1.0,Leverkusen,15510,Stade du Roudourou,Ivan Kružliak
48,League phase,3.0,47,Wed,2024-10-23,18:45,Atalanta,2.4,0,0,0.3,Celtic,21614,Gewiss Stadium,Irfan Peljto
49,League phase,3.0,48,Wed,2024-10-23,20:00,Benfica,1.7,1,3,1.0,Feyenoord,61687,Estádio do Sport Lisboa e Benfica,Halil Umut Meler
50,League phase,3.0,49,Wed,2024-10-23,20:00,Manchester City,2.9,5,0,0.2,Sparta Prague,50116,Etihad Stadium,Maurizio Mariani
51,League phase,3.0,50,Wed,2024-10-23,21:00,RB Salzburg,1.2,0,2,1.6,Dinamo Zagreb,24018,Red Bull Arena,Danny Makkelie
52,League phase,3.0,51,Wed,2024-10-23,21:00,Young Boys,0.8,0,1,3.3,Inter,31500,Stadion Wankdorf,Michael Oliver
53,League phase,3.0,52,Wed,2024-10-23,21:00,Barcelona,2.2,4,1,1.0,Bayern Munich,50312,Estadi Olímpic Lluís Companys,Slavko Vinčič
54,League phase,3.0,53,Wed,2024-10-23,21:00,Atlético Madrid,2.3,1,3,1.3,Lille,61197,Riyadh Air Metropolitan Stadium,Marco Guida
55,League phase,3.0,54,Wed,2024-10-23,21:00,RB Leipzig,0.8,0,1,2.3,Liverpool,45228,Red Bull Arena,Sandro Schärer
57,League phase,4.0,55,Tue,2024-11-05,18:45,Slovan Bratislava,1.7,1,4,1.5,Dinamo Zagreb,22132,Štadión Tehelné pole,Anthony Taylor
58,League phase,4.0,56,Tue,2024-11-05,18:45,PSV Eindhoven,2.0,4,0,0.8,Girona,34400,Philips Stadion,Michael Oliver
59,League phase,4.0,57,Tue,2024-11-05,20:00,Sporting CP,2.9,4,1,2.1,Manchester City,47453,Estádio José Alvalade,Daniel Siebert
60,League phase,4.0,58,Tue,2024-11-05,20:00,Liverpool,3.7,4,0,0.9,Leverkusen,59790,Anfield,Danny Makkelie
61,League phase,4.0,59,Tue,2024-11-05,20:00,Celtic,1.8,3,1,1.3,RB Leipzig,57551,Celtic Park,Benoît Bastien
62,League phase,4.0,60,Tue,2024-11-05,21:00,Bologna,0.5,0,1,0.9,Monaco,23084,Stadio Renato Dall'Ara,Əliyar Ağayev
63,League phase,4.0,61,Tue,2024-11-05,21:00,Real Madrid,2.6,1,3,2.5,Milan,75561,Estadio Santiago Bernabéu,Slavko Vinčič
64,League phase,4.0,62,Tue,2024-11-05,21:00,Lille,0.8,1,1,1.4,Juventus,48312,Decathlon Arena - Stade Pierre-Mauroy,Irfan Peljto
65,League phase,4.0,63,Tue,2024-11-05,21:00,Dortmund,2.0,1,0,0.4,Sturm Graz,81365,Signal Iduna Park,Erik Lambrechts
66,League phase,4.0,64,Wed,2024-11-06,18:45,Club Brugge,1.4,1,0,0.4,Aston Villa,23466,Jan Breydelstadion,Tobias Stieler
67,League phase,4.0,65,Wed,2024-11-06,19:45,Shakhtar,2.0,2,1,1.0,Young Boys,17420,Veltins-Arena,Orel Grinfeeld
68,League phase,4.0,66,Wed,2024-11-06,21:00,Paris S-G,2.1,1,2,0.7,Atlético Madrid,47369,Parc des Princes,Szymon Marciniak
69,League phase,4.0,67,Wed,2024-11-06,21:00,Bayern Munich,1.4,1,0,0.1,Benfica,75000,Allianz Arena,Davide Massa
70,League phase,4.0,68,Wed,2024-11-06,21:00,Red Star,0.2,2,5,3.6,Barcelona,48886,Stadion Rajko Mitić,Espen Eskås
71,League phase,4.0,69,Wed,2024-11-06,21:00,Sparta Prague,0.5,1,2,1.6,Brest,18033,epet Arena,Mykola Balakin
72,League phase,4.0,70,Wed,2024-11-06,21:00,Feyenoord,0.8,1,3,1.7,RB Salzburg,42774,Stadion Feijenoord,Donatas Rumšas
73,League phase,4.0,71,Wed,2024-11-06,21:00,Stuttgart,1.0,0,2,2.3,Atalanta,60000,MHPArena,Rade Obrenović
74,League phase,4.0,72,Wed,2024-11-06,21:00,Inter,1.1,1,0,1.8,Arsenal,75222,Stadio Giuseppe Meazza,István Kovács
76,League phase,5.0,73,Tue,2024-11-26,18:45,Slovan Bratislava,1.5,2,3,1.9,Milan,22500,Štadión Tehelné pole,Jose Maria Sánchez
77,League phase,5.0,74,Tue,2024-11-26,18:45,Sparta Prague,0.2,0,6,3.1,Atlético Madrid,18110,epet Arena,Danny Makkelie
78,League phase,5.0,75,Tue,2024-11-26,20:00,Manchester City,2.1,3,3,2.2,Feyenoord,47011,Etihad Stadium,Radu Petrescu
79,League phase,5.0,76,Tue,2024-11-26,20:00,Sporting CP,1.0,1,5,4.0,Arsenal,47386,Estádio José Alvalade,Szymon Marciniak
80,League phase,5.0,77,Tue,2024-11-26,21:00,Barcelona,2.8,3,0,0.1,Brest,46317,Estadi Olímpic Lluís Companys,Irfan Peljto
81,League phase,5.0,78,Tue,2024-11-26,21:00,Leverkusen,4.3,5,0,0.3,RB Salzburg,29211,BayArena,Mykola Balakin
82,League phase,5.0,79,Tue,2024-11-26,21:00,Inter,1.4,1,0,0.1,RB Leipzig,63174,Stadio Giuseppe Meazza,João Pinheiro
83,League phase,5.0,80,Tue,2024-11-26,21:00,Bayern Munich,2.4,1,0,0.8,Paris S-G,75000,Allianz Arena,István Kovács
84,League phase,5.0,81,Tue,2024-11-26,21:00,Young Boys,0.8,1,6,2.5,Atalanta,31500,Stadion Wankdorf,Manfredas Lukjančukas
85,League phase,5.0,82,Wed,2024-11-27,18:45,Red Star,1.8,5,1,0.6,Stuttgart,41372,Stadion Rajko Mitić,Erik Lambrechts
86,League phase,5.0,83,Wed,2024-11-27,18:45,Sturm Graz,0.8,1,0,1.7,Girona,21502,Merkur Arena,Rohit Saggi
87,League phase,5.0,84,Wed,2024-11-27,20:00,Aston Villa,1.2,0,0,0.4,Juventus,42589,Villa Park,Jesús Gil
88,League phase,5.0,85,Wed,2024-11-27,20:00,Liverpool,2.7,2,0,1.2,Real Madrid,59546,Anfield,François Letexier
89,League phase,5.0,86,Wed,2024-11-27,20:00,Celtic,1.0,1,1,1.1,Club Brugge,57456,Celtic Park,Georgi Kabakov
90,League phase,5.0,87,Wed,2024-11-27,21:00,PSV Eindhoven,2.6,3,2,1.0,Shakhtar,35100,Philips Stadion,Urs Schnyder
91,League phase,5.0,88,Wed,2024-11-27,21:00,Bologna,1.7,1,2,2.1,Lille,22420,Stadio Renato Dall'Ara,Michael Oliver
92,League phase,5.0,89,Wed,2024-11-27,21:00,Dinamo Zagreb,0.2,0,3,1.7,Dortmund,20019,Stadion Maksimir,Clément Turpin
93,League phase,5.0,90,Wed,2024-11-27,21:00,Monaco,1.6,2,3,3.0,Benfica,13581,Stade Louis II,Rade Obrenović
95,League phase,6.0,91,Tue,2024-12-10,18:45,Dinamo Zagreb,0.5,0,0,0.4,Celtic,18158,Stadion Maksimir,Felix Zwayer
96,League phase,6.0,92,Tue,2024-12-10,18:45,Girona,1.2,0,1,1.8,Liverpool,9241,Estadi Municipal de Montilivi,Benoît Bastien
97,League phase,6.0,93,Tue,2024-12-10,21:00,Leverkusen,1.1,1,0,0.3,Inter,30210,BayArena,Slavko Vinčič
98,League phase,6.0,94,Tue,2024-12-10,21:00,Brest,1.6,1,0,1.6,PSV Eindhoven,15778,Stade du Roudourou,Jose Maria Sánchez
99,League phase,6.0,95,Tue,2024-12-10,21:00,Club Brugge,1.0,2,1,1.2,Sporting CP,22254,Jan Breydelstadion,Anthony Taylor
100,League phase,6.0,96,Tue,2024-12-10,21:00,RB Salzburg,0.2,0,3,3.2,Paris S-G,25065,Red Bull Arena,Michael Oliver
101,League phase,6.0,97,Tue,2024-12-10,21:00,RB Leipzig,2.2,2,3,2.1,Aston Villa,40406,Red Bull Arena,Maurizio Mariani
102,League phase,6.0,98,Tue,2024-12-10,21:00,Atalanta,3.3,2,3,2.1,Real Madrid,22967,Gewiss Stadium,Szymon Marciniak
103,League phase,6.0,99,Tue,2024-12-10,22:00,Shakhtar,1.2,1,5,3.6,Bayern Munich,57079,Veltins-Arena,Halil Umut Meler
104,League phase,6.0,100,Wed,2024-12-11,18:45,Lille,2.0,3,2,1.3,Sturm Graz,45796,Decathlon Arena - Stade Pierre-Mauroy,Georgi Kabakov
105,League phase,6.0,101,Wed,2024-12-11,18:45,Atlético Madrid,2.0,3,1,1.0,Slovan Bratislava,59134,Riyadh Air Metropolitan Stadium,Manfredas Lukjančukas
106,League phase,6.0,102,Wed,2024-12-11,20:00,Arsenal,2.3,3,0,0.5,Monaco,60157,Emirates Stadium,Davide Massa
107,League phase,6.0,103,Wed,2024-12-11,20:00,Benfica,1.3,0,0,0.2,Bologna,60650,Estádio do Sport Lisboa e Benfica,Radu Petrescu
108,League phase,6.0,104,Wed,2024-12-11,21:00,Milan,2.0,2,1,0.4,Red Star,53717,Stadio Giuseppe Meazza,Jesús Gil
109,League phase,6.0,105,Wed,2024-12-11,21:00,Juventus,1.1,2,0,1.2,Manchester City,40890,Allianz Stadium,Clément Turpin
110,League phase,6.0,106,Wed,2024-12-11,21:00,Stuttgart,2.3,5,1,0.2,Young Boys,60000,MHPArena,Giorgi Kruashvili
111,League phase,6.0,107,Wed,2024-12-11,21:00,Dortmund,2.7,2,3,2.0,Barcelona,81365,Signal Iduna Park,François Letexier
112,League phase,6.0,108,Wed,2024-12-11,21:00,Feyenoord,1.0,4,2,0.7,Sparta Prague,45000,Stadion Feijenoord,Tobias Stieler
114,League phase,7.0,109,Tue,2025-01-21,18:45,Atalanta,4.9,5,0,0.8,Sturm Graz,19469,Gewiss Stadium,Donatas Rumšas
115,League phase,7.0,110,Tue,2025-01-21,18:45,Monaco,1.5,1,0,0.9,Aston Villa,13508,Stade Louis II,Slavko Vinčič
116,League phase,7.0,111,Tue,2025-01-21,20:00,Liverpool,2.5,2,1,0.5,Lille,59782,Anfield,Felix Zwayer
117,League phase,7.0,112,Tue,2025-01-21,20:00,Benfica,3.3,4,5,3.6,Barcelona,63225,Estádio do Sport Lisboa e Benfica,Danny Makkelie
118,League phase,7.0,113,Tue,2025-01-21,21:00,Bologna,2.1,2,1,1.0,Dortmund,26801,Stadio Renato Dall'Ara,Serdar Gözübüyük
119,League phase,7.0,114,Tue,2025-01-21,21:00,Club Brugge,0.7,0,0,0.4,Juventus,26700,Jan Breydelstadion,Benoît Bastien
120,League phase,7.0,115,Tue,2025-01-21,21:00,Red Star,2.6,2,3,0.8,PSV Eindhoven,36648,Stadion Rajko Mitić,István Kovács
121,League phase,7.0,116,Tue,2025-01-21,21:00,Slovan Bratislava,0.6,1,3,3.4,Stuttgart,22500,Štadión Tehelné pole,Chris Kavanagh
122,League phase,7.0,117,Tue,2025-01-21,21:00,Atlético Madrid,0.8,2,1,0.8,Leverkusen,66820,Riyadh Air Metropolitan Stadium,Davide Massa
123,League phase,7.0,118,Wed,2025-01-22,18:45,RB Leipzig,2.3,2,1,0.9,Sporting CP,33478,Red Bull Arena,Manfredas Lukjančukas
124,League phase,7.0,119,Wed,2025-01-22,19:45,Shakhtar,1.9,2,0,0.4,Brest,15282,Veltins-Arena,Sandro Schärer
125,League phase,7.0,120,Wed,2025-01-22,20:00,Arsenal,2.4,3,0,0.1,Dinamo Zagreb,60024,Emirates Stadium,Daniel Siebert
126,League phase,7.0,121,Wed,2025-01-22,20:00,Celtic,1.8,1,0,1.0,Young Boys,56544,Celtic Park,Rohit Saggi
127,League phase,7.0,122,Wed,2025-01-22,21:00,Real Madrid,2.8,5,1,0.4,RB Salzburg,73692,Estadio Santiago Bernabéu,Glenn Nyberg
128,League phase,7.0,123,Wed,2025-01-22,21:00,Milan,1.3,1,0,1.0,Girona,66030,Stadio Giuseppe Meazza,Tobias Stieler
129,League phase,7.0,124,Wed,2025-01-22,21:00,Paris S-G,2.8,4,2,1.7,Manchester City,47818,Parc des Princes,Szymon Marciniak
130,League phase,7.0,125,Wed,2025-01-22,21:00,Sparta Prague,0.4,0,1,0.9,Inter,18010,epet Arena,Alejandro Hernández
131,League phase,7.0,126,Wed,2025-01-22,21:00,Feyenoord,1.7,3,0,2.4,Bayern Munich,43106,Stadion Feijenoord,François Letexier
133,League phase,8.0,127,Wed,2025-01-29,20:00,Manchester City,2.0,3,1,1.1,Club Brugge,51237,Etihad Stadium,Jose Maria Sánchez
134,League phase,8.0,128,Wed,2025-01-29,20:00,Aston Villa,3.9,4,2,0.8,Celtic,42824,Villa Park,Clément Turpin
135,League phase,8.0,129,Wed,2025-01-29,20:00,Sporting CP,1.3,1,1,1.1,Bologna,37328,Estádio José Alvalade,Benoît Bastien
136,League phase,8.0,130,Wed,2025-01-29,21:00,Bayern Munich,3.7,3,1,0.9,Slovan Bratislava,75000,Allianz Arena,João Pinheiro
137,League phase,8.0,131,Wed,2025-01-29,21:00,Juventus,0.9,0,2,2.2,Benfica,41402,Allianz Stadium,István Kovács
138,League phase,8.0,132,Wed,2025-01-29,21:00,Barcelona,2.4,2,2,1.2,Atalanta,42728,Estadi Olímpic Lluís Companys,Michael Oliver
139,League phase,8.0,133,Wed,2025-01-29,21:00,Dortmund,2.4,3,1,0.4,Shakhtar,81365,Signal Iduna Park,Glenn Nyberg
140,League phase,8.0,134,Wed,2025-01-29,21:00,Brest,1.4,0,3,2.6,Real Madrid,15405,Stade du Roudourou,Espen Eskås
141,League phase,8.0,135,Wed,2025-01-29,21:00,PSV Eindhoven,1.3,3,2,1.6,Liverpool,35000,Philips Stadion,Tobias Stieler
142,League phase,8.0,136,Wed,2025-01-29,21:00,Inter,3.9,3,0,0.2,Monaco,71601,Stadio Giuseppe Meazza,Irfan Peljto
143,League phase,8.0,137,Wed,2025-01-29,21:00,Leverkusen,1.7,2,0,0.7,Sparta Prague,30210,BayArena,Georgi Kabakov
144,League phase,8.0,138,Wed,2025-01-29,21:00,Stuttgart,0.8,1,4,2.4,Paris S-G,60000,MHPArena,Davide Massa
145,League phase,8.0,139,Wed,2025-01-29,21:00,Lille,1.3,6,1,0.7,Feyenoord,44071,Decathlon Arena - Stade Pierre-Mauroy,Slavko Vinčič
146,League phase,8.0,140,Wed,2025-01-29,21:00,Sturm Graz,1.3,1,0,1.5,RB Leipzig,26851,28 Black Arena,Mykola Balakin
147,League phase,8.0,141,Wed,2025-01-29,21:00,Young Boys,0.4,0,1,1.8,Red Star,31500,Stadion Wankdorf,Halil Umut Meler
148,League phase,8.0,142,Wed,2025-01-29,21:00,Girona,0.7,1,2,2.1,Arsenal,9048,Estadi Municipal de Montilivi,Maurizio Mariani
149,League phase,8.0,143,Wed,2025-01-29,21:00,Dinamo Zagreb,1.4,2,1,1.1,Milan,18856,Stadion Maksimir,François Letexier
150,League phase,8.0,144,Wed,2025-01-29,21:00,RB Salzburg,0.6,1,4,2.1,Atlético Madrid,23389,Red Bull Arena,Anthony Taylor
152,Knockout phase play-offs,NaN,145,Tue,2025-02-11,18:45,Brest,0.9,0,3,2.6,Paris S-G,15831,Stade du Roudourou,Irfan Peljto
153,Knockout phase play-offs,NaN,146,Tue,2025-02-11,20:00,Manchester City,1.5,2,3,3.2,Real Madrid,52081,Etihad Stadium,Clément Turpin
154,Knockout phase play-offs,NaN,147,Tue,2025-02-11,20:00,Sporting CP,0.7,0,3,1.8,Dortmund,41543,Estádio José Alvalade,Espen Eskås
155,Knockout phase play-offs,NaN,148,Tue,2025-02-11,21:00,Juventus,1.4,2,1,0.8,PSV Eindhoven,39886,Allianz Stadium,Daniel Siebert
156,Knockout phase play-offs,NaN,149,Wed,2025-02-12,18:45,Club Brugge,1.4,2,1,1.0,Atalanta,24242,Jan Breydelstadion,Halil Umut Meler
157,Knockout phase play-offs,NaN,150,Wed,2025-02-12,20:00,Celtic,1.3,1,2,0.7,Bayern Munich,57406,Celtic Park,Jesús Gil
158,Knockout phase play-offs,NaN,151,Wed,2025-02-12,21:00,Monaco,0.4,0,1,2.1,Benfica,12159,Stade Louis II,Maurizio Mariani
159,Knockout phase play-offs,NaN,152,Wed,2025-02-12,21:00,Feyenoord,0.5,1,0,0.6,Milan,45000,Stadion Feijenoord,Jose Maria Sánchez
160,Knockout phase play-offs,NaN,153,Tue,2025-02-18,18:45,Milan,1.7,1,1,0.9,Feyenoord,54749,Stadio Giuseppe Meazza,Szymon Marciniak
161,Knockout phase play-offs,NaN,154,Tue,2025-02-18,20:00,Benfica,1.9,3,3,1.5,Monaco,60776,Estádio do Sport Lisboa e Benfica,Glenn Nyberg
162,Knockout phase play-offs,NaN,155,Tue,2025-02-18,21:00,Atalanta,3.1,1,3,1.1,Club Brugge,21727,Gewiss Stadium,Felix Zwayer
163,Knockout phase play-offs,NaN,156,Tue,2025-02-18,21:00,Bayern Munich,2.3,1,1,1.3,Celtic,75000,Allianz Arena,Benoît Bastien
164,Knockout phase play-offs,NaN,157,Wed,2025-02-19,18:45,Dortmund,1.9,0,0,0.4,Sporting CP,80300,Signal Iduna Park,Davide Massa
165,Knockout phase play-offs,NaN,158,Wed,2025-02-19,21:00,Real Madrid,1.8,3,1,1.3,Manchester City,77023,Estadio Santiago Bernabéu,István Kovács
166,Knockout phase play-offs,NaN,159,Wed,2025-02-19,21:00,PSV Eindhoven,3.4,3,1,1.7,Juventus,35000,Philips Stadion,Slavko Vinčič
167,Knockout phase play-offs,NaN,160,Wed,2025-02-19,21:00,Paris S-G,3.2,7,0,0.9,Brest,47211,Parc des Princes,Michael Oliver
168,Round of 16,NaN,161,Tue,2025-03-04,18:45,Club Brugge,1.1,1,3,1.4,Aston Villa,26890,Jan Breydelstadion,João Pinheiro
169,Round of 16,NaN,162,Tue,2025-03-04,21:00,PSV Eindhoven,1.4,1,7,1.9,Arsenal,34400,Philips Stadion,Jesús Gil
170,Round of 16,NaN,163,Tue,2025-03-04,21:00,Real Madrid,0.7,2,1,0.2,Atlético Madrid,77261,Estadio Santiago Bernabéu,Clément Turpin
171,Round of 16,NaN,164,Tue,2025-03-04,21:00,Dortmund,0.3,1,1,0.9,Lille,81365,Signal Iduna Park,Jose Maria Sánchez
172,Round of 16,NaN,165,Wed,2025-03-05,18:45,Feyenoord,0.4,0,2,2.2,Inter,43789,Stadion Feijenoord,Espen Eskås
173,Round of 16,NaN,166,Wed,2025-03-05,20:00,Benfica,1.7,0,1,1.2,Barcelona,62437,Estádio do Sport Lisboa e Benfica,Felix Zwayer
174,Round of 16,NaN,167,Wed,2025-03-05,21:00,Bayern Munich,2.7,3,0,0.4,Leverkusen,75000,Allianz Arena,Michael Oliver
175,Round of 16,NaN,168,Wed,2025-03-05,21:00,Paris S-G,1.6,0,1,0.3,Liverpool,47511,Parc des Princes,Davide Massa

In [15]:
# Getting data from other file of this project (needed to connect to Google Drive)
df1 = pd.read_csv('/content/drive/MyDrive/Dados/Projetos/ucl_2425/Complete data/ucl2425.csv')

In [16]:
df1.head()

,MD,Match_ID,Player,Squad,#,Nation,Age_Years,Age_Days,Pos,Min,Gls,Ast,PK,PKatt,Sh,SoT,CrdY,CrdR,Touches,Tkl,Int,Blocks,xG,npxG,xAG,SCA,GCA,Passes_Cmp,Passes_Att,Passes_Cmp%,Passes_PrgP,Carries,Carries_PrgC,Take-Ons_Att,Take-Ons_Succ,Total_TotDist,Total_PrgDist,Short_Cmp,Short_Att,Short_Cmp%,Medium_Cmp,Medium_Att,Medium_Cmp%,Long_Cmp,Long_Att,Long_Cmp%,xA,KP,1/3,PPA,CrsPA,Pass Types_Live,Pass Types_Dead,Pass Types_FK,Pass Types_TB,Pass Types_Sw,Pass Types_Crs,Pass Types_TI,Pass Types_CK,Corner Kicks_In,Corner Kicks_Out,Corner Kicks_Str,Outcomes_Cmp,Outcomes_Off,Outcomes_Blocks,Tackles_TklW,Tackles_Def 3rd,Tackles_Mid 3rd,Tackles_Att 3rd,Challenges_Tkl,Challenges_Att,Challenges_Tkl%,Challenges_Lost,Blocks_Sh,Blocks_Pass,Int.1,Tkl+Int,Clr,Err,Touches_Def Pen,Touches_Def 3rd,Touches_Mid 3rd,Touches_Att 3rd,Touches_Att Pen,Take-Ons_Succ%,Take-Ons_Tkld,Take-Ons_Tkld%,Carries_TotDist,Carries_PrgDist,Carries_1/3,Carries_CPA,Carries_Mis,Carries_Dis,Rec,PrgR,2CrdY,Fls,Fld,Off,Crs,TklW,PKwon,PKcon,OG,Recov,Aerial Duels_Won,Aerial Duels_Lost,Aerial Duels_Won%
0,1,1,Abdu Conté,Young Boys,22,POR,26,177,LB,28,0,0,0,0,0,0,0,0,9,0,0,1,0.0,0.0,0.0,0,0,5,8,62.5,1,5,1,0,0,91,26,2,5,40.0,3,3,100.0,0,0,NaN,0.0,0,1,0,0,7,1,0,0,0,0,1,0,0,0,0,5,0,0,0,0,0,0,0,0,NaN,0,1,0,0,0,0,0,1,2,5,2,0,NaN,0,NaN,29,18,1,0,0,0,4,0,0,0,0,0,0,0,0,0,0,1,0,0,NaN
1,1,1,Alan Virginius,Young Boys,21,FRA,21,258,"RM,FW",28,0,0,0,0,1,0,0,0,3,0,0,0,0.0,0.0,0.0,0,0,0,0,NaN,0,2,1,0,0,0,0,0,0,NaN,0,0,NaN,0,0,NaN,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,1,0,2,1,NaN,0,NaN,17,7,0,1,0,0,2,1,0,1,0,0,0,0,0,0,0,0,0,0,NaN
2,1,1,Cedric Itten,Young Boys,9,SUI,27,265,FW,8,0,0,0,0,1,0,0,0,5,0,0,0,0.0,0.0,0.0,2,0,3,4,75.0,1,2,0,0,0,33,5,1,1,100.0,1,1,100.0,0,0,NaN,0.0,0,0,0,0,2,1,0,0,0,0,0,0,0,0,0,3,1,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,2,3,1,NaN,0,NaN,10,5,0,0,0,0,3,1,0,0,0,0,0,0,0,0,0,0,1,0,100.0
3,1,1,Cheikh Niasse,Young Boys,20,SEN,24,242,DM,45,0,0,0,0,0,0,1,0,28,1,0,0,0.0,0.0,0.0,0,0,20,25,80.0,2,20,3,2,2,342,54,9,11,81.8,6,6,100.0,3,5,60.0,0.0,0,0,0,0,25,0,0,0,0,0,0,0,0,0,0,20,0,0,0,0,1,0,1,1,100.0,0,0,0,0,1,0,0,1,5,19,5,0,100.0,0,0.0,145,103,1,0,1,2,22,2,0,1,2,0,0,0,0,0,0,2,1,0,100.0
4,1,1,Darian Males,Young Boys,39,SUI,23,137,LM,8,0,0,0,0,0,0,0,0,6,2,0,0,0.0,0.0,0.0,0,0,1,3,33.3,0,1,0,1,0,36,0,0,0,NaN,0,0,NaN,1,3,33.3,0.0,0,0,0,0,2,1,0,0,0,2,0,1,0,1,0,1,0,0,2,0,0,2,0,0,NaN,0,0,0,0,2,0,0,0,0,1,5,0,0.0,1,100.0,2,0,0,0,1,0,2,1,0,0,0,0,2,2,0,0,0,0,0,0,NaN

In [17]:
squads_df = pd.unique(df[['Home', 'Away']].values.ravel('K'))
squads_df1 = df1['Squad'].unique()

# Times em df que não estão em df1
not_in_df1 = list(set(squads_df) - set(squads_df1))

# Times em df1 que não estão em df
not_in_df = list(set(squads_df1) - set(squads_df))

print("Squads in df and out of df1:", not_in_df1)
print("Squads in df1 and out of df:", not_in_df)

Squads in df and out of df1: ['Inter', 'Leverkusen', 'Red Star', 'Shakhtar', 'RB Salzburg', 'Paris S-G']
Squads in df1 and out of df: ['Red Bull Salzburg', 'Paris Saint-Germain', 'Bayer Leverkusen', 'Shakhtar Donetsk', 'Red Star Belgrade', 'Internazionale']

In [18]:
squads_mapping = {
    'Shakhtar': 'Shakhtar Donetsk',
    'Leverkusen': 'Bayer Leverkusen',
    'Paris S-G': 'Paris Saint-Germain',
    'Red Star': 'Red Star Belgrade',
    'RB Salzburg': 'Red Bull Salzburg',
    'Inter': 'Internazionale'
}

In [19]:
df['Home'] = df['Home'].replace(squads_mapping)
df['Away'] = df['Away'].replace(squads_mapping)

In [20]:
df

,Round,MD,Match_ID,Day,Date,Time,Home,xG_Home,Score_Home,Score_Away,xG_Away,Away,Attendance,Venue,Referee
0,League phase,1.0,1,Tue,2024-09-17,18:45,Young Boys,0.6,0,3,2.0,Aston Villa,31500,Stadion Wankdorf,Georgi Kabakov
1,League phase,1.0,2,Tue,2024-09-17,18:45,Juventus,2.9,3,1,1.0,PSV Eindhoven,40417,Allianz Stadium,Alejandro Hernández
2,League phase,1.0,3,Tue,2024-09-17,20:00,Sporting CP,1.6,2,0,0.4,Lille,40024,Estádio José Alvalade,Donatas Rumšas
3,League phase,1.0,4,Tue,2024-09-17,21:00,Real Madrid,2.6,3,1,1.9,Stuttgart,71288,Estadio Santiago Bernabéu,Halil Umut Meler
4,League phase,1.0,5,Tue,2024-09-17,21:00,Milan,0.6,1,3,3.1,Liverpool,59826,Stadio Giuseppe Meazza,Espen Eskås
5,League phase,1.0,6,Tue,2024-09-17,21:00,Bayern Munich,5.9,9,2,0.7,Dinamo Zagreb,75000,Allianz Arena,Juan Martínez
6,League phase,1.0,7,Wed,2024-09-18,18:45,Sparta Prague,2.5,3,0,0.6,Red Bull Salzburg,17612,epet Arena,Rade Obrenović
7,League phase,1.0,8,Wed,2024-09-18,18:45,Bologna,1.2,0,0,0.9,Shakhtar Donetsk,23130,Stadio Renato Dall'Ara,Rohit Saggi
8,League phase,1.0,9,Wed,2024-09-18,20:00,Celtic,3.8,5,1,0.5,Slovan Bratislava,56826,Celtic Park,Danny Makkelie
9,League phase,1.0,10,Wed,2024-09-18,20:00,Manchester City,2.3,0,0,0.7,Internazionale,50922,Etihad Stadium,Glenn Nyberg
10,League phase,1.0,11,Wed,2024-09-18,21:00,Club Brugge,1.2,0,3,1.9,Dortmund,19961,Jan Breydelstadion,Irfan Peljto
11,League phase,1.0,12,Wed,2024-09-18,21:00,Paris Saint-Germain,2.1,1,0,0.2,Girona,39951,Parc des Princes,Daniel Siebert
12,League phase,1.0,13,Thu,2024-09-19,18:45,Red Star Belgrade,1.0,1,2,1.3,Benfica,44238,Stadion Rajko Mitić,Michael Oliver
13,League phase,1.0,14,Thu,2024-09-19,18:45,Feyenoord,0.8,0,4,1.7,Bayer Leverkusen,42297,Stadion Feijenoord,Davide Massa
14,League phase,1.0,15,Thu,2024-09-19,21:00,Monaco,1.3,2,1,0.4,Barcelona,13296,Stade Louis II,Allard Lindhout
15,League phase,1.0,16,Thu,2024-09-19,21:00,Atalanta,1.2,0,0,0.8,Arsenal,22858,Gewiss Stadium,Clément Turpin
16,League phase,1.0,17,Thu,2024-09-19,21:00,Brest,2.1,2,1,0.5,Sturm Graz,14518,Stade du Roudourou,Nick Walsh
17,League phase,1.0,18,Thu,2024-09-19,21:00,Atlético Madrid,1.7,2,1,0.7,RB Leipzig,57856,Riyadh Air Metropolitan Stadium,Ivan Kružliak
19,League phase,2.0,19,Tue,2024-10-01,18:45,Stuttgart,1.7,1,1,1.0,Sparta Prague,60000,MHPArena,Manfredas Lukjančukas
20,League phase,2.0,20,Tue,2024-10-01,18:45,Red Bull Salzburg,1.6,0,4,2.0,Brest,20232,Red Bull Arena,Anthony Taylor
21,League phase,2.0,21,Tue,2024-10-01,20:00,Arsenal,0.7,2,0,0.4,Paris Saint-Germain,60103,Emirates Stadium,Slavko Vinčič
22,League phase,2.0,22,Tue,2024-10-01,21:00,Barcelona,3.4,5,0,0.8,Young Boys,45097,Estadi Olímpic Lluís Companys,Erik Lambrechts
23,League phase,2.0,23,Tue,2024-10-01,21:00,Dortmund,2.6,7,1,2.1,Celtic,81365,Signal Iduna Park,Jose Maria Sánchez
24,League phase,2.0,24,Tue,2024-10-01,21:00,Internazionale,2.8,4,0,0.5,Red Star Belgrade,56391,Stadio Giuseppe Meazza,Felix Zwayer
25,League phase,2.0,25,Tue,2024-10-01,21:00,Slovan Bratislava,0.1,0,4,3.7,Manchester City,22500,Štadión Tehelné pole,Davide Massa
26,League phase,2.0,26,Tue,2024-10-01,21:00,PSV Eindhoven,2.6,1,1,1.3,Sporting CP,34400,Philips Stadion,Marco Guida
27,League phase,2.0,27,Tue,2024-10-01,21:00,Bayer Leverkusen,1.8,1,0,1.0,Milan,30210,BayArena,Sandro Schärer
28,League phase,2.0,28,Wed,2024-10-02,18:45,Girona,2.2,2,3,1.9,Feyenoord,8752,Estadi Municipal de Montilivi,Urs Schnyder
29,League phase,2.0,29,Wed,2024-10-02,18:45,Shakhtar Donetsk,0.3,0,3,2.6,Atalanta,21636,Veltins-Arena,João Pinheiro
30,League phase,2.0,30,Wed,2024-10-02,20:00,Liverpool,1.2,2,0,0.6,Bologna,59816,Anfield,Nikola Dabanović
31,League phase,2.0,31,Wed,2024-10-02,20:00,Aston Villa,0.4,1,0,1.5,Bayern Munich,38991,Villa Park,Radu Petrescu
32,League phase,2.0,32,Wed,2024-10-02,20:00,Benfica,4.4,4,0,0.2,Atlético Madrid,62028,Estádio do Sport Lisboa e Benfica,Serdar Gözübüyük
33,League phase,2.0,33,Wed,2024-10-02,21:00,Dinamo Zagreb,1.0,2,2,1.9,Monaco,12462,Stadion Maksimir,Harm Osmers
34,League phase,2.0,34,Wed,2024-10-02,21:00,RB Leipzig,3.3,2,3,1.2,Juventus,45228,Red Bull Arena,François Letexier
35,League phase,2.0,35,Wed,2024-10-02,21:00,Sturm Graz,0.4,0,1,0.7,Club Brugge,23205,Merkur Arena,Əliyar Ağayev
36,League phase,2.0,36,Wed,2024-10-02,21:00,Lille,1.1,1,0,2.0,Real Madrid,48205,Decathlon Arena - Stade Pierre-Mauroy,Maurizio Mariani
38,League phase,3.0,37,Tue,2024-10-22,18:45,Monaco,3.3,5,1,1.0,Red Star Belgrade,9590,Stade Louis II,Tobias Stieler
39,League phase,3.0,38,Tue,2024-10-22,18:45,Milan,1.2,3,1,0.6,Club Brugge,58649,Stadio Giuseppe Meazza,Felix Zwayer
40,League phase,3.0,39,Tue,2024-10-22,20:00,Arsenal,1.8,1,0,0.7,Shakhtar Donetsk,59594,Emirates Stadium,Benoît Bastien
41,League phase,3.0,40,Tue,2024-10-22,20:00,Aston Villa,1.2,2,0,0.9,Bologna,41847,Villa Park,João Pinheiro
42,League phase,3.0,41,Tue,2024-10-22,21:00,Sturm Graz,0.7,0,2,1.4,Sporting CP,23691,Merkur Arena,Giorgi Kruashvili
43,League phase,3.0,42,Tue,2024-10-22,21:00,Juventus,0.2,0,1,2.5,Stuttgart,41306,Allianz Stadium,Espen Eskås
44,League phase,3.0,43,Tue,2024-10-22,21:00,Real Madrid,3.5,5,2,1.6,Dortmund,74642,Estadio Santiago Bernabéu,István Kovács
45,League phase,3.0,44,Tue,2024-10-22,21:00,Girona,1.7,2,0,0.5,Slovan Bratislava,9246,Estadi Municipal de Montilivi,Horațiu Fesnic
46,League phase,3.0,45,Tue,2024-10-22,21:00,Paris Saint-Germain,2.5,1,1,0.2,PSV Eindhoven,47511,Parc des Princes,Glenn Nyberg
47,League phase,3.0,46,Wed,2024-10-23,18:45,Brest,0.5,1,1,1.0,Bayer Leverkusen,15510,Stade du Roudourou,Ivan Kružliak
48,League phase,3.0,47,Wed,2024-10-23,18:45,Atalanta,2.4,0,0,0.3,Celtic,21614,Gewiss Stadium,Irfan Peljto
49,League phase,3.0,48,Wed,2024-10-23,20:00,Benfica,1.7,1,3,1.0,Feyenoord,61687,Estádio do Sport Lisboa e Benfica,Halil Umut Meler
50,League phase,3.0,49,Wed,2024-10-23,20:00,Manchester City,2.9,5,0,0.2,Sparta Prague,50116,Etihad Stadium,Maurizio Mariani
51,League phase,3.0,50,Wed,2024-10-23,21:00,Red Bull Salzburg,1.2,0,2,1.6,Dinamo Zagreb,24018,Red Bull Arena,Danny Makkelie
52,League phase,3.0,51,Wed,2024-10-23,21:00,Young Boys,0.8,0,1,3.3,Internazionale,31500,Stadion Wankdorf,Michael Oliver
53,League phase,3.0,52,Wed,2024-10-23,21:00,Barcelona,2.2,4,1,1.0,Bayern Munich,50312,Estadi Olímpic Lluís Companys,Slavko Vinčič
54,League phase,3.0,53,Wed,2024-10-23,21:00,Atlético Madrid,2.3,1,3,1.3,Lille,61197,Riyadh Air Metropolitan Stadium,Marco Guida
55,League phase,3.0,54,Wed,2024-10-23,21:00,RB Leipzig,0.8,0,1,2.3,Liverpool,45228,Red Bull Arena,Sandro Schärer
57,League phase,4.0,55,Tue,2024-11-05,18:45,Slovan Bratislava,1.7,1,4,1.5,Dinamo Zagreb,22132,Štadión Tehelné pole,Anthony Taylor
58,League phase,4.0,56,Tue,2024-11-05,18:45,PSV Eindhoven,2.0,4,0,0.8,Girona,34400,Philips Stadion,Michael Oliver
59,League phase,4.0,57,Tue,2024-11-05,20:00,Sporting CP,2.9,4,1,2.1,Manchester City,47453,Estádio José Alvalade,Daniel Siebert
60,League phase,4.0,58,Tue,2024-11-05,20:00,Liverpool,3.7,4,0,0.9,Bayer Leverkusen,59790,Anfield,Danny Makkelie
61,League phase,4.0,59,Tue,2024-11-05,20:00,Celtic,1.8,3,1,1.3,RB Leipzig,57551,Celtic Park,Benoît Bastien
62,League phase,4.0,60,Tue,2024-11-05,21:00,Bologna,0.5,0,1,0.9,Monaco,23084,Stadio Renato Dall'Ara,Əliyar Ağayev
63,League phase,4.0,61,Tue,2024-11-05,21:00,Real Madrid,2.6,1,3,2.5,Milan,75561,Estadio Santiago Bernabéu,Slavko Vinčič
64,League phase,4.0,62,Tue,2024-11-05,21:00,Lille,0.8,1,1,1.4,Juventus,48312,Decathlon Arena - Stade Pierre-Mauroy,Irfan Peljto
65,League phase,4.0,63,Tue,2024-11-05,21:00,Dortmund,2.0,1,0,0.4,Sturm Graz,81365,Signal Iduna Park,Erik Lambrechts
66,League phase,4.0,64,Wed,2024-11-06,18:45,Club Brugge,1.4,1,0,0.4,Aston Villa,23466,Jan Breydelstadion,Tobias Stieler
67,League phase,4.0,65,Wed,2024-11-06,19:45,Shakhtar Donetsk,2.0,2,1,1.0,Young Boys,17420,Veltins-Arena,Orel Grinfeeld
68,League phase,4.0,66,Wed,2024-11-06,21:00,Paris Saint-Germain,2.1,1,2,0.7,Atlético Madrid,47369,Parc des Princes,Szymon Marciniak
69,League phase,4.0,67,Wed,2024-11-06,21:00,Bayern Munich,1.4,1,0,0.1,Benfica,75000,Allianz Arena,Davide Massa
70,League phase,4.0,68,Wed,2024-11-06,21:00,Red Star Belgrade,0.2,2,5,3.6,Barcelona,48886,Stadion Rajko Mitić,Espen Eskås
71,League phase,4.0,69,Wed,2024-11-06,21:00,Sparta Prague,0.5,1,2,1.6,Brest,18033,epet Arena,Mykola Balakin
72,League phase,4.0,70,Wed,2024-11-06,21:00,Feyenoord,0.8,1,3,1.7,Red Bull Salzburg,42774,Stadion Feijenoord,Donatas Rumšas
73,League phase,4.0,71,Wed,2024-11-06,21:00,Stuttgart,1.0,0,2,2.3,Atalanta,60000,MHPArena,Rade Obrenović
74,League phase,4.0,72,Wed,2024-11-06,21:00,Internazionale,1.1,1,0,1.8,Arsenal,75222,Stadio Giuseppe Meazza,István Kovács
76,League phase,5.0,73,Tue,2024-11-26,18:45,Slovan Bratislava,1.5,2,3,1.9,Milan,22500,Štadión Tehelné pole,Jose Maria Sánchez
77,League phase,5.0,74,Tue,2024-11-26,18:45,Sparta Prague,0.2,0,6,3.1,Atlético Madrid,18110,epet Arena,Danny Makkelie
78,League phase,5.0,75,Tue,2024-11-26,20:00,Manchester City,2.1,3,3,2.2,Feyenoord,47011,Etihad Stadium,Radu Petrescu
79,League phase,5.0,76,Tue,2024-11-26,20:00,Sporting CP,1.0,1,5,4.0,Arsenal,47386,Estádio José Alvalade,Szymon Marciniak
80,League phase,5.0,77,Tue,2024-11-26,21:00,Barcelona,2.8,3,0,0.1,Brest,46317,Estadi Olímpic Lluís Companys,Irfan Peljto
81,League phase,5.0,78,Tue,2024-11-26,21:00,Bayer Leverkusen,4.3,5,0,0.3,Red Bull Salzburg,29211,BayArena,Mykola Balakin
82,League phase,5.0,79,Tue,2024-11-26,21:00,Internazionale,1.4,1,0,0.1,RB Leipzig,63174,Stadio Giuseppe Meazza,João Pinheiro
83,League phase,5.0,80,Tue,2024-11-26,21:00,Bayern Munich,2.4,1,0,0.8,Paris Saint-Germain,75000,Allianz Arena,István Kovács
84,League phase,5.0,81,Tue,2024-11-26,21:00,Young Boys,0.8,1,6,2.5,Atalanta,31500,Stadion Wankdorf,Manfredas Lukjančukas
85,League phase,5.0,82,Wed,2024-11-27,18:45,Red Star Belgrade,1.8,5,1,0.6,Stuttgart,41372,Stadion Rajko Mitić,Erik Lambrechts
86,League phase,5.0,83,Wed,2024-11-27,18:45,Sturm Graz,0.8,1,0,1.7,Girona,21502,Merkur Arena,Rohit Saggi
87,League phase,5.0,84,Wed,2024-11-27,20:00,Aston Villa,1.2,0,0,0.4,Juventus,42589,Villa Park,Jesús Gil
88,League phase,5.0,85,Wed,2024-11-27,20:00,Liverpool,2.7,2,0,1.2,Real Madrid,59546,Anfield,François Letexier
89,League phase,5.0,86,Wed,2024-11-27,20:00,Celtic,1.0,1,1,1.1,Club Brugge,57456,Celtic Park,Georgi Kabakov
90,League phase,5.0,87,Wed,2024-11-27,21:00,PSV Eindhoven,2.6,3,2,1.0,Shakhtar Donetsk,35100,Philips Stadion,Urs Schnyder
91,League phase,5.0,88,Wed,2024-11-27,21:00,Bologna,1.7,1,2,2.1,Lille,22420,Stadio Renato Dall'Ara,Michael Oliver
92,League phase,5.0,89,Wed,2024-11-27,21:00,Dinamo Zagreb,0.2,0,3,1.7,Dortmund,20019,Stadion Maksimir,Clément Turpin
93,League phase,5.0,90,Wed,2024-11-27,21:00,Monaco,1.6,2,3,3.0,Benfica,13581,Stade Louis II,Rade Obrenović
95,League phase,6.0,91,Tue,2024-12-10,18:45,Dinamo Zagreb,0.5,0,0,0.4,Celtic,18158,Stadion Maksimir,Felix Zwayer
96,League phase,6.0,92,Tue,2024-12-10,18:45,Girona,1.2,0,1,1.8,Liverpool,9241,Estadi Municipal de Montilivi,Benoît Bastien
97,League phase,6.0,93,Tue,2024-12-10,21:00,Bayer Leverkusen,1.1,1,0,0.3,Internazionale,30210,BayArena,Slavko Vinčič
98,League phase,6.0,94,Tue,2024-12-10,21:00,Brest,1.6,1,0,1.6,PSV Eindhoven,15778,Stade du Roudourou,Jose Maria Sánchez
99,League phase,6.0,95,Tue,2024-12-10,21:00,Club Brugge,1.0,2,1,1.2,Sporting CP,22254,Jan Breydelstadion,Anthony Taylor
100,League phase,6.0,96,Tue,2024-12-10,21:00,Red Bull Salzburg,0.2,0,3,3.2,Paris Saint-Germain,25065,Red Bull Arena,Michael Oliver
101,League phase,6.0,97,Tue,2024-12-10,21:00,RB Leipzig,2.2,2,3,2.1,Aston Villa,40406,Red Bull Arena,Maurizio Mariani
102,League phase,6.0,98,Tue,2024-12-10,21:00,Atalanta,3.3,2,3,2.1,Real Madrid,22967,Gewiss Stadium,Szymon Marciniak
103,League phase,6.0,99,Tue,2024-12-10,22:00,Shakhtar Donetsk,1.2,1,5,3.6,Bayern Munich,57079,Veltins-Arena,Halil Umut Meler
104,League phase,6.0,100,Wed,2024-12-11,18:45,Lille,2.0,3,2,1.3,Sturm Graz,45796,Decathlon Arena - Stade Pierre-Mauroy,Georgi Kabakov
105,League phase,6.0,101,Wed,2024-12-11,18:45,Atlético Madrid,2.0,3,1,1.0,Slovan Bratislava,59134,Riyadh Air Metropolitan Stadium,Manfredas Lukjančukas
106,League phase,6.0,102,Wed,2024-12-11,20:00,Arsenal,2.3,3,0,0.5,Monaco,60157,Emirates Stadium,Davide Massa
107,League phase,6.0,103,Wed,2024-12-11,20:00,Benfica,1.3,0,0,0.2,Bologna,60650,Estádio do Sport Lisboa e Benfica,Radu Petrescu
108,League phase,6.0,104,Wed,2024-12-11,21:00,Milan,2.0,2,1,0.4,Red Star Belgrade,53717,Stadio Giuseppe Meazza,Jesús Gil
109,League phase,6.0,105,Wed,2024-12-11,21:00,Juventus,1.1,2,0,1.2,Manchester City,40890,Allianz Stadium,Clément Turpin
110,League phase,6.0,106,Wed,2024-12-11,21:00,Stuttgart,2.3,5,1,0.2,Young Boys,60000,MHPArena,Giorgi Kruashvili
111,League phase,6.0,107,Wed,2024-12-11,21:00,Dortmund,2.7,2,3,2.0,Barcelona,81365,Signal Iduna Park,François Letexier
112,League phase,6.0,108,Wed,2024-12-11,21:00,Feyenoord,1.0,4,2,0.7,Sparta Prague,45000,Stadion Feijenoord,Tobias Stieler
114,League phase,7.0,109,Tue,2025-01-21,18:45,Atalanta,4.9,5,0,0.8,Sturm Graz,19469,Gewiss Stadium,Donatas Rumšas
115,League phase,7.0,110,Tue,2025-01-21,18:45,Monaco,1.5,1,0,0.9,Aston Villa,13508,Stade Louis II,Slavko Vinčič
116,League phase,7.0,111,Tue,2025-01-21,20:00,Liverpool,2.5,2,1,0.5,Lille,59782,Anfield,Felix Zwayer
117,League phase,7.0,112,Tue,2025-01-21,20:00,Benfica,3.3,4,5,3.6,Barcelona,63225,Estádio do Sport Lisboa e Benfica,Danny Makkelie
118,League phase,7.0,113,Tue,2025-01-21,21:00,Bologna,2.1,2,1,1.0,Dortmund,26801,Stadio Renato Dall'Ara,Serdar Gözübüyük
119,League phase,7.0,114,Tue,2025-01-21,21:00,Club Brugge,0.7,0,0,0.4,Juventus,26700,Jan Breydelstadion,Benoît Bastien
120,League phase,7.0,115,Tue,2025-01-21,21:00,Red Star Belgrade,2.6,2,3,0.8,PSV Eindhoven,36648,Stadion Rajko Mitić,István Kovács
121,League phase,7.0,116,Tue,2025-01-21,21:00,Slovan Bratislava,0.6,1,3,3.4,Stuttgart,22500,Štadión Tehelné pole,Chris Kavanagh
122,League phase,7.0,117,Tue,2025-01-21,21:00,Atlético Madrid,0.8,2,1,0.8,Bayer Leverkusen,66820,Riyadh Air Metropolitan Stadium,Davide Massa
123,League phase,7.0,118,Wed,2025-01-22,18:45,RB Leipzig,2.3,2,1,0.9,Sporting CP,33478,Red Bull Arena,Manfredas Lukjančukas
124,League phase,7.0,119,Wed,2025-01-22,19:45,Shakhtar Donetsk,1.9,2,0,0.4,Brest,15282,Veltins-Arena,Sandro Schärer
125,League phase,7.0,120,Wed,2025-01-22,20:00,Arsenal,2.4,3,0,0.1,Dinamo Zagreb,60024,Emirates Stadium,Daniel Siebert
126,League phase,7.0,121,Wed,2025-01-22,20:00,Celtic,1.8,1,0,1.0,Young Boys,56544,Celtic Park,Rohit Saggi
127,League phase,7.0,122,Wed,2025-01-22,21:00,Real Madrid,2.8,5,1,0.4,Red Bull Salzburg,73692,Estadio Santiago Bernabéu,Glenn Nyberg
128,League phase,7.0,123,Wed,2025-01-22,21:00,Milan,1.3,1,0,1.0,Girona,66030,Stadio Giuseppe Meazza,Tobias Stieler
129,League phase,7.0,124,Wed,2025-01-22,21:00,Paris Saint-Germain,2.8,4,2,1.7,Manchester City,47818,Parc des Princes,Szymon Marciniak
130,League phase,7.0,125,Wed,2025-01-22,21:00,Sparta Prague,0.4,0,1,0.9,Internazionale,18010,epet Arena,Alejandro Hernández
131,League phase,7.0,126,Wed,2025-01-22,21:00,Feyenoord,1.7,3,0,2.4,Bayern Munich,43106,Stadion Feijenoord,François Letexier
133,League phase,8.0,127,Wed,2025-01-29,20:00,Manchester City,2.0,3,1,1.1,Club Brugge,51237,Etihad Stadium,Jose Maria Sánchez
134,League phase,8.0,128,Wed,2025-01-29,20:00,Aston Villa,3.9,4,2,0.8,Celtic,42824,Villa Park,Clément Turpin
135,League phase,8.0,129,Wed,2025-01-29,20:00,Sporting CP,1.3,1,1,1.1,Bologna,37328,Estádio José Alvalade,Benoît Bastien
136,League phase,8.0,130,Wed,2025-01-29,21:00,Bayern Munich,3.7,3,1,0.9,Slovan Bratislava,75000,Allianz Arena,João Pinheiro
137,League phase,8.0,131,Wed,2025-01-29,21:00,Juventus,0.9,0,2,2.2,Benfica,41402,Allianz Stadium,István Kovács
138,League phase,8.0,132,Wed,2025-01-29,21:00,Barcelona,2.4,2,2,1.2,Atalanta,42728,Estadi Olímpic Lluís Companys,Michael Oliver
139,League phase,8.0,133,Wed,2025-01-29,21:00,Dortmund,2.4,3,1,0.4,Shakhtar Donetsk,81365,Signal Iduna Park,Glenn Nyberg
140,League phase,8.0,134,Wed,2025-01-29,21:00,Brest,1.4,0,3,2.6,Real Madrid,15405,Stade du Roudourou,Espen Eskås
141,League phase,8.0,135,Wed,2025-01-29,21:00,PSV Eindhoven,1.3,3,2,1.6,Liverpool,35000,Philips Stadion,Tobias Stieler
142,League phase,8.0,136,Wed,2025-01-29,21:00,Internazionale,3.9,3,0,0.2,Monaco,71601,Stadio Giuseppe Meazza,Irfan Peljto
143,League phase,8.0,137,Wed,2025-01-29,21:00,Bayer Leverkusen,1.7,2,0,0.7,Sparta Prague,30210,BayArena,Georgi Kabakov
144,League phase,8.0,138,Wed,2025-01-29,21:00,Stuttgart,0.8,1,4,2.4,Paris Saint-Germain,60000,MHPArena,Davide Massa
145,League phase,8.0,139,Wed,2025-01-29,21:00,Lille,1.3,6,1,0.7,Feyenoord,44071,Decathlon Arena - Stade Pierre-Mauroy,Slavko Vinčič
146,League phase,8.0,140,Wed,2025-01-29,21:00,Sturm Graz,1.3,1,0,1.5,RB Leipzig,26851,28 Black Arena,Mykola Balakin
147,League phase,8.0,141,Wed,2025-01-29,21:00,Young Boys,0.4,0,1,1.8,Red Star Belgrade,31500,Stadion Wankdorf,Halil Umut Meler
148,League phase,8.0,142,Wed,2025-01-29,21:00,Girona,0.7,1,2,2.1,Arsenal,9048,Estadi Municipal de Montilivi,Maurizio Mariani
149,League phase,8.0,143,Wed,2025-01-29,21:00,Dinamo Zagreb,1.4,2,1,1.1,Milan,18856,Stadion Maksimir,François Letexier
150,League phase,8.0,144,Wed,2025-01-29,21:00,Red Bull Salzburg,0.6,1,4,2.1,Atlético Madrid,23389,Red Bull Arena,Anthony Taylor
152,Knockout phase play-offs,NaN,145,Tue,2025-02-11,18:45,Brest,0.9,0,3,2.6,Paris Saint-Germain,15831,Stade du Roudourou,Irfan Peljto
153,Knockout phase play-offs,NaN,146,Tue,2025-02-11,20:00,Manchester City,1.5,2,3,3.2,Real Madrid,52081,Etihad Stadium,Clément Turpin
154,Knockout phase play-offs,NaN,147,Tue,2025-02-11,20:00,Sporting CP,0.7,0,3,1.8,Dortmund,41543,Estádio José Alvalade,Espen Eskås
155,Knockout phase play-offs,NaN,148,Tue,2025-02-11,21:00,Juventus,1.4,2,1,0.8,PSV Eindhoven,39886,Allianz Stadium,Daniel Siebert
156,Knockout phase play-offs,NaN,149,Wed,2025-02-12,18:45,Club Brugge,1.4,2,1,1.0,Atalanta,24242,Jan Breydelstadion,Halil Umut Meler
157,Knockout phase play-offs,NaN,150,Wed,2025-02-12,20:00,Celtic,1.3,1,2,0.7,Bayern Munich,57406,Celtic Park,Jesús Gil
158,Knockout phase play-offs,NaN,151,Wed,2025-02-12,21:00,Monaco,0.4,0,1,2.1,Benfica,12159,Stade Louis II,Maurizio Mariani
159,Knockout phase play-offs,NaN,152,Wed,2025-02-12,21:00,Feyenoord,0.5,1,0,0.6,Milan,45000,Stadion Feijenoord,Jose Maria Sánchez
160,Knockout phase play-offs,NaN,153,Tue,2025-02-18,18:45,Milan,1.7,1,1,0.9,Feyenoord,54749,Stadio Giuseppe Meazza,Szymon Marciniak
161,Knockout phase play-offs,NaN,154,Tue,2025-02-18,20:00,Benfica,1.9,3,3,1.5,Monaco,60776,Estádio do Sport Lisboa e Benfica,Glenn Nyberg
162,Knockout phase play-offs,NaN,155,Tue,2025-02-18,21:00,Atalanta,3.1,1,3,1.1,Club Brugge,21727,Gewiss Stadium,Felix Zwayer
163,Knockout phase play-offs,NaN,156,Tue,2025-02-18,21:00,Bayern Munich,2.3,1,1,1.3,Celtic,75000,Allianz Arena,Benoît Bastien
164,Knockout phase play-offs,NaN,157,Wed,2025-02-19,18:45,Dortmund,1.9,0,0,0.4,Sporting CP,80300,Signal Iduna Park,Davide Massa
165,Knockout phase play-offs,NaN,158,Wed,2025-02-19,21:00,Real Madrid,1.8,3,1,1.3,Manchester City,77023,Estadio Santiago Bernabéu,István Kovács
166,Knockout phase play-offs,NaN,159,Wed,2025-02-19,21:00,PSV Eindhoven,3.4,3,1,1.7,Juventus,35000,Philips Stadion,Slavko Vinčič
167,Knockout phase play-offs,NaN,160,Wed,2025-02-19,21:00,Paris Saint-Germain,3.2,7,0,0.9,Brest,47211,Parc des Princes,Michael Oliver
168,Round of 16,NaN,161,Tue,2025-03-04,18:45,Club Brugge,1.1,1,3,1.4,Aston Villa,26890,Jan Breydelstadion,João Pinheiro
169,Round of 16,NaN,162,Tue,2025-03-04,21:00,PSV Eindhoven,1.4,1,7,1.9,Arsenal,34400,Philips Stadion,Jesús Gil
170,Round of 16,NaN,163,Tue,2025-03-04,21:00,Real Madrid,0.7,2,1,0.2,Atlético Madrid,77261,Estadio Santiago Bernabéu,Clément Turpin
171,Round of 16,NaN,164,Tue,2025-03-04,21:00,Dortmund,0.3,1,1,0.9,Lille,81365,Signal Iduna Park,Jose Maria Sánchez

In [21]:
squads_df = pd.unique(df[['Home', 'Away']].values.ravel('K'))
squads_df1 = df1['Squad'].unique()

# Times em df que não estão em df1
nao_em_df1 = list(set(squads_df) - set(squads_df1))

# Times em df1 que não estão em df
nao_em_df = list(set(squads_df1) - set(squads_df))

print("Squads in df and out of df1:", not_in_df1)
print("Squads in df1 and out of df:", not_in_df)

Squads in df and out of df1: ['Inter', 'Leverkusen', 'Red Star', 'Shakhtar', 'RB Salzburg', 'Paris S-G']
Squads in df1 and out of df: ['Red Bull Salzburg', 'Paris Saint-Germain', 'Bayer Leverkusen', 'Shakhtar Donetsk', 'Red Star Belgrade', 'Internazionale']

In [22]:
#raise SystemExit

In [23]:
file_path = '/content/drive/MyDrive/Dados/Projetos/UCL_2425/fixturesucl2425.csv'

# Mount Google Drive to save file (if necessary)
drive.mount('/content/drive')

#df.to_csv(file_path, index=False)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).